apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels: 
    name: mongodb
spec: 
  containers: 
    - resources:
        limits :
          cpu: 0.5
      image: mongo
      name: mongodb
      ports: 
        - containerPort: 27017
          hostPort: 27017
          name: mongo
      volumeMounts:
#         # name must match the volume name below
        - name: mongo-persistent-storage
#          # mount path within the container
          mountPath: /data/db
  volumes:
    - name: mongo-persistent-storage
      awsElasticBlockStore:
        volumeID: aws://YOUR-REGION/YOUR-VOLNAME
        fsType: ext3

