version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Europe/Rome
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: express-validator
    versions:
    - 6.10.0
    - 6.10.1
    - 6.9.2
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: redis
    versions:
    - 3.1.0
  - dependency-name: stripe
    versions:
    - 8.134.0
    - 8.135.0
    - 8.137.0
    - 8.138.0
    - 8.140.0
    - 8.142.0
  - dependency-name: "@babel/register"
    versions:
    - 7.12.13
    - 7.13.14
    - 7.13.8
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
  - dependency-name: jwks-rsa
    versions:
    - 1.12.3
    - 2.0.1
    - 2.0.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: image-size
    versions:
    - 0.9.4
    - 0.9.5
    - 0.9.7
  - dependency-name: winston-loggly-bulk
    versions:
    - 3.2.0
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.3
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: "@google-cloud/trace-agent"
    versions:
    - 5.1.2
  - dependency-name: monk
    versions:
    - 7.3.3
- package-ecosystem: npm
  directory: "/website/client"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Europe/Rome
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
    - 7.9.0
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - 6.1.17
    - 6.1.18
    - 6.1.20
    - 6.1.21
    - 6.2.2
    - 6.2.3
    - 6.2.7
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.1.17
    - 6.1.18
    - 6.1.20
    - 6.1.21
    - 6.2.2
    - 6.2.3
    - 6.2.7
  - dependency-name: "@storybook/vue"
    versions:
    - 6.1.17
    - 6.1.18
    - 6.1.20
    - 6.1.21
    - 6.2.2
    - 6.2.3
    - 6.2.7
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.1.17
    - 6.1.18
    - 6.1.20
    - 6.1.21
    - 6.2.2
    - 6.2.3
    - 6.2.7
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.9.0
    - 3.9.1
  - dependency-name: bootstrap
    versions:
    - 4.6.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: hellojs
    versions:
    - 1.18.8
    - 1.19.2
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.3
  - dependency-name: amplitude-js
    versions:
    - 7.4.2
    - 7.4.3
    - 7.4.4
  - dependency-name: pug
    versions:
    - 3.0.2
  - dependency-name: sass
    versions:
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.2
    - 1.1.3
  - dependency-name: intro.js
    versions:
    - 3.2.1
    - 3.3.1
  - dependency-name: sass-loader
    versions:
    - 10.1.1
