FROM node:20

# Install global packages
RUN npm install -g gulp-cli mocha

# Copy package.json and package-lock.json into image, then install
# dependencies.
COPY . /usr/src/habitica
WORKDIR /usr/src/habitica
RUN npm install
RUN npm run postinstall
RUN npm run client:build
RUN gulp build:prod