// Generated by CoffeeScript 1.3.3

module.exports = function(expressApp) {
  return expressApp.get('/:uid/up/:score?', function(req, res) {
    var model, score;
    score = parseInt(req.params.score) || 1;
    console.log({
      score: score
    });
    model = req.getModel();
    model.fetch("users." + req.params.uid, function(err, user) {
      if (err || !user.get()) {
        return;
      }
      return user.set('stats.exp', parseInt(user.get('stats.exp')) + score);
    });
    return res.send(200);
  });
};
