// Generated by CoffeeScript 1.3.3
var scoring;

scoring = require('../app/scoring');

module.exports = function(expressApp) {
  expressApp.get('/:uid/up/:score?', function(req, res) {
    var model, score;
    score = parseInt(req.params.score) || 1;
    console.log({
      score: score
    });
    model = req.getModel();
    model.fetch("users." + req.params.uid, function(err, user) {
      if (err || !user.get()) {
        return;
      }
      return scoring.score({
        user: user,
        direction: 'up'
      });
    });
    return res.send(200);
  });
  return expressApp.get('/:uid/down/:score?', function(req, res) {
    var model, score;
    score = parseInt(req.params.score) || 1;
    console.log({
      score: score
    });
    model = req.getModel();
    model.fetch("users." + req.params.uid, function(err, user) {
      if (err || !user.get()) {
        return;
      }
      return scoring.score({
        user: user,
        direction: 'down'
      });
    });
    return res.send(200);
  });
};
