// Generated by CoffeeScript 1.3.3
var MongoStore, ONE_YEAR, app, derby, exports, express, expressApp, gzippo, http, path, publicPath, racer, root, server, serverError;

http = require('http');

path = require('path');

express = require('express');

gzippo = require('gzippo');

MongoStore = require('connect-mongo')(express);

derby = require('derby');

app = require('../app');

serverError = require('./serverError');

racer = require('derby/node_modules/racer');

racer.set('transports', ['xhr-polling']);

ONE_YEAR = 1000 * 60 * 60 * 24 * 365;

root = path.dirname(path.dirname(__dirname));

publicPath = path.join(root, 'public');

(expressApp = express()).use(express.favicon()).use(gzippo.staticGzip(publicPath, {
  maxAge: ONE_YEAR
})).use(express.compress()).use(express.cookieParser('secret_sauce')).use(express.session({
  secret: 'secret_sauce',
  cookie: {
    maxAge: ONE_YEAR
  },
  store: new MongoStore({
    url: process.env.NODE_DB_URI,
    collection: 'express-sessions'
  })
})).use(app.session()).use(app.router()).use(expressApp.router).use(serverError(root));

exports = module.exports = server = http.createServer(expressApp);

expressApp.all('*', function(req) {
  throw "404: " + req.url;
});

derby.use(require('racer-db-mongo'));

exports.store = app.createStore({
  listen: server,
  db: {
    type: 'Mongo',
    uri: process.env.NODE_DB_URI
  }
});
