// Generated by CoffeeScript 1.4.0

module.exports.middleware = function(req, res, next) {
  return next();
};

module.exports.app = function(appExports, model) {};

module.exports.routes = function(expressApp) {};
