import { ownsItem } from '../gear-helper';
import t from '../../translation';

const armor = {
  lunarArmor: {
    text: t('armorArmoireLunarArmorText'),
    notes: t('armorArmoireLunarArmorNotes', { str: 7, int: 7 }),
    value: 100,
    str: 7,
    int: 7,
    set: 'soothing',
    canOwn: ownsItem('armor_armoire_lunarArmor'),
    canBuy: () => true,
  },
  gladiatorArmor: {
    text: t('armorArmoireGladiatorArmorText'),
    notes: t('armorArmoireGladiatorArmorNotes', { str: 7, per: 7 }),
    value: 100,
    str: 7,
    per: 7,
    set: 'gladiator',
    canOwn: ownsItem('armor_armoire_gladiatorArmor'),
    canBuy: () => true,
  },
  rancherRobes: {
    text: t('armorArmoireRancherRobesText'),
    notes: t('armorArmoireRancherRobesNotes', { str: 5, per: 5, int: 5 }),
    value: 100,
    str: 5,
    per: 5,
    int: 5,
    set: 'rancher',
    canOwn: ownsItem('armor_armoire_rancherRobes'),
    canBuy: () => true,
  },
  goldenToga: {
    text: t('armorArmoireGoldenTogaText'),
    notes: t('armorArmoireGoldenTogaNotes', { attrs: 8 }),
    value: 100,
    str: 8,
    con: 8,
    set: 'goldenToga',
    canOwn: ownsItem('armor_armoire_goldenToga'),
    canBuy: () => true,
  },
  hornedIronArmor: {
    text: t('armorArmoireHornedIronArmorText'),
    notes: t('armorArmoireHornedIronArmorNotes', { con: 9, per: 7 }),
    value: 100,
    con: 9,
    per: 7,
    set: 'hornedIron',
    canOwn: ownsItem('armor_armoire_hornedIronArmor'),
    canBuy: () => true,
  },
  plagueDoctorOvercoat: {
    text: t('armorArmoirePlagueDoctorOvercoatText'),
    notes: t('armorArmoirePlagueDoctorOvercoatNotes', { int: 6, str: 5, con: 6 }),
    value: 100,
    int: 6,
    str: 5,
    con: 6,
    set: 'plagueDoctor',
    canOwn: ownsItem('armor_armoire_plagueDoctorOvercoat'),
    canBuy: () => true,
  },
  shepherdRobes: {
    text: t('armorArmoireShepherdRobesText'),
    notes: t('armorArmoireShepherdRobesNotes', { attrs: 9 }),
    value: 100,
    str: 9,
    per: 9,
    set: 'shepherd',
    canOwn: ownsItem('armor_armoire_shepherdRobes'),
    canBuy: () => true,
  },
  royalRobes: {
    text: t('armorArmoireRoyalRobesText'),
    notes: t('armorArmoireRoyalRobesNotes', { attrs: 5 }),
    value: 100,
    con: 5,
    per: 5,
    int: 5,
    set: 'royal',
    canOwn: ownsItem('armor_armoire_royalRobes'),
    canBuy: () => true,
  },
  crystalCrescentRobes: {
    text: t('armorArmoireCrystalCrescentRobesText'),
    notes: t('armorArmoireCrystalCrescentRobesNotes', { attrs: 7 }),
    value: 100,
    per: 7,
    con: 7,
    set: 'crystalCrescent',
    canOwn: ownsItem('armor_armoire_crystalCrescentRobes'),
    canBuy: () => true,
  },
  dragonTamerArmor: {
    text: t('armorArmoireDragonTamerArmorText'),
    notes: t('armorArmoireDragonTamerArmorNotes', { con: 15 }),
    value: 100,
    con: 15,
    set: 'dragonTamer',
    canOwn: ownsItem('armor_armoire_dragonTamerArmor'),
    canBuy: () => true,
  },
  barristerRobes: {
    text: t('armorArmoireBarristerRobesText'),
    notes: t('armorArmoireBarristerRobesNotes', { con: 10 }),
    value: 100,
    con: 10,
    set: 'barrister',
    canOwn: ownsItem('armor_armoire_barristerRobes'),
    canBuy: () => true,
  },
  jesterCostume: {
    text: t('armorArmoireJesterCostumeText'),
    notes: t('armorArmoireJesterCostumeNotes', { int: 15 }),
    value: 100,
    int: 15,
    set: 'jester',
    canOwn: ownsItem('armor_armoire_jesterCostume'),
    canBuy: () => true,
  },
  minerOveralls: {
    text: t('armorArmoireMinerOverallsText'),
    notes: t('armorArmoireMinerOverallsNotes', { con: 10 }),
    value: 100,
    con: 10,
    set: 'miner',
    canOwn: ownsItem('armor_armoire_minerOveralls'),
    canBuy: () => true,
  },
  basicArcherArmor: {
    text: t('armorArmoireBasicArcherArmorText'),
    notes: t('armorArmoireBasicArcherArmorNotes', { per: 12 }),
    value: 100,
    per: 12,
    set: 'basicArcher',
    canOwn: ownsItem('armor_armoire_basicArcherArmor'),
    canBuy: () => true,
  },
  graduateRobe: {
    text: t('armorArmoireGraduateRobeText'),
    notes: t('armorArmoireGraduateRobeNotes', { int: 10 }),
    value: 100,
    int: 10,
    set: 'graduate',
    canOwn: ownsItem('armor_armoire_graduateRobe'),
    canBuy: () => true,
  },
  stripedSwimsuit: {
    text: t('armorArmoireStripedSwimsuitText'),
    notes: t('armorArmoireStripedSwimsuitNotes', { con: 13 }),
    value: 100,
    con: 13,
    set: 'seaside',
    canOwn: ownsItem('armor_armoire_stripedSwimsuit'),
    canBuy: () => true,
  },
  cannoneerRags: {
    text: t('armorArmoireCannoneerRagsText'),
    notes: t('armorArmoireCannoneerRagsNotes', { con: 15 }),
    value: 100,
    con: 15,
    set: 'cannoneer',
    canOwn: ownsItem('armor_armoire_cannoneerRags'),
    canBuy: () => true,
  },
  falconerArmor: {
    text: t('armorArmoireFalconerArmorText'),
    notes: t('armorArmoireFalconerArmorNotes', { con: 10 }),
    value: 100,
    con: 10,
    set: 'falconer',
    canOwn: ownsItem('armor_armoire_falconerArmor'),
    canBuy: () => true,
  },
  vermilionArcherArmor: {
    text: t('armorArmoireVermilionArcherArmorText'),
    notes: t('armorArmoireVermilionArcherArmorNotes', { per: 15 }),
    value: 100,
    per: 15,
    set: 'vermilionArcher',
    canOwn: ownsItem('armor_armoire_vermilionArcherArmor'),
    canBuy: () => true,
  },
  ogreArmor: {
    text: t('armorArmoireOgreArmorText'),
    notes: t('armorArmoireOgreArmorNotes', { con: 15 }),
    value: 100,
    con: 15,
    set: 'ogre',
    canOwn: ownsItem('armor_armoire_ogreArmor'),
    canBuy: () => true,
  },
  ironBlueArcherArmor: {
    text: t('armorArmoireIronBlueArcherArmorText'),
    notes: t('armorArmoireIronBlueArcherArmorNotes', { str: 12 }),
    value: 100,
    str: 12,
    set: 'blueArcher',
    canOwn: ownsItem('armor_armoire_ironBlueArcherArmor'),
    canBuy: () => true,
  },
  redPartyDress: {
    text: t('armorArmoireRedPartyDressText'),
    notes: t('armorArmoireRedPartyDressNotes', { attrs: 7 }),
    value: 100,
    str: 7,
    con: 7,
    int: 7,
    set: 'redHairbow',
    canOwn: ownsItem('armor_armoire_redPartyDress'),
    canBuy: () => true,
  },
  woodElfArmor: {
    text: t('armorArmoireWoodElfArmorText'),
    notes: t('armorArmoireWoodElfArmorNotes', { per: 12 }),
    value: 100,
    per: 12,
    set: 'woodElf',
    canOwn: ownsItem('armor_armoire_woodElfArmor'),
    canBuy: () => true,
  },
  ramFleeceRobes: {
    text: t('armorArmoireRamFleeceRobesText'),
    notes: t('armorArmoireRamFleeceRobesNotes', { con: 9, str: 7 }),
    value: 100,
    con: 9,
    str: 7,
    set: 'ramBarbarian',
    canOwn: ownsItem('armor_armoire_ramFleeceRobes'),
    canBuy: () => true,
  },
  gownOfHearts: {
    text: t('armorArmoireGownOfHeartsText'),
    notes: t('armorArmoireGownOfHeartsNotes', { con: 13 }),
    value: 100,
    con: 13,
    set: 'queenOfHearts',
    canOwn: ownsItem('armor_armoire_gownOfHearts'),
    canBuy: () => true,
  },
  mushroomDruidArmor: {
    text: t('armorArmoireMushroomDruidArmorText'),
    notes: t('armorArmoireMushroomDruidArmorNotes', { con: 7, per: 8 }),
    value: 100,
    con: 7,
    per: 8,
    set: 'mushroomDruid',
    canOwn: ownsItem('armor_armoire_mushroomDruidArmor'),
    canBuy: () => true,
  },
  greenFestivalYukata: {
    text: t('armorArmoireGreenFestivalYukataText'),
    notes: t('armorArmoireGreenFestivalYukataNotes', { attrs: 8 }),
    value: 100,
    con: 8,
    per: 8,
    set: 'festivalAttire',
    canOwn: ownsItem('armor_armoire_greenFestivalYukata'),
    canBuy: () => true,
  },
  merchantTunic: {
    text: t('armorArmoireMerchantTunicText'),
    notes: t('armorArmoireMerchantTunicNotes', { per: 10 }),
    value: 100,
    per: 10,
    set: 'merchant',
    canOwn: ownsItem('armor_armoire_merchantTunic'),
    canBuy: () => true,
  },
  vikingTunic: {
    text: t('armorArmoireVikingTunicText'),
    notes: t('armorArmoireVikingTunicNotes', { con: 6, str: 8 }),
    value: 100,
    con: 6,
    str: 8,
    set: 'viking',
    canOwn: ownsItem('armor_armoire_vikingTunic'),
    canBuy: () => true,
  },
  swanDancerTutu: {
    text: t('armorArmoireSwanDancerTutuText'),
    notes: t('armorArmoireSwanDancerTutuNotes', { attrs: 8 }),
    value: 100,
    int: 8,
    str: 8,
    set: 'swanDancer',
    canOwn: ownsItem('armor_armoire_swanDancerTutu'),
    canBuy: () => true,
  },
  yellowPartyDress: {
    text: t('armorArmoireYellowPartyDressText'),
    notes: t('armorArmoireYellowPartyDressNotes', { attrs: 7 }),
    value: 100,
    per: 7,
    int: 7,
    str: 7,
    set: 'yellowHairbow',
    canOwn: ownsItem('armor_armoire_yellowPartyDress'),
    canBuy: () => true,
  },
  antiProcrastinationArmor: {
    text: t('armorArmoireAntiProcrastinationArmorText'),
    notes: t('armorArmoireAntiProcrastinationArmorNotes', { str: 15 }),
    value: 100,
    str: 15,
    set: 'antiProcrastination',
    canOwn: ownsItem('armor_armoire_antiProcrastinationArmor'),
    canBuy: () => true,
  },
  farrierOutfit: {
    text: t('armorArmoireFarrierOutfitText'),
    notes: t('armorArmoireFarrierOutfitNotes', { attrs: 6 }),
    value: 100,
    con: 6,
    int: 6,
    per: 6,
    set: 'farrier',
    canOwn: ownsItem('armor_armoire_farrierOutfit'),
    canBuy: () => true,
  },
  candlestickMakerOutfit: {
    text: t('armorArmoireCandlestickMakerOutfitText'),
    notes: t('armorArmoireCandlestickMakerOutfitNotes', { con: 12 }),
    value: 100,
    con: 12,
    set: 'candlestickMaker',
    canOwn: ownsItem('armor_armoire_candlestickMakerOutfit'),
    canBuy: () => true,
  },
  wovenRobes: {
    text: t('armorArmoireWovenRobesText'),
    notes: t('armorArmoireWovenRobesNotes', { con: 8, int: 9 }),
    value: 100,
    con: 8,
    int: 9,
    set: 'weaver',
    canOwn: ownsItem('armor_armoire_wovenRobes'),
    canBuy: () => true,
  },
  lamplightersGreatcoat: {
    text: t('armorArmoireLamplightersGreatcoatText'),
    notes: t('armorArmoireLamplightersGreatcoatNotes', { per: 14 }),
    value: 100,
    per: 14,
    set: 'lamplighter',
    canOwn: ownsItem('armor_armoire_lamplightersGreatcoat'),
    canBuy: () => true,
  },
  coachDriverLivery: {
    text: t('armorArmoireCoachDriverLiveryText'),
    notes: t('armorArmoireCoachDriverLiveryNotes', { str: 12 }),
    value: 100,
    str: 12,
    set: 'coachDriver',
    canOwn: ownsItem('armor_armoire_coachDriverLivery'),
    canBuy: () => true,
  },
  robeOfDiamonds: {
    text: t('armorArmoireRobeOfDiamondsText'),
    notes: t('armorArmoireRobeOfDiamondsNotes', { per: 13 }),
    value: 100,
    per: 13,
    set: 'kingOfDiamonds',
    canOwn: ownsItem('armor_armoire_robeOfDiamonds'),
    canBuy: () => true,
  },
  flutteryFrock: {
    text: t('armorArmoireFlutteryFrockText'),
    notes: t('armorArmoireFlutteryFrockNotes', { attrs: 5 }),
    value: 100,
    con: 5,
    per: 5,
    str: 5,
    set: 'fluttery',
    canOwn: ownsItem('armor_armoire_flutteryFrock'),
    canBuy: () => true,
  },
  cobblersCoveralls: {
    text: t('armorArmoireCobblersCoverallsText'),
    notes: t('armorArmoireCobblersCoverallsNotes', { attrs: 7 }),
    value: 100,
    per: 7,
    str: 7,
    set: 'cobbler',
    canOwn: ownsItem('armor_armoire_cobblersCoveralls'),
    canBuy: () => true,
  },
  glassblowersCoveralls: {
    text: t('armorArmoireGlassblowersCoverallsText'),
    notes: t('armorArmoireGlassblowersCoverallsNotes', { con: 8 }),
    value: 100,
    con: 8,
    set: 'glassblower',
    canOwn: ownsItem('armor_armoire_glassblowersCoveralls'),
    canBuy: () => true,
  },
  bluePartyDress: {
    text: t('armorArmoireBluePartyDressText'),
    notes: t('armorArmoireBluePartyDressNotes', { attrs: 7 }),
    value: 100,
    con: 7,
    per: 7,
    str: 7,
    set: 'blueHairbow',
    canOwn: ownsItem('armor_armoire_bluePartyDress'),
    canBuy: () => true,
  },
  piraticalPrincessGown: {
    text: t('armorArmoirePiraticalPrincessGownText'),
    notes: t('armorArmoirePiraticalPrincessGownNotes', { per: 7 }),
    value: 100,
    per: 7,
    set: 'piraticalPrincess',
    canOwn: ownsItem('armor_armoire_piraticalPrincessGown'),
    canBuy: () => true,
  },
  jeweledArcherArmor: {
    text: t('armorArmoireJeweledArcherArmorText'),
    notes: t('armorArmoireJeweledArcherArmorNotes', { con: 15 }),
    value: 100,
    con: 15,
    set: 'jeweledArcher',
    canOwn: ownsItem('armor_armoire_jeweledArcherArmor'),
    canBuy: () => true,
  },
  coverallsOfBookbinding: {
    text: t('armorArmoireCoverallsOfBookbindingText'),
    notes: t('armorArmoireCoverallsOfBookbindingNotes', { con: 10, per: 5 }),
    value: 100,
    con: 10,
    per: 5,
    set: 'bookbinder',
    canOwn: ownsItem('armor_armoire_coverallsOfBookbinding'),
    canBuy: () => true,
  },
  robeOfSpades: {
    text: t('armorArmoireRobeOfSpadesText'),
    notes: t('armorArmoireRobeOfSpadesNotes', { str: 13 }),
    value: 100,
    str: 13,
    set: 'aceOfSpades',
    canOwn: ownsItem('armor_armoire_robeOfSpades'),
    canBuy: () => true,
  },
  softBlueSuit: {
    text: t('armorArmoireSoftBlueSuitText'),
    notes: t('armorArmoireSoftBlueSuitNotes', { int: 10, per: 5 }),
    value: 100,
    int: 10,
    per: 5,
    set: 'blueLoungewear',
    canOwn: ownsItem('armor_armoire_softBlueSuit'),
    canBuy: () => true,
  },
  softGreenSuit: {
    text: t('armorArmoireSoftGreenSuitText'),
    notes: t('armorArmoireSoftGreenSuitNotes', { attrs: 7 }),
    value: 100,
    int: 7,
    con: 7,
    set: 'greenLoungewear',
    canOwn: ownsItem('armor_armoire_softGreenSuit'),
    canBuy: () => true,
  },
  softRedSuit: {
    text: t('armorArmoireSoftRedSuitText'),
    notes: t('armorArmoireSoftRedSuitNotes', { int: 8, str: 5 }),
    value: 100,
    int: 8,
    str: 5,
    set: 'redLoungewear',
    canOwn: ownsItem('armor_armoire_softRedSuit'),
    canBuy: () => true,
  },
  scribesRobe: {
    text: t('armorArmoireScribesRobeText'),
    notes: t('armorArmoireScribesRobeNotes', { attrs: 7 }),
    value: 100,
    int: 7,
    per: 7,
    set: 'scribe',
    canOwn: ownsItem('armor_armoire_scribesRobe'),
    canBuy: () => true,
  },
  chefsJacket: {
    text: t('armorArmoireChefsJacketText'),
    notes: t('armorArmoireChefsJacketNotes', { int: 10 }),
    value: 100,
    int: 10,
    set: 'chef',
    canOwn: ownsItem('armor_armoire_chefsJacket'),
    canBuy: () => true,
  },
  vernalVestment: {
    text: t('armorArmoireVernalVestmentText'),
    notes: t('armorArmoireVernalVestmentNotes', { attrs: 6 }),
    value: 100,
    str: 6,
    int: 6,
    set: 'vernalVestments',
    canOwn: ownsItem('armor_armoire_vernalVestment'),
    canBuy: () => true,
  },
  nephriteArmor: {
    text: t('armorArmoireNephriteArmorText'),
    notes: t('armorArmoireNephriteArmorNotes', { str: 7, per: 6 }),
    value: 100,
    str: 7,
    per: 6,
    set: 'nephrite',
    canOwn: ownsItem('armor_armoire_nephriteArmor'),
    canBuy: () => true,
  },
  boatingJacket: {
    text: t('armorArmoireBoatingJacketText'),
    notes: t('armorArmoireBoatingJacketNotes', { attrs: 6 }),
    value: 100,
    int: 6,
    per: 6,
    str: 6,
    set: 'boating',
    canOwn: ownsItem('armor_armoire_boatingJacket'),
    canBuy: () => true,
  },
  astronomersRobe: {
    text: t('armorArmoireAstronomersRobeText'),
    notes: t('armorArmoireAstronomersRobeNotes', { attrs: 8 }),
    value: 100,
    per: 8,
    con: 8,
    set: 'astronomer',
    canOwn: ownsItem('armor_armoire_astronomersRobe'),
    canBuy: () => true,
  },
  invernessCape: {
    text: t('armorArmoireInvernessCapeText'),
    notes: t('armorArmoireInvernessCapeNotes', { attrs: 7 }),
    value: 100,
    per: 7,
    int: 7,
    set: 'detective',
    canOwn: ownsItem('armor_armoire_invernessCape'),
    canBuy: () => true,
  },
  shadowMastersRobe: {
    text: t('armorArmoireShadowMastersRobeText'),
    notes: t('armorArmoireShadowMastersRobeNotes', { con: 12 }),
    value: 100,
    con: 12,
    set: 'shadowMaster',
    canOwn: ownsItem('armor_armoire_shadowMastersRobe'),
    canBuy: () => true,
  },
  alchemistsRobe: {
    text: t('armorArmoireAlchemistsRobeText'),
    notes: t('armorArmoireAlchemistsRobeNotes', { con: 8, per: 5 }),
    value: 100,
    con: 8,
    per: 5,
    set: 'alchemist',
    canOwn: ownsItem('armor_armoire_alchemistsRobe'),
    canBuy: () => true,
  },
  duffleCoat: {
    text: t('armorArmoireDuffleCoatText'),
    notes: t('armorArmoireDuffleCoatNotes', { attrs: 7 }),
    value: 100,
    con: 7,
    per: 7,
    set: 'duffle',
    canOwn: ownsItem('armor_armoire_duffleCoat'),
    canBuy: () => true,
  },
  layerCakeArmor: {
    text: t('armorArmoireLayerCakeArmorText'),
    notes: t('armorArmoireLayerCakeArmorNotes', { con: 13 }),
    value: 100,
    con: 13,
    set: 'birthday',
    canOwn: ownsItem('armor_armoire_layerCakeArmor'),
    canBuy: () => true,
  },
  matchMakersApron: {
    text: t('armorArmoireMatchMakersApronText'),
    notes: t('armorArmoireMatchMakersApronNotes', { attrs: 7 }),
    value: 100,
    con: 7,
    str: 7,
    int: 7,
    set: 'matchMaker',
    canOwn: ownsItem('armor_armoire_matchMakersApron'),
    canBuy: () => true,
  },
  baseballUniform: {
    text: t('armorArmoireBaseballUniformText'),
    notes: t('armorArmoireBaseballUniformNotes', { attrs: 10 }),
    value: 100,
    con: 10,
    str: 10,
    set: 'baseball',
    canOwn: ownsItem('armor_armoire_baseballUniform'),
    canBuy: () => true,
  },
  boxArmor: {
    text: t('armorArmoireBoxArmorText'),
    notes: t('armorArmoireBoxArmorNotes', { attrs: 5 }),
    value: 100,
    per: 5,
    con: 5,
    set: 'paperKnight',
    canOwn: ownsItem('armor_armoire_boxArmor'),
    canBuy: () => true,
  },
  fiddlersCoat: {
    text: t('armorArmoireFiddlersCoatText'),
    notes: t('armorArmoireFiddlersCoatNotes', { con: 6 }),
    value: 100,
    con: 6,
    set: 'fiddler',
    canOwn: ownsItem('armor_armoire_fiddlersCoat'),
    canBuy: () => true,
  },
};

const body = {
  cozyScarf: {
    text: t('bodyArmoireCozyScarfText'),
    notes: t('bodyArmoireCozyScarfNotes', { attrs: 5 }),
    value: 100,
    con: 5,
    per: 5,
    set: 'lamplighter',
    canOwn: ownsItem('body_armoire_cozyScarf'),
    canBuy: () => true,
  },
};

const eyewear = {
  plagueDoctorMask: {
    text: t('eyewearArmoirePlagueDoctorMaskText'),
    notes: t('eyewearArmoirePlagueDoctorMaskNotes', { attrs: 5 }),
    con: 5,
    int: 5,
    value: 100,
    set: 'plagueDoctor',
    canOwn: ownsItem('eyewear_armoire_plagueDoctorMask'),
    canBuy: () => true,
  },
  goofyGlasses: {
    text: t('eyewearArmoireGoofyGlassesText'),
    notes: t('eyewearArmoireGoofyGlassesNotes', { per: 10 }),
    value: 100,
    per: 10,
    canOwn: ownsItem('eyewear_armoire_goofyGlasses'),
    canBuy: () => true,
  },
};

const head = {
  lunarCrown: {
    text: t('headArmoireLunarCrownText'),
    notes: t('headArmoireLunarCrownNotes', { con: 7, per: 7 }),
    value: 100,
    con: 7,
    per: 7,
    set: 'soothing',
    canOwn: ownsItem('head_armoire_lunarCrown'),
    canBuy: () => true,
  },
  redHairbow: {
    text: t('headArmoireRedHairbowText'),
    notes: t('headArmoireRedHairbowNotes', { str: 5, int: 5, con: 5 }),
    value: 100,
    str: 5,
    int: 5,
    con: 5,
    set: 'redHairbow',
    canOwn: ownsItem('head_armoire_redHairbow'),
    canBuy: () => true,
  },
  violetFloppyHat: {
    text: t('headArmoireVioletFloppyHatText'),
    notes: t('headArmoireVioletFloppyHatNotes', { per: 5, int: 5, con: 5 }),
    value: 100,
    per: 5,
    int: 5,
    con: 5,
    canOwn: ownsItem('head_armoire_violetFloppyHat'),
    canBuy: () => true,
  },
  gladiatorHelm: {
    text: t('headArmoireGladiatorHelmText'),
    notes: t('headArmoireGladiatorHelmNotes', { per: 7, int: 7 }),
    value: 100,
    per: 7,
    int: 7,
    set: 'gladiator',
    canOwn: ownsItem('head_armoire_gladiatorHelm'),
    canBuy: () => true,
  },
  rancherHat: {
    text: t('headArmoireRancherHatText'),
    notes: t('headArmoireRancherHatNotes', { str: 5, per: 5, int: 5 }),
    value: 100,
    str: 5,
    per: 5,
    int: 5,
    set: 'rancher',
    canOwn: ownsItem('head_armoire_rancherHat'),
    canBuy: () => true,
  },
  royalCrown: {
    text: t('headArmoireRoyalCrownText'),
    notes: t('headArmoireRoyalCrownNotes', { str: 10 }),
    value: 100,
    str: 10,
    set: 'royal',
    canOwn: ownsItem('head_armoire_royalCrown'),
    canBuy: () => true,
  },
  blueHairbow: {
    text: t('headArmoireBlueHairbowText'),
    notes: t('headArmoireBlueHairbowNotes', { per: 5, int: 5, con: 5 }),
    value: 100,
    per: 5,
    int: 5,
    con: 5,
    set: 'blueHairbow',
    canOwn: ownsItem('head_armoire_blueHairbow'),
    canBuy: () => true,
  },
  goldenLaurels: {
    text: t('headArmoireGoldenLaurelsText'),
    notes: t('headArmoireGoldenLaurelsNotes', { attrs: 8 }),
    value: 100,
    per: 8,
    con: 8,
    set: 'goldenToga',
    canOwn: ownsItem('head_armoire_goldenLaurels'),
    canBuy: () => true,
  },
  hornedIronHelm: {
    text: t('headArmoireHornedIronHelmText'),
    notes: t('headArmoireHornedIronHelmNotes', { con: 9, str: 7 }),
    value: 100,
    con: 9,
    str: 7,
    set: 'hornedIron',
    canOwn: ownsItem('head_armoire_hornedIronHelm'),
    canBuy: () => true,
  },
  yellowHairbow: {
    text: t('headArmoireYellowHairbowText'),
    notes: t('headArmoireYellowHairbowNotes', { attrs: 5 }),
    value: 100,
    int: 5,
    per: 5,
    str: 5,
    set: 'yellowHairbow',
    canOwn: ownsItem('head_armoire_yellowHairbow'),
    canBuy: () => true,
  },
  redFloppyHat: {
    text: t('headArmoireRedFloppyHatText'),
    notes: t('headArmoireRedFloppyHatNotes', { attrs: 6 }),
    value: 100,
    con: 6,
    int: 6,
    per: 6,
    canOwn: ownsItem('head_armoire_redFloppyHat'),
    set: 'redLoungewear',
    canBuy: () => true,
  },
  plagueDoctorHat: {
    text: t('headArmoirePlagueDoctorHatText'),
    notes: t('headArmoirePlagueDoctorHatNotes', { int: 5, str: 6, con: 5 }),
    value: 100,
    int: 5,
    str: 6,
    con: 5,
    set: 'plagueDoctor',
    canOwn: ownsItem('head_armoire_plagueDoctorHat'),
    canBuy: () => true,
  },
  blackCat: {
    text: t('headArmoireBlackCatText'),
    notes: t('headArmoireBlackCatNotes', { attrs: 9 }),
    value: 100,
    int: 9,
    per: 9,
    canOwn: ownsItem('head_armoire_blackCat'),
    canBuy: () => true,
  },
  orangeCat: {
    text: t('headArmoireOrangeCatText'),
    notes: t('headArmoireOrangeCatNotes', { attrs: 9 }),
    value: 100,
    con: 9,
    str: 9,
    canOwn: ownsItem('head_armoire_orangeCat'),
    canBuy: () => true,
  },
  blueFloppyHat: {
    text: t('headArmoireBlueFloppyHatText'),
    notes: t('headArmoireBlueFloppyHatNotes', { attrs: 7 }),
    value: 100,
    per: 7,
    int: 7,
    con: 7,
    set: 'blueLoungewear',
    canOwn: ownsItem('head_armoire_blueFloppyHat'),
    canBuy: () => true,
  },
  shepherdHeaddress: {
    text: t('headArmoireShepherdHeaddressText'),
    notes: t('headArmoireShepherdHeaddressNotes', { int: 9 }),
    value: 100,
    int: 9,
    set: 'shepherd',
    canOwn: ownsItem('head_armoire_shepherdHeaddress'),
    canBuy: () => true,
  },
  crystalCrescentHat: {
    text: t('headArmoireCrystalCrescentHatText'),
    notes: t('headArmoireCrystalCrescentHatNotes', { attrs: 7 }),
    value: 100,
    int: 7,
    per: 7,
    set: 'crystalCrescent',
    canOwn: ownsItem('head_armoire_crystalCrescentHat'),
    canBuy: () => true,
  },
  dragonTamerHelm: {
    text: t('headArmoireDragonTamerHelmText'),
    notes: t('headArmoireDragonTamerHelmNotes', { int: 15 }),
    value: 100,
    int: 15,
    set: 'dragonTamer',
    canOwn: ownsItem('head_armoire_dragonTamerHelm'),
    canBuy: () => true,
  },
  barristerWig: {
    text: t('headArmoireBarristerWigText'),
    notes: t('headArmoireBarristerWigNotes', { str: 10 }),
    value: 100,
    str: 10,
    set: 'barrister',
    canOwn: ownsItem('head_armoire_barristerWig'),
    canBuy: () => true,
  },
  jesterCap: {
    text: t('headArmoireJesterCapText'),
    notes: t('headArmoireJesterCapNotes', { per: 15 }),
    value: 100,
    per: 15,
    set: 'jester',
    canOwn: ownsItem('head_armoire_jesterCap'),
    canBuy: () => true,
  },
  minerHelmet: {
    text: t('headArmoireMinerHelmetText'),
    notes: t('headArmoireMinerHelmetNotes', { int: 5 }),
    value: 100,
    int: 5,
    set: 'miner',
    canOwn: ownsItem('head_armoire_minerHelmet'),
    canBuy: () => true,
  },
  basicArcherCap: {
    text: t('headArmoireBasicArcherCapText'),
    notes: t('headArmoireBasicArcherCapNotes', { per: 6 }),
    value: 100,
    per: 6,
    set: 'basicArcher',
    canOwn: ownsItem('head_armoire_basicArcherCap'),
    canBuy: () => true,
  },
  graduateCap: {
    text: t('headArmoireGraduateCapText'),
    notes: t('headArmoireGraduateCapNotes', { int: 9 }),
    value: 100,
    int: 9,
    set: 'graduate',
    canOwn: ownsItem('head_armoire_graduateCap'),
    canBuy: () => true,
  },
  greenFloppyHat: {
    text: t('headArmoireGreenFloppyHatText'),
    notes: t('headArmoireGreenFloppyHatNotes', { attrs: 8 }),
    value: 100,
    per: 8,
    int: 8,
    con: 8,
    canOwn: ownsItem('head_armoire_greenFloppyHat'),
    set: 'greenLoungewear',
    canBuy: () => true,
  },
  cannoneerBandanna: {
    text: t('headArmoireCannoneerBandannaText'),
    notes: t('headArmoireCannoneerBandannaNotes', { attrs: 15 }),
    value: 100,
    int: 15,
    per: 15,
    set: 'cannoneer',
    canOwn: ownsItem('head_armoire_cannoneerBandanna'),
    canBuy: () => true,
  },
  falconerCap: {
    text: t('headArmoireFalconerCapText'),
    notes: t('headArmoireFalconerCapNotes', { int: 10 }),
    value: 100,
    int: 10,
    set: 'falconer',
    canOwn: ownsItem('head_armoire_falconerCap'),
    canBuy: () => true,
  },
  vermilionArcherHelm: {
    text: t('headArmoireVermilionArcherHelmText'),
    notes: t('headArmoireVermilionArcherHelmNotes', { per: 12 }),
    value: 100,
    per: 12,
    set: 'vermilionArcher',
    canOwn: ownsItem('head_armoire_vermilionArcherHelm'),
    canBuy: () => true,
  },
  ogreMask: {
    text: t('headArmoireOgreMaskText'),
    notes: t('headArmoireOgreMaskNotes', { attrs: 7 }),
    value: 100,
    con: 7,
    str: 7,
    set: 'ogre',
    canOwn: ownsItem('head_armoire_ogreMask'),
    canBuy: () => true,
  },
  ironBlueArcherHelm: {
    text: t('headArmoireIronBlueArcherHelmText'),
    notes: t('headArmoireIronBlueArcherHelmNotes', { con: 9 }),
    value: 100,
    con: 9,
    set: 'blueArcher',
    canOwn: ownsItem('head_armoire_ironBlueArcherHelm'),
    canBuy: () => true,
  },
  woodElfHelm: {
    text: t('headArmoireWoodElfHelmText'),
    notes: t('headArmoireWoodElfHelmNotes', { con: 12 }),
    value: 100,
    con: 12,
    set: 'woodElf',
    canOwn: ownsItem('head_armoire_woodElfHelm'),
    canBuy: () => true,
  },
  ramHeaddress: {
    text: t('headArmoireRamHeaddressText'),
    notes: t('headArmoireRamHeaddressNotes', { con: 9, per: 7 }),
    value: 100,
    con: 9,
    per: 7,
    set: 'ramBarbarian',
    canOwn: ownsItem('head_armoire_ramHeaddress'),
    canBuy: () => true,
  },
  crownOfHearts: {
    text: t('headArmoireCrownOfHeartsText'),
    notes: t('headArmoireCrownOfHeartsNotes', { str: 13 }),
    value: 100,
    str: 13,
    set: 'queenOfHearts',
    canOwn: ownsItem('head_armoire_crownOfHearts'),
    canBuy: () => true,
  },
  mushroomDruidCap: {
    text: t('headArmoireMushroomDruidCapText'),
    notes: t('headArmoireMushroomDruidCapNotes', { int: 6, str: 7 }),
    value: 100,
    int: 6,
    str: 7,
    set: 'mushroomDruid',
    canOwn: ownsItem('head_armoire_mushroomDruidCap'),
    canBuy: () => true,
  },
  merchantChaperon: {
    text: t('headArmoireMerchantChaperonText'),
    notes: t('headArmoireMerchantChaperonNotes', { attrs: 7 }),
    value: 100,
    int: 7,
    per: 7,
    set: 'merchant',
    canOwn: ownsItem('head_armoire_merchantChaperon'),
    canBuy: () => true,
  },
  vikingHelm: {
    text: t('headArmoireVikingHelmText'),
    notes: t('headArmoireVikingHelmNotes', { str: 6, per: 8 }),
    value: 100,
    str: 6,
    per: 8,
    set: 'viking',
    canOwn: ownsItem('head_armoire_vikingHelm'),
    canBuy: () => true,
  },
  swanFeatherCrown: {
    text: t('headArmoireSwanFeatherCrownText'),
    notes: t('headArmoireSwanFeatherCrownNotes', { int: 8 }),
    value: 100,
    int: 8,
    set: 'swanDancer',
    canOwn: ownsItem('head_armoire_swanFeatherCrown'),
    canBuy: () => true,
  },
  antiProcrastinationHelm: {
    text: t('headArmoireAntiProcrastinationHelmText'),
    notes: t('headArmoireAntiProcrastinationHelmNotes', { per: 15 }),
    value: 100,
    per: 15,
    set: 'antiProcrastination',
    canOwn: ownsItem('head_armoire_antiProcrastinationHelm'),
    canBuy: () => true,
  },
  candlestickMakerHat: {
    text: t('headArmoireCandlestickMakerHatText'),
    notes: t('headArmoireCandlestickMakerHatNotes', { attrs: 6 }),
    value: 100,
    int: 6,
    per: 6,
    set: 'candlestickMaker',
    canOwn: ownsItem('head_armoire_candlestickMakerHat'),
    canBuy: () => true,
  },
  lamplightersTopHat: {
    text: t('headArmoireLamplightersTopHatText'),
    notes: t('headArmoireLamplightersTopHatNotes', { con: 14 }),
    value: 100,
    con: 14,
    set: 'lamplighter',
    canOwn: ownsItem('head_armoire_lamplightersTopHat'),
    canBuy: () => true,
  },
  coachDriversHat: {
    text: t('headArmoireCoachDriversHatText'),
    notes: t('headArmoireCoachDriversHatNotes', { int: 12 }),
    value: 100,
    int: 12,
    set: 'coachDriver',
    canOwn: ownsItem('head_armoire_coachDriversHat'),
    canBuy: () => true,
  },
  crownOfDiamonds: {
    text: t('headArmoireCrownOfDiamondsText'),
    notes: t('headArmoireCrownOfDiamondsNotes', { int: 13 }),
    value: 100,
    int: 13,
    set: 'kingOfDiamonds',
    canOwn: ownsItem('head_armoire_crownOfDiamonds'),
    canBuy: () => true,
  },
  flutteryWig: {
    text: t('headArmoireFlutteryWigText'),
    notes: t('headArmoireFlutteryWigNotes', { attrs: 5 }),
    value: 100,
    int: 5,
    per: 5,
    str: 5,
    set: 'fluttery',
    canOwn: ownsItem('head_armoire_flutteryWig'),
    canBuy: () => true,
  },
  bigWig: {
    text: t('headArmoireBigWigText'),
    notes: t('headArmoireBigWigNotes', { str: 10 }),
    value: 100,
    str: 10,
    canOwn: ownsItem('head_armoire_bigWig'),
    canBuy: () => true,
  },
  paperBag: {
    text: t('headArmoirePaperBagText'),
    notes: t('headArmoirePaperBagNotes', { con: 10 }),
    value: 100,
    con: 10,
    canOwn: ownsItem('head_armoire_paperBag'),
    canBuy: () => true,
  },
  birdsNest: {
    text: t('headArmoireBirdsNestText'),
    notes: t('headArmoireBirdsNestNotes', { int: 10 }),
    value: 100,
    int: 10,
    canOwn: ownsItem('head_armoire_birdsNest'),
    canBuy: () => true,
  },
  glassblowersHat: {
    text: t('headArmoireGlassblowersHatText'),
    notes: t('headArmoireGlassblowersHatNotes', { per: 8 }),
    value: 100,
    per: 8,
    set: 'glassblower',
    canOwn: ownsItem('head_armoire_glassblowersHat'),
    canBuy: () => true,
  },
  piraticalPrincessHeaddress: {
    text: t('headArmoirePiraticalPrincessHeaddressText'),
    notes: t('headArmoirePiraticalPrincessHeaddressNotes', { attrs: 8 }),
    value: 100,
    per: 8,
    int: 8,
    set: 'piraticalPrincess',
    canOwn: ownsItem('head_armoire_piraticalPrincessHeaddress'),
    canBuy: () => true,
  },
  jeweledArcherHelm: {
    text: t('headArmoireJeweledArcherHelmText'),
    notes: t('headArmoireJeweledArcherHelmNotes', { int: 15 }),
    value: 100,
    int: 15,
    set: 'jeweledArcher',
    canOwn: ownsItem('head_armoire_jeweledArcherHelm'),
    canBuy: () => true,
  },
  veilOfSpades: {
    text: t('headArmoireVeilOfSpadesText'),
    notes: t('headArmoireVeilOfSpadesNotes', { per: 13 }),
    value: 100,
    per: 13,
    set: 'aceOfSpades',
    canOwn: ownsItem('head_armoire_veilOfSpades'),
    canBuy: () => true,
  },
  toqueBlanche: {
    text: t('headArmoireToqueBlancheText'),
    notes: t('headArmoireToqueBlancheNotes', { per: 10 }),
    value: 100,
    per: 10,
    set: 'chef',
    canOwn: ownsItem('head_armoire_toqueBlanche'),
    canBuy: () => true,
  },
  vernalHennin: {
    text: t('headArmoireVernalHenninText'),
    notes: t('headArmoireVernalHenninNotes', { per: 12 }),
    value: 100,
    per: 12,
    set: 'vernalVestments',
    canOwn: ownsItem('head_armoire_vernalHennin'),
    canBuy: () => true,
  },
  tricornHat: {
    text: t('headArmoireTricornHatText'),
    notes: t('headArmoireTricornHatNotes', { per: 10 }),
    value: 100,
    per: 10,
    canOwn: ownsItem('head_armoire_tricornHat'),
    canBuy: () => true,
  },
  nephriteHelm: {
    text: t('headArmoireNephriteHelmText'),
    notes: t('headArmoireNephriteHelmNotes', { per: 7, int: 6 }),
    value: 100,
    per: 7,
    int: 6,
    set: 'nephrite',
    canOwn: ownsItem('head_armoire_nephriteHelm'),
    canBuy: () => true,
  },
  boaterHat: {
    text: t('headArmoireBoaterHatText'),
    notes: t('headArmoireBoaterHatNotes', { attrs: 6 }),
    value: 100,
    str: 6,
    con: 6,
    per: 6,
    set: 'boating',
    canOwn: ownsItem('head_armoire_boaterHat'),
    canBuy: () => true,
  },
  astronomersHat: {
    text: t('headArmoireAstronomersHatText'),
    notes: t('headArmoireAstronomersHatNotes', { con: 10 }),
    value: 100,
    con: 10,
    set: 'astronomer',
    canOwn: ownsItem('head_armoire_astronomersHat'),
    canBuy: () => true,
  },
  deerstalkerCap: {
    text: t('headArmoireDeerstalkerCapText'),
    notes: t('headArmoireDeerstalkerCapNotes', { int: 14 }),
    value: 100,
    int: 14,
    set: 'detective',
    canOwn: ownsItem('head_armoire_deerstalkerCap'),
    canBuy: () => true,
  },
  shadowMastersHood: {
    text: t('headArmoireShadowMastersHoodText'),
    notes: t('headArmoireShadowMastersHoodNotes', { attrs: 5 }),
    value: 100,
    per: 5,
    con: 5,
    set: 'shadowMaster',
    canOwn: ownsItem('head_armoire_shadowMastersHood'),
    canBuy: () => true,
  },
  alchemistsHat: {
    text: t('headArmoireAlchemistsHatText'),
    notes: t('headArmoireAlchemistsHatNotes', { per: 7 }),
    value: 100,
    per: 7,
    set: 'alchemist',
    canOwn: ownsItem('head_armoire_alchemistsHat'),
    canBuy: () => true,
  },
  earflapHat: {
    text: t('headArmoireEarflapHatText'),
    notes: t('headArmoireEarflapHatNotes', { attrs: 7 }),
    value: 100,
    int: 7,
    str: 7,
    set: 'duffle',
    canOwn: ownsItem('head_armoire_earflapHat'),
    canBuy: () => true,
  },
  frostedHelm: {
    text: t('headArmoireFrostedHelmText'),
    notes: t('headArmoireFrostedHelmNotes', { int: 13 }),
    value: 100,
    int: 13,
    set: 'birthday',
    canOwn: ownsItem('head_armoire_frostedHelm'),
    canBuy: () => true,
  },
  matchMakersBeret: {
    text: t('headArmoireMatchMakersBeretText'),
    notes: t('headArmoireMatchMakersBeretNotes', { con: 15 }),
    value: 100,
    con: 15,
    set: 'matchMaker',
    canOwn: ownsItem('head_armoire_matchMakersBeret'),
    canBuy: () => true,
  },
  baseballCap: {
    text: t('headArmoireBaseballCapText'),
    notes: t('headArmoireBaseballCapNotes', { attrs: 8 }),
    value: 100,
    con: 8,
    str: 8,
    set: 'baseball',
    canOwn: ownsItem('head_armoire_baseballCap'),
    canBuy: () => true,
  },
  fiddlersCap: {
    text: t('headArmoireFiddlersCapText'),
    notes: t('headArmoireFiddlersCapNotes', { per: 6 }),
    value: 100,
    per: 6,
    set: 'fiddler',
    canOwn: ownsItem('head_armoire_fiddlersCap'),
    canBuy: () => true,
  },
};

const shield = {
  gladiatorShield: {
    text: t('shieldArmoireGladiatorShieldText'),
    notes: t('shieldArmoireGladiatorShieldNotes', { con: 5, str: 5 }),
    value: 100,
    con: 5,
    str: 5,
    set: 'gladiator',
    canOwn: ownsItem('shield_armoire_gladiatorShield'),
    canBuy: () => true,
  },
  midnightShield: {
    text: t('shieldArmoireMidnightShieldText'),
    notes: t('shieldArmoireMidnightShieldNotes', { con: 10, str: 2 }),
    value: 100,
    con: 10,
    str: 2,
    canOwn: ownsItem('shield_armoire_midnightShield'),
    canBuy: () => true,
  },
  royalCane: {
    text: t('shieldArmoireRoyalCaneText'),
    notes: t('shieldArmoireRoyalCaneNotes', { attrs: 5 }),
    value: 100,
    con: 5,
    int: 5,
    per: 5,
    set: 'royal',
    canOwn: ownsItem('shield_armoire_royalCane'),
    canBuy: () => true,
  },
  dragonTamerShield: {
    text: t('shieldArmoireDragonTamerShieldText'),
    notes: t('shieldArmoireDragonTamerShieldNotes', { per: 15 }),
    value: 100,
    per: 15,
    set: 'dragonTamer',
    canOwn: ownsItem('shield_armoire_dragonTamerShield'),
    canBuy: () => true,
  },
  mysticLamp: {
    text: t('shieldArmoireMysticLampText'),
    notes: t('shieldArmoireMysticLampNotes', { per: 15 }),
    value: 100,
    per: 15,
    canOwn: ownsItem('shield_armoire_mysticLamp'),
    canBuy: () => true,
  },
  floralBouquet: {
    text: t('shieldArmoireFloralBouquetText'),
    notes: t('shieldArmoireFloralBouquetNotes', { con: 3 }),
    value: 100,
    con: 3,
    canOwn: ownsItem('shield_armoire_floralBouquet'),
    canBuy: () => true,
  },
  sandyBucket: {
    text: t('shieldArmoireSandyBucketText'),
    notes: t('shieldArmoireSandyBucketNotes', { per: 10 }),
    value: 100,
    per: 10,
    set: 'seaside',
    canOwn: ownsItem('shield_armoire_sandyBucket'),
    canBuy: () => true,
  },
  perchingFalcon: {
    text: t('shieldArmoirePerchingFalconText'),
    notes: t('shieldArmoirePerchingFalconNotes', { str: 16 }),
    value: 100,
    str: 16,
    set: 'falconer',
    canOwn: ownsItem('shield_armoire_perchingFalcon'),
    canBuy: () => true,
  },
  ramHornShield: {
    text: t('shieldArmoireRamHornShieldText'),
    notes: t('shieldArmoireRamHornShieldNotes', { attrs: 7 }),
    value: 100,
    str: 7,
    con: 7,
    set: 'ramBarbarian',
    canOwn: ownsItem('shield_armoire_ramHornShield'),
    canBuy: () => true,
  },
  redRose: {
    text: t('shieldArmoireRedRoseText'),
    notes: t('shieldArmoireRedRoseNotes', { per: 10 }),
    value: 100,
    per: 10,
    canOwn: ownsItem('shield_armoire_redRose'),
    canBuy: () => true,
  },
  mushroomDruidShield: {
    text: t('shieldArmoireMushroomDruidShieldText'),
    notes: t('shieldArmoireMushroomDruidShieldNotes', { con: 9, str: 8 }),
    value: 100,
    con: 9,
    str: 8,
    set: 'mushroomDruid',
    canOwn: ownsItem('shield_armoire_mushroomDruidShield'),
    canBuy: () => true,
  },
  festivalParasol: {
    text: t('shieldArmoireFestivalParasolText'),
    notes: t('shieldArmoireFestivalParasolNotes', { con: 8 }),
    value: 100,
    con: 8,
    set: 'festivalAttire',
    canOwn: ownsItem('shield_armoire_festivalParasol'),
    canBuy: () => true,
  },
  vikingShield: {
    text: t('shieldArmoireVikingShieldText'),
    notes: t('shieldArmoireVikingShieldNotes', { per: 6, int: 8 }),
    value: 100,
    per: 6,
    int: 8,
    set: 'viking',
    canOwn: ownsItem('shield_armoire_vikingShield'),
    canBuy: () => true,
  },
  swanFeatherFan: {
    text: t('shieldArmoireSwanFeatherFanText'),
    notes: t('shieldArmoireSwanFeatherFanNotes', { str: 8 }),
    value: 100,
    str: 8,
    set: 'swanDancer',
    canOwn: ownsItem('shield_armoire_swanFeatherFan'),
    canBuy: () => true,
  },
  goldenBaton: {
    text: t('shieldArmoireGoldenBatonText'),
    notes: t('shieldArmoireGoldenBatonNotes', { attrs: 4 }),
    value: 100,
    int: 4,
    str: 4,
    canOwn: ownsItem('shield_armoire_goldenBaton'),
    canBuy: () => true,
  },
  antiProcrastinationShield: {
    text: t('shieldArmoireAntiProcrastinationShieldText'),
    notes: t('shieldArmoireAntiProcrastinationShieldNotes', { con: 15 }),
    value: 100,
    con: 15,
    set: 'antiProcrastination',
    canOwn: ownsItem('shield_armoire_antiProcrastinationShield'),
    canBuy: () => true,
  },
  horseshoe: {
    text: t('shieldArmoireHorseshoeText'),
    notes: t('shieldArmoireHorseshoeNotes', { attrs: 6 }),
    value: 100,
    con: 6,
    per: 6,
    str: 6,
    set: 'farrier',
    canOwn: ownsItem('shield_armoire_horseshoe'),
    canBuy: () => true,
  },
  handmadeCandlestick: {
    text: t('shieldArmoireHandmadeCandlestickText'),
    notes: t('shieldArmoireHandmadeCandlestickNotes', { str: 12 }),
    value: 100,
    str: 12,
    set: 'candlestickMaker',
    canOwn: ownsItem('shield_armoire_handmadeCandlestick'),
    canBuy: () => true,
  },
  weaversShuttle: {
    text: t('shieldArmoireWeaversShuttleText'),
    notes: t('shieldArmoireWeaversShuttleNotes', { int: 8, per: 9 }),
    value: 100,
    per: 9,
    int: 8,
    set: 'weaver',
    canOwn: ownsItem('shield_armoire_weaversShuttle'),
    canBuy: () => true,
  },
  shieldOfDiamonds: {
    text: t('shieldArmoireShieldOfDiamondsText'),
    notes: t('shieldArmoireShieldOfDiamondsNotes', { con: 10 }),
    value: 100,
    con: 10,
    set: 'kingOfDiamonds',
    canOwn: ownsItem('shield_armoire_shieldOfDiamonds'),
    canBuy: () => true,
  },
  flutteryFan: {
    text: t('shieldArmoireFlutteryFanText'),
    notes: t('shieldArmoireFlutteryFanNotes', { attrs: 5 }),
    value: 100,
    con: 5,
    int: 5,
    per: 5,
    set: 'fluttery',
    canOwn: ownsItem('shield_armoire_flutteryFan'),
    canBuy: () => true,
  },
  fancyShoe: {
    text: t('shieldArmoireFancyShoeText'),
    notes: t('shieldArmoireFancyShoeNotes', { attrs: 7 }),
    value: 100,
    int: 7,
    per: 7,
    set: 'cobbler',
    canOwn: ownsItem('shield_armoire_fancyShoe'),
    canBuy: () => true,
  },
  fancyBlownGlassVase: {
    text: t('shieldArmoireFancyBlownGlassVaseText'),
    notes: t('shieldArmoireFancyBlownGlassVaseNotes', { int: 6 }),
    value: 100,
    int: 6,
    set: 'glassblower',
    canOwn: ownsItem('shield_armoire_fancyBlownGlassVase'),
    canBuy: () => true,
  },
  piraticalSkullShield: {
    text: t('shieldArmoirePiraticalSkullShieldText'),
    notes: t('shieldArmoirePiraticalSkullShieldNotes', { attrs: 4 }),
    value: 100,
    per: 4,
    int: 4,
    set: 'piraticalPrincess',
    canOwn: ownsItem('shield_armoire_piraticalSkullShield'),
    canBuy: () => true,
  },
  unfinishedTome: {
    text: t('shieldArmoireUnfinishedTomeText'),
    notes: t('shieldArmoireUnfinishedTomeNotes', { int: 10 }),
    value: 100,
    int: 10,
    set: 'bookbinder',
    canOwn: ownsItem('shield_armoire_unfinishedTome'),
    canBuy: () => true,
  },
  softBluePillow: {
    text: t('shieldArmoireSoftBluePillowText'),
    notes: t('shieldArmoireSoftBluePillowNotes', { con: 10 }),
    value: 100,
    con: 10,
    set: 'blueLoungewear',
    canOwn: ownsItem('shield_armoire_softBluePillow'),
    canBuy: () => true,
  },
  softGreenPillow: {
    text: t('shieldArmoireSoftGreenPillowText'),
    notes: t('shieldArmoireSoftGreenPillowNotes', { con: 8, int: 6 }),
    value: 100,
    con: 8,
    int: 6,
    set: 'greenLoungewear',
    canOwn: ownsItem('shield_armoire_softGreenPillow'),
    canBuy: () => true,
  },
  softRedPillow: {
    text: t('shieldArmoireSoftRedPillowText'),
    notes: t('shieldArmoireSoftRedPillowNotes', { attrs: 5 }),
    value: 100,
    con: 5,
    str: 5,
    set: 'redLoungewear',
    canOwn: ownsItem('shield_armoire_softRedPillow'),
    canBuy: () => true,
  },
  mightyQuill: {
    text: t('shieldArmoireMightyQuillText'),
    notes: t('shieldArmoireMightyQuillNotes', { per: 9 }),
    value: 100,
    per: 9,
    set: 'scribe',
    canOwn: ownsItem('shield_armoire_mightyQuill'),
    canBuy: () => true,
  },
  mightyPizza: {
    text: t('shieldArmoireMightyPizzaText'),
    notes: t('shieldArmoireMightyPizzaNotes', { per: 8 }),
    value: 100,
    per: 8,
    set: 'chef',
    canOwn: ownsItem('shield_armoire_mightyPizza'),
    canBuy: () => true,
  },
  trustyUmbrella: {
    text: t('shieldArmoireTrustyUmbrellaText'),
    notes: t('shieldArmoireTrustyUmbrellaNotes', { int: 7 }),
    value: 100,
    int: 7,
    set: 'detective',
    canOwn: ownsItem('shield_armoire_trustyUmbrella'),
    canBuy: () => true,
  },
  polishedPocketwatch: {
    text: t('shieldArmoirePolishedPocketwatchText'),
    notes: t('shieldArmoirePolishedPocketwatchNotes', { int: 9 }),
    value: 100,
    int: 9,
    canOwn: ownsItem('shield_armoire_polishedPocketwatch'),
    canBuy: () => true,
  },
  masteredShadow: {
    text: t('shieldArmoireMasteredShadowText'),
    notes: t('shieldArmoireMasteredShadowNotes', { attrs: 5 }),
    value: 100,
    per: 5,
    con: 5,
    set: 'shadowMaster',
    canOwn: ownsItem('shield_armoire_masteredShadow'),
    canBuy: () => true,
  },
  alchemistsScale: {
    text: t('shieldArmoireAlchemistsScaleText'),
    notes: t('shieldArmoireAlchemistsScaleNotes', { int: 7 }),
    value: 100,
    int: 7,
    set: 'alchemist',
    canOwn: ownsItem('shield_armoire_alchemistsScale'),
    canBuy: () => true,
  },
  birthdayBanner: {
    text: t('shieldArmoireBirthdayBannerText'),
    notes: t('shieldArmoireBirthdayBannerNotes', { str: 7 }),
    value: 100,
    str: 7,
    set: 'birthday',
    canOwn: ownsItem('shield_armoire_birthdayBanner'),
    canBuy: () => true,
  },
  perfectMatch: {
    text: t('shieldArmoirePerfectMatchText'),
    notes: t('shieldArmoirePerfectMatchNotes', { per: 15 }),
    value: 100,
    per: 15,
    set: 'matchMaker',
    canOwn: ownsItem('shield_armoire_perfectMatch'),
    canBuy: () => true,
  },
  baseballGlove: {
    text: t('shieldArmoireBaseballGloveText'),
    notes: t('shieldArmoireBaseballGloveNotes', { str: 9 }),
    value: 100,
    str: 9,
    set: 'baseball',
    canOwn: ownsItem('shield_armoire_baseballGlove'),
    canBuy: () => true,
  },
  hobbyHorse: {
    text: t('shieldArmoireHobbyHorseText'),
    notes: t('shieldArmoireHobbyHorseNotes', { attrs: 4 }),
    value: 100,
    per: 4,
    con: 4,
    set: 'paperKnight',
    canOwn: ownsItem('shield_armoire_hobbyHorse'),
    canBuy: () => true,
  },
  fiddle: {
    text: t('shieldArmoireFiddleText'),
    notes: t('shieldArmoireFiddleNotes', { int: 6 }),
    value: 100,
    int: 6,
    set: 'fiddler',
    canOwn: ownsItem('shield_armoire_fiddle'),
    canBuy: () => true,
  },
};

const headAccessory = {
  comicalArrow: {
    text: t('headAccessoryArmoireComicalArrowText'),
    notes: t('headAccessoryArmoireComicalArrowNotes', { str: 10 }),
    value: 100,
    str: 10,
    canOwn: ownsItem('headAccessory_armoire_comicalArrow'),
    canBuy: () => true,
  },
  gogglesOfBookbinding: {
    text: t('headAccessoryArmoireGogglesOfBookbindingText'),
    notes: t('headAccessoryArmoireGogglesOfBookbindingNotes', { per: 8 }),
    value: 100,
    per: 8,
    set: 'bookbinder',
    canOwn: ownsItem('headAccessory_armoire_gogglesOfBookbinding'),
    canBuy: () => true,
  },
};

const weapon = {
  basicCrossbow: {
    text: t('weaponArmoireBasicCrossbowText'),
    notes: t('weaponArmoireBasicCrossbowNotes', { str: 5, per: 5, con: 5 }),
    value: 100,
    str: 5,
    per: 5,
    con: 5,
    canOwn: ownsItem('weapon_armoire_basicCrossbow'),
    canBuy: () => true,
  },
  lunarSceptre: {
    text: t('weaponArmoireLunarSceptreText'),
    notes: t('weaponArmoireLunarSceptreNotes', { con: 7, int: 7 }),
    value: 100,
    con: 7,
    int: 7,
    set: 'soothing',
    canOwn: ownsItem('weapon_armoire_lunarSceptre'),
    canBuy: () => true,
  },
  rancherLasso: {
    twoHanded: true,
    text: t('weaponArmoireRancherLassoText'),
    notes: t('weaponArmoireRancherLassoNotes', { str: 5, per: 5, int: 5 }),
    value: 100,
    str: 5,
    per: 5,
    int: 5,
    set: 'rancher',
    canOwn: ownsItem('weapon_armoire_rancherLasso'),
    canBuy: () => true,
  },
  mythmakerSword: {
    text: t('weaponArmoireMythmakerSwordText'),
    notes: t('weaponArmoireMythmakerSwordNotes', { attrs: 6 }),
    value: 100,
    str: 6,
    per: 6,
    set: 'goldenToga',
    canOwn: ownsItem('weapon_armoire_mythmakerSword'),
    canBuy: () => true,
  },
  ironCrook: {
    text: t('weaponArmoireIronCrookText'),
    notes: t('weaponArmoireIronCrookNotes', { attrs: 7 }),
    value: 100,
    str: 7,
    per: 7,
    set: 'hornedIron',
    canOwn: ownsItem('weapon_armoire_ironCrook'),
    canBuy: () => true,
  },
  goldWingStaff: {
    text: t('weaponArmoireGoldWingStaffText'),
    notes: t('weaponArmoireGoldWingStaffNotes', { attrs: 4 }),
    value: 100,
    con: 4,
    int: 4,
    per: 4,
    str: 4,
    canOwn: ownsItem('weapon_armoire_goldWingStaff'),
    canBuy: () => true,
  },
  batWand: {
    text: t('weaponArmoireBatWandText'),
    notes: t('weaponArmoireBatWandNotes', { int: 10, per: 2 }),
    value: 100,
    int: 10,
    per: 2,
    canOwn: ownsItem('weapon_armoire_batWand'),
    canBuy: () => true,
  },
  shepherdsCrook: {
    text: t('weaponArmoireShepherdsCrookText'),
    notes: t('weaponArmoireShepherdsCrookNotes', { con: 9 }),
    value: 100,
    con: 9,
    set: 'shepherd',
    canOwn: ownsItem('weapon_armoire_shepherdsCrook'),
    canBuy: () => true,
  },
  crystalCrescentStaff: {
    text: t('weaponArmoireCrystalCrescentStaffText'),
    notes: t('weaponArmoireCrystalCrescentStaffNotes', { attrs: 7 }),
    value: 100,
    int: 7,
    str: 7,
    set: 'crystalCrescent',
    canOwn: ownsItem('weapon_armoire_crystalCrescentStaff'),
    canBuy: () => true,
  },
  blueLongbow: {
    text: t('weaponArmoireBlueLongbowText'),
    notes: t('weaponArmoireBlueLongbowNotes', { per: 9, con: 8, str: 7 }),
    value: 100,
    per: 9,
    con: 8,
    str: 7,
    twoHanded: true,
    set: 'blueArcher',
    canOwn: ownsItem('weapon_armoire_blueLongbow'),
    canBuy: () => true,
  },
  glowingSpear: {
    text: t('weaponArmoireGlowingSpearText'),
    notes: t('weaponArmoireGlowingSpearNotes', { str: 15 }),
    value: 100,
    str: 15,
    canOwn: ownsItem('weapon_armoire_glowingSpear'),
    canBuy: () => true,
  },
  barristerGavel: {
    text: t('weaponArmoireBarristerGavelText'),
    notes: t('weaponArmoireBarristerGavelNotes', { attrs: 5 }),
    value: 100,
    str: 5,
    con: 5,
    set: 'barrister',
    canOwn: ownsItem('weapon_armoire_barristerGavel'),
    canBuy: () => true,
  },
  jesterBaton: {
    text: t('weaponArmoireJesterBatonText'),
    notes: t('weaponArmoireJesterBatonNotes', { attrs: 8 }),
    value: 100,
    int: 8,
    per: 8,
    set: 'jester',
    canOwn: ownsItem('weapon_armoire_jesterBaton'),
    canBuy: () => true,
  },
  miningPickax: {
    text: t('weaponArmoireMiningPickaxText'),
    notes: t('weaponArmoireMiningPickaxNotes', { per: 15 }),
    value: 100,
    per: 15,
    set: 'miner',
    canOwn: ownsItem('weapon_armoire_miningPickax'),
    canBuy: () => true,
  },
  basicLongbow: {
    text: t('weaponArmoireBasicLongbowText'),
    notes: t('weaponArmoireBasicLongbowNotes', { str: 6 }),
    value: 100,
    str: 6,
    twoHanded: true,
    set: 'basicArcher',
    canOwn: ownsItem('weapon_armoire_basicLongbow'),
    canBuy: () => true,
  },
  habiticanDiploma: {
    text: t('weaponArmoireHabiticanDiplomaText'),
    notes: t('weaponArmoireHabiticanDiplomaNotes', { int: 11 }),
    value: 100,
    int: 11,
    set: 'graduate',
    canOwn: ownsItem('weapon_armoire_habiticanDiploma'),
    canBuy: () => true,
  },
  sandySpade: {
    text: t('weaponArmoireSandySpadeText'),
    notes: t('weaponArmoireSandySpadeNotes', { str: 10 }),
    value: 100,
    str: 10,
    set: 'seaside',
    canOwn: ownsItem('weapon_armoire_sandySpade'),
    canBuy: () => true,
  },
  cannon: {
    text: t('weaponArmoireCannonText'),
    notes: t('weaponArmoireCannonNotes', { str: 15 }),
    value: 100,
    str: 15,
    set: 'cannoneer',
    canOwn: ownsItem('weapon_armoire_cannon'),
    canBuy: () => true,
  },
  vermilionArcherBow: {
    text: t('weaponArmoireVermilionArcherBowText'),
    notes: t('weaponArmoireVermilionArcherBowNotes', { str: 15 }),
    value: 100,
    str: 15,
    twoHanded: true,
    set: 'vermilionArcher',
    canOwn: ownsItem('weapon_armoire_vermilionArcherBow'),
    canBuy: () => true,
  },
  ogreClub: {
    text: t('weaponArmoireOgreClubText'),
    notes: t('weaponArmoireOgreClubNotes', { str: 15 }),
    value: 100,
    str: 15,
    set: 'ogre',
    canOwn: ownsItem('weapon_armoire_ogreClub'),
    canBuy: () => true,
  },
  woodElfStaff: {
    text: t('weaponArmoireWoodElfStaffText'),
    notes: t('weaponArmoireWoodElfStaffNotes', { int: 12 }),
    value: 100,
    int: 12,
    set: 'woodElf',
    canOwn: ownsItem('weapon_armoire_woodElfStaff'),
    canBuy: () => true,
  },
  wandOfHearts: {
    text: t('weaponArmoireWandOfHeartsText'),
    notes: t('weaponArmoireWandOfHeartsNotes', { int: 13 }),
    value: 100,
    int: 13,
    set: 'queenOfHearts',
    canOwn: ownsItem('weapon_armoire_wandOfHearts'),
    canBuy: () => true,
  },
  forestFungusStaff: {
    text: t('weaponArmoireForestFungusStaffText'),
    notes: t('weaponArmoireForestFungusStaffNotes', { int: 8, per: 9 }),
    value: 100,
    int: 8,
    per: 9,
    canOwn: ownsItem('weapon_armoire_forestFungusStaff'),
    canBuy: () => true,
  },
  festivalFirecracker: {
    text: t('weaponArmoireFestivalFirecrackerText'),
    notes: t('weaponArmoireFestivalFirecrackerNotes', { per: 8 }),
    value: 100,
    per: 8,
    set: 'festivalAttire',
    canOwn: ownsItem('weapon_armoire_festivalFirecracker'),
    canBuy: () => true,
  },
  merchantsDisplayTray: {
    text: t('weaponArmoireMerchantsDisplayTrayText'),
    notes: t('weaponArmoireMerchantsDisplayTrayNotes', { int: 10 }),
    value: 100,
    int: 10,
    set: 'merchant',
    canOwn: ownsItem('weapon_armoire_merchantsDisplayTray'),
    canBuy: () => true,
  },
  battleAxe: {
    text: t('weaponArmoireBattleAxeText'),
    notes: t('weaponArmoireBattleAxeNotes', { int: 6, con: 8 }),
    value: 100,
    int: 6,
    con: 8,
    canOwn: ownsItem('weapon_armoire_battleAxe'),
    canBuy: () => true,
  },
  hoofClippers: {
    text: t('weaponArmoireHoofClippersText'),
    notes: t('weaponArmoireHoofClippersNotes', { attrs: 6 }),
    value: 100,
    con: 6,
    int: 6,
    str: 6,
    set: 'farrier',
    canOwn: ownsItem('weapon_armoire_hoofClippers'),
    canBuy: () => true,
  },
  weaversComb: {
    text: t('weaponArmoireWeaversCombText'),
    notes: t('weaponArmoireWeaversCombNotes', { per: 8, str: 9 }),
    value: 100,
    per: 8,
    str: 9,
    set: 'weaver',
    canOwn: ownsItem('weapon_armoire_weaversComb'),
    canBuy: () => true,
  },
  lamplighter: {
    text: t('weaponArmoireLamplighterText'),
    notes: t('weaponArmoireLamplighterNotes', { per: 6, con: 8 }),
    value: 100,
    per: 6,
    con: 8,
    set: 'lamplighter',
    canOwn: ownsItem('weapon_armoire_lamplighter'),
    canBuy: () => true,
  },
  coachDriversWhip: {
    text: t('weaponArmoireCoachDriversWhipText'),
    notes: t('weaponArmoireCoachDriversWhipNotes', { str: 6, int: 8 }),
    value: 100,
    str: 6,
    int: 8,
    set: 'coachDriver',
    canOwn: ownsItem('weapon_armoire_coachDriversWhip'),
    canBuy: () => true,
  },
  scepterOfDiamonds: {
    text: t('weaponArmoireScepterOfDiamondsText'),
    notes: t('weaponArmoireScepterOfDiamondsNotes', { str: 13 }),
    value: 100,
    str: 13,
    set: 'kingOfDiamonds',
    canOwn: ownsItem('weapon_armoire_scepterOfDiamonds'),
    canBuy: () => true,
  },
  flutteryArmy: {
    text: t('weaponArmoireFlutteryArmyText'),
    notes: t('weaponArmoireFlutteryArmyNotes', { attrs: 5 }),
    value: 100,
    con: 5,
    int: 5,
    str: 5,
    set: 'fluttery',
    canOwn: ownsItem('weapon_armoire_flutteryArmy'),
    canBuy: () => true,
  },
  cobblersHammer: {
    text: t('weaponArmoireCobblersHammerText'),
    notes: t('weaponArmoireCobblersHammerNotes', { attrs: 7 }),
    value: 100,
    con: 7,
    str: 7,
    set: 'cobbler',
    canOwn: ownsItem('weapon_armoire_cobblersHammer'),
    canBuy: () => true,
  },
  glassblowersBlowpipe: {
    text: t('weaponArmoireGlassblowersBlowpipeText'),
    notes: t('weaponArmoireGlassblowersBlowpipeNotes', { str: 6 }),
    value: 100,
    str: 6,
    set: 'glassblower',
    canOwn: ownsItem('weapon_armoire_glassblowersBlowpipe'),
    canBuy: () => true,
  },
  poisonedGoblet: {
    text: t('weaponArmoirePoisonedGobletText'),
    notes: t('weaponArmoirePoisonedGobletNotes', { int: 7 }),
    value: 100,
    int: 7,
    set: 'piraticalPrincess',
    canOwn: ownsItem('weapon_armoire_poisonedGoblet'),
    canBuy: () => true,
  },
  jeweledArcherBow: {
    text: t('weaponArmoireJeweledArcherBowText'),
    notes: t('weaponArmoireJeweledArcherBowNotes', { int: 15 }),
    twoHanded: true,
    value: 100,
    int: 15,
    set: 'jeweledArcher',
    canOwn: ownsItem('weapon_armoire_jeweledArcherBow'),
    canBuy: () => true,
  },
  needleOfBookbinding: {
    text: t('weaponArmoireNeedleOfBookbindingText'),
    notes: t('weaponArmoireNeedleOfBookbindingNotes', { str: 8 }),
    value: 100,
    str: 8,
    set: 'bookbinder',
    canOwn: ownsItem('weapon_armoire_needleOfBookbinding'),
    canBuy: () => true,
  },
  spearOfSpades: {
    text: t('weaponArmoireSpearOfSpadesText'),
    notes: t('weaponArmoireSpearOfSpadesNotes', { con: 13 }),
    value: 100,
    con: 13,
    set: 'aceOfSpades',
    canOwn: ownsItem('weapon_armoire_spearOfSpades'),
    canBuy: () => true,
  },
  arcaneScroll: {
    text: t('weaponArmoireArcaneScrollText'),
    notes: t('weaponArmoireArcaneScrollNotes', { int: 9 }),
    value: 100,
    int: 9,
    set: 'scribe',
    canOwn: ownsItem('weapon_armoire_arcaneScroll'),
    canBuy: () => true,
  },
  chefsSpoon: {
    text: t('weaponArmoireChefsSpoonText'),
    notes: t('weaponArmoireChefsSpoonNotes', { int: 8 }),
    value: 100,
    int: 8,
    set: 'chef',
    canOwn: ownsItem('weapon_armoire_chefsSpoon'),
    canBuy: () => true,
  },
  vernalTaper: {
    text: t('weaponArmoireVernalTaperText'),
    notes: t('weaponArmoireVernalTaperNotes', { con: 8 }),
    value: 100,
    con: 8,
    set: 'vernalVestments',
    canOwn: ownsItem('weapon_armoire_vernalTaper'),
    canBuy: () => true,
  },
  jugglingBalls: {
    text: t('weaponArmoireJugglingBallsText'),
    notes: t('weaponArmoireJugglingBallsNotes', { int: 10 }),
    value: 100,
    int: 10,
    canOwn: ownsItem('weapon_armoire_jugglingBalls'),
    canBuy: () => true,
  },
  slingshot: {
    text: t('weaponArmoireSlingshotText'),
    notes: t('weaponArmoireSlingshotNotes', { str: 10 }),
    value: 100,
    str: 10,
    canOwn: ownsItem('weapon_armoire_slingshot'),
    canBuy: () => true,
  },
  nephriteBow: {
    text: t('weaponArmoireNephriteBowText'),
    notes: t('weaponArmoireNephriteBowNotes', { int: 7, str: 6 }),
    value: 100,
    int: 7,
    str: 6,
    set: 'nephrite',
    twoHanded: true,
    canOwn: ownsItem('weapon_armoire_nephriteBow'),
    canBuy: () => true,
  },
  bambooCane: {
    text: t('weaponArmoireBambooCaneText'),
    notes: t('weaponArmoireBambooCaneNotes', { attrs: 6 }),
    value: 100,
    int: 6,
    per: 6,
    con: 6,
    set: 'boating',
    canOwn: ownsItem('weapon_armoire_bambooCane'),
    canBuy: () => true,
  },
  astronomersTelescope: {
    text: t('weaponArmoireAstronomersTelescopeText'),
    notes: t('weaponArmoireAstronomersTelescopeNotes', { per: 10 }),
    value: 100,
    per: 10,
    set: 'astronomer',
    canOwn: ownsItem('weapon_armoire_astronomersTelescope'),
    canBuy: () => true,
  },
  magnifyingGlass: {
    text: t('weaponArmoireMagnifyingGlassText'),
    notes: t('weaponArmoireMagnifyingGlassNotes', { per: 7 }),
    value: 100,
    per: 7,
    set: 'detective',
    canOwn: ownsItem('weapon_armoire_magnifyingGlass'),
    canBuy: () => true,
  },
  floridFan: {
    text: t('weaponArmoireFloridFanText'),
    notes: t('weaponArmoireFloridFanNotes', { con: 9 }),
    value: 100,
    con: 9,
    canOwn: ownsItem('weapon_armoire_floridFan'),
    canBuy: () => true,
  },
  resplendentRapier: {
    text: t('weaponArmoireResplendentRapierText'),
    notes: t('weaponArmoireResplendentRapierNotes', { per: 9 }),
    value: 100,
    per: 9,
    canOwn: ownsItem('weapon_armoire_resplendentRapier'),
    canBuy: () => true,
  },
  shadowMastersMace: {
    text: t('weaponArmoireShadowMastersMaceText'),
    notes: t('weaponArmoireShadowMastersMaceNotes', { per: 12 }),
    value: 100,
    per: 12,
    set: 'shadowMaster',
    canOwn: ownsItem('weapon_armoire_shadowMastersMace'),
    canBuy: () => true,
  },
  alchemistsDistiller: {
    text: t('weaponArmoireAlchemistsDistillerText'),
    notes: t('weaponArmoireAlchemistsDistillerNotes', { str: 8, int: 5 }),
    value: 100,
    str: 8,
    int: 5,
    set: 'alchemist',
    canOwn: ownsItem('weapon_armoire_alchemistsDistiller'),
    canBuy: () => true,
  },
  happyBanner: {
    text: t('weaponArmoireHappyBannerText'),
    notes: t('weaponArmoireHappyBannerNotes', { per: 7 }),
    value: 100,
    per: 7,
    set: 'birthday',
    canOwn: ownsItem('weapon_armoire_happyBanner'),
    canBuy: () => true,
  },
  livelyMatch: {
    text: t('weaponArmoireLivelyMatchText'),
    notes: t('weaponArmoireLivelyMatchNotes', { str: 15 }),
    value: 100,
    str: 15,
    set: 'matchMaker',
    canOwn: ownsItem('weapon_armoire_livelyMatch'),
    canBuy: () => true,
  },
  baseballBat: {
    text: t('weaponArmoireBaseballBatText'),
    notes: t('weaponArmoireBaseballBatNotes', { con: 9 }),
    value: 100,
    con: 9,
    set: 'baseball',
    canOwn: ownsItem('weapon_armoire_baseballBat'),
    canBuy: () => true,
  },
  paperCutter: {
    text: t('weaponArmoirePaperCutterText'),
    notes: t('weaponArmoirePaperCutterNotes', { str: 9 }),
    value: 100,
    str: 9,
    set: 'paperKnight',
    canOwn: ownsItem('weapon_armoire_paperCutter'),
    canBuy: () => true,
  },
  fiddlersBow: {
    text: t('weaponArmoireFiddlersBowText'),
    notes: t('weaponArmoireFiddlersBowNotes', { str: 6 }),
    value: 100,
    str: 6,
    set: 'fiddler',
    canOwn: ownsItem('weapon_armoire_fiddlersBow'),
    canBuy: () => true,
  },
};

export {
  armor,
  body,
  eyewear,
  head,
  headAccessory,
  shield,
  weapon,
};
