import t from '../../translation';

let armor = {
  1: {
    text: t('armorRogue1Text'),
    notes: t('armorRogue1Notes', { per: 6 }),
    textlocaleKey: 'armorRogue1Text',
    notesLocalKey: 'armorRogue1Notes',
    per: 6,
    value: 30,
  },
  2: {
    text: t('armorRogue2Text'),
    notes: t('armorRogue2Notes', { per: 9 }),
    textlocaleKey: 'armorRogue2Text',
    notesLocalKey: 'armorRogue2Notes',
    per: 9,
    value: 45,
  },
  3: {
    text: t('armorRogue3Text'),
    notes: t('armorRogue3Notes', { per: 12 }),
    textlocaleKey: 'armorRogue3Text',
    notesLocalKey: 'armorRogue3Notes',
    per: 12,
    value: 65,
  },
  4: {
    text: t('armorRogue4Text'),
    notes: t('armorRogue4Notes', { per: 15 }),
    textlocaleKey: 'armorRogue4Text',
    notesLocalKey: 'armorRogue4Notes',
    per: 15,
    value: 90,
  },
  5: {
    text: t('armorRogue5Text'),
    notes: t('armorRogue5Notes', { per: 18 }),
    textlocaleKey: 'armorRogue5Text',
    notesLocalKey: 'armorRogue5Notes',
    per: 18,
    value: 120,
    last: true,
  },
};

let head = {
  1: {
    text: t('headRogue1Text'),
    notes: t('headRogue1Notes', { per: 2 }),
    textlocaleKey: 'headRogue1Text',
    notesLocalKey: 'headRogue1Notes',
    per: 2,
    value: 15,
  },
  2: {
    text: t('headRogue2Text'),
    notes: t('headRogue2Notes', { per: 4 }),
    textlocaleKey: 'headRogue2Text',
    notesLocalKey: 'headRogue2Notes',
    per: 4,
    value: 25,
  },
  3: {
    text: t('headRogue3Text'),
    notes: t('headRogue3Notes', { per: 6 }),
    textlocaleKey: 'headRogue3Text',
    notesLocalKey: 'headRogue3Notes',
    per: 6,
    value: 40,
  },
  4: {
    text: t('headRogue4Text'),
    notes: t('headRogue4Notes', { per: 9 }),
    textlocaleKey: 'headRogue4Text',
    notesLocalKey: 'headRogue4Notes',
    per: 9,
    value: 60,
  },
  5: {
    text: t('headRogue5Text'),
    notes: t('headRogue5Notes', { per: 12 }),
    textlocaleKey: 'headRogue5Text',
    notesLocalKey: 'headRogue5Notes',
    per: 12,
    value: 80,
    last: true,
  },
};

let weapon = {
  0: {
    text: t('weaponRogue0Text'),
    notes: t('weaponRogue0Notes'),
    textlocaleKey: 'weaponRogue0Text',
    notesLocalKey: 'weaponRogue0Notes',
    str: 0,
    value: 0,
  },
  1: {
    text: t('weaponRogue1Text'),
    notes: t('weaponRogue1Notes', { str: 2 }),
    textlocaleKey: 'weaponRogue1Text',
    notesLocalKey: 'weaponRogue1Notes',
    str: 2,
    value: 20,
  },
  2: {
    text: t('weaponRogue2Text'),
    notes: t('weaponRogue2Notes', { str: 3 }),
    textlocaleKey: 'weaponRogue2Text',
    notesLocalKey: 'weaponRogue2Notes',
    str: 3,
    value: 35,
  },
  3: {
    text: t('weaponRogue3Text'),
    notes: t('weaponRogue3Notes', { str: 4 }),
    textlocaleKey: 'weaponRogue3Text',
    notesLocalKey: 'weaponRogue3Notes',
    str: 4,
    value: 50,
  },
  4: {
    text: t('weaponRogue4Text'),
    notes: t('weaponRogue4Notes', { str: 6 }),
    textlocaleKey: 'weaponRogue4Text',
    notesLocalKey: 'weaponRogue4Notes',
    str: 6,
    value: 70,
  },
  5: {
    text: t('weaponRogue5Text'),
    notes: t('weaponRogue5Notes', { str: 8 }),
    textlocaleKey: 'weaponRogue5Text',
    notesLocalKey: 'weaponRogue5Notes',
    str: 8,
    value: 90,
  },
  6: {
    text: t('weaponRogue6Text'),
    notes: t('weaponRogue6Notes', { str: 10 }),
    textlocaleKey: 'weaponRogue6Text',
    notesLocalKey: 'weaponRogue6Notes',
    str: 10,
    value: 120,
    last: true,
  },
};

let shield = {
  0: {
    text: t('weaponRogue0Text'),
    notes: t('weaponRogue0Notes'),
    textlocaleKey: 'weaponRogue0Text',
    notesLocalKey: 'weaponRogue0Notes',
    str: 0,
    value: 0,
  },
  1: {
    text: t('weaponRogue1Text'),
    notes: t('weaponRogue1Notes', { str: 2 }),
    textlocaleKey: 'weaponRogue1Text',
    notesLocalKey: 'weaponRogue1Notes',
    str: 2,
    value: 20,
  },
  2: {
    text: t('weaponRogue2Text'),
    notes: t('weaponRogue2Notes', { str: 3 }),
    textlocaleKey: 'weaponRogue2Text',
    notesLocalKey: 'weaponRogue2Notes',
    str: 3,
    value: 35,
  },
  3: {
    text: t('weaponRogue3Text'),
    notes: t('weaponRogue3Notes', { str: 4 }),
    textlocaleKey: 'weaponRogue3Text',
    notesLocalKey: 'weaponRogue3Notes',
    str: 4,
    value: 50,
  },
  4: {
    text: t('weaponRogue4Text'),
    notes: t('weaponRogue4Notes', { str: 6 }),
    textlocaleKey: 'weaponRogue4Text',
    notesLocalKey: 'weaponRogue4Notes',
    str: 6,
    value: 70,
  },
  5: {
    text: t('weaponRogue5Text'),
    notes: t('weaponRogue5Notes', { str: 8 }),
    textlocaleKey: 'weaponRogue5Text',
    notesLocalKey: 'weaponRogue5Notes',
    str: 8,
    value: 90,
  },
  6: {
    text: t('weaponRogue6Text'),
    notes: t('weaponRogue6Notes', { str: 10 }),
    textlocaleKey: 'weaponRogue6Text',
    notesLocalKey: 'weaponRogue6Notes',
    str: 10,
    value: 120,
    last: true,
  },
};

let rogueSet = {
  armor,
  head,
  shield,
  weapon,
};

module.exports = rogueSet;
