<template lang="pug">
  .container-fluid
    h1 Privacy Policy
    p.pagemeta
      | Last updated July 27, 2015
      br
      small (Corrected grammar errors and updated company name)
      br
      br
    p
      strong PLEASE READ THIS PRIVACY POLICY CAREFULLY&period;
      br
      | By accessing or otherwise using habitica&period;com or any sub domains thereto &lpar;&quot;the Sites&quot;&rpar;&comma;
      | or using a habitica&period;com or Habitica application on a mobile device &lpar;&quot;the Applications&quot;&rpar;&comma;
      | you agree to be bound contractually by this Privacy Policy&period; Individually
      | or collectively&comma; the Applications and the Sites may be referred to as
      | the &quot;Services&period;&quot;
    p
      | To review material modifications and their effective dates scroll
      | to the bottom of the page&period;
    p
      strong
        | 1&period; Privacy Statement&semi; Collection of Personal
        | Information&period;
      br
      | 1&period;1 HabitRPG, Inc. owns and operates this business&period; All
      | references to &quot;we&quot;&comma; &quot;us&quot;&comma; shall be construed to mean HabitRPG, Inc.&period;
    p
      | 1&period;2 We understand that visitors to this website are concerned
      | about the privacy of information&period; The following describes our privacy
      | policy regarding information&comma; including personal information&comma; that we
      | collect through this website&period;
    p
      strong 2&period; Modification of Privacy Policy&period;
      br
      | We reserve the right to modify this Privacy Policy at any time&comma;
      | and without prior notice&comma; by posting an amended Privacy Policy that is
      | always accessible by clicking on the &quot;Privacy Policy&quot; link on this
      | site&apos;s home page&period; Your continued use of this site indicates your
      | acceptance of the amended Privacy Policy&period; You should check the Privacy
      | Policy through this link periodically for modifications by clicking on
      | the link provided near the top of the Privacy Policy for a listing of
      | material modifications and their effective dates&period; Regarding personal
      | information&comma; if any modifications are materially less restrictive on our
      | use or disclosure of the personal information previously disclosed by
      | you&comma; we will obtain your consent before implementing such revisions with
      | respect to such information&period;
    p
      strong 3&period; Collection of Anonymous&comma; Passive Information&period;
      br
      | We reserve the right to monitor your use of the services&period; As you
      | navigate through the services&comma; certain anonymous information may be
      | passively collected &lpar;that is&comma; gathered without your actively providing
      | the information&rpar; using various technologies&comma; such as cookies&comma; Internet
      | tags or web beacons&comma; and navigational data collection &lpar;log files&comma; server
      | logs&comma; clickstream&rpar;&period; The following is a listing and a brief explanation
      | of passive information collection methodologies which we may use from
      | time to time to better understand how the Services are being used&period;
    p
      | 3&period;1 A &quot;cookie&quot; is a text file that this site sends to your
      | browser in the form of a text file The information generated by the
      | cookie about your use of this site &lpar;including your IP address&rpar; will be
      | transmitted to and stored&period; Most browsers automatically accept cookies&comma;
      | but they usually can be modified to decline cookies if you prefer&semi;
      | however&comma; certain features of this site might not work without cookies&period;
    p
      | 3&period;2 &quot;Session&quot; cookies are temporary bits of information that are
      | used to improve navigation&comma; block visitors from providing information
      | where inappropriate &lpar;the Services &quot;remembers&quot; previous entries of age or
      | country of origin that were outside the specified parameters and blocks
      | subsequent changes&rpar;&comma; and collect aggregate statistical information on
      | the Services&period; They are erased once you exit your Web browser or
      | otherwise turn off your computer&period;
    p
      | 3&period;3 &quot;Persistent&quot; cookies are more permanent bits of information
      | that are placed on the hard drive of your computer and stay there unless
      | you delete the cookie&period; Persistent cookies store information on your
      | computer for a number of purposes&comma; such as retrieving certain
      | information you have previously provided&comma; helping to determine what
      | areas of the Services you may find most valuable&comma; and customizing the
      | Services based on your preferences on an ongoing basis&period; Persistent
      | cookies placed by this site in your computer do not hold personal
      | information&period;
    p
      | 3&period;4 You can set your browser to accept all cookies&comma; to reject all
      | cookies&comma; or to notify you whenever a cookie is offered so that you can
      | decide each time whether to accept it&period; To learn more about cookies and
      | how to specify your preferences&comma; please search for &quot;cookie&quot; in the
      | &quot;Help&quot; portion of your browser&period;
    p
      | 3&period;5 An Internet Protocol &lpar;IP&rpar; address is a number assigned to
      | your computer by your Internet service provider so you can access the
      | Internet and is generally considered to be non-personally identifiable
      | information&comma; because in most cases an IP address is dynamic &lpar;changing
      | each time you connect to the Internet&rpar;&comma; rather than static &lpar;unique to a
      | particular user&apos;s computer&rpar;&period; The IP address can be used to diagnose
      | problems with a server&comma; report aggregate information&comma; determine the
      | fastest route for your computer to use in connecting to a site&comma; and
      | administer and improve the Services&period;
    p
      | 3&period;6 &quot;Internet tags&quot; &lpar;also known as Web Beacons&comma; single-pixel
      | GIFs&comma; clear GIFs&comma; invisible GIFs&comma; and 1-by-1 GIFs&rpar; are smaller than
      | cookies and tell the Web site server information such as the IP address
      | and browser type related to the visitor&apos;s computer&period; Tags may be placed
      | both on online advertisements that bring people to the Services and on
      | different pages of the Services&period; Such tags indicate how many times a
      | page is opened and which information is consulted&period;
    p
      | 3&period;7 &quot;Navigational data&quot; &lpar;log files&comma; server logs&comma; and clickstream
      | data&rpar; are used for system management&comma; to improve the content of the
      | Services&comma; market research purposes&comma; and to communicate information to
      | visitors&period;
    p
      strong 4&period; Use and Sharing of Anonymous&comma; Passive Information&period;
      br
      | The Services may make full use of passively collected anonymous
      | information&comma; including without limitation the right to use such
      | information to provide better service to Service users&comma; customize the
      | Services based on your preferences&comma; compile and analyze statistics and
      | trends&comma; and otherwise administer and improve the Services for your use&period; We
      | reserve the right to share this anonymous&comma; passive information in
      | aggregated form&period;
    p
      strong 5&period; 3rd Party Behavioral Ads&semi; Google&apos;s AdSense Network&period;
      br
      | 5&period;1 We reserve the right to use anonymous&comma; passive information
      | about your visits to this and other websites &lpar;not including your name&comma;
      | address&comma; email address or telephone number&rpar; for purposes of serving our
      | ads and third party ads that are targeted to your interests &lpar;&quot;3rd Party
      | Behavioral Ads&quot;&rpar;&period; We reserve the right to share anonymous&comma; passive
      | information collected on the services with third parties for purposes of
      | serving 3rd Party Behavioral Ads&period; These 3rd Party Behavioral Ads do not
      | identify you personally&period; Instead&comma; they associate your behavioral data on
      | visited sites with your browser&comma; so that the ads your computer sees on
      | this site are more likely to be relevant to your interests&period; 3rd Party
      | Behavioral Ads require that that you be served with a cookie containing
      | a tracking code&period; You may refuse the use of cookies by selecting the
      | appropriate settings on your browser&semi; however&comma; please note that if you
      | do this you may not be able to use the full functionality of this site&period;
    p
      | 5&period;2 We reserve the right to participate in Google&apos;s AdSense
      | network for purposes of serving 3rd Party Behavioral Ads&period; Google uses
      | DoubleClick&apos;s DART cookie for serving 3rd Party Behavioral Ads over the
      | AdSense network&period; You may opt out of the use of the DART cookie&period; For
      | information regarding how to opt out&comma; go to
      | http&colon;&sol;&sol;www&period;google&period;com&sol;privacy&UnderBar;ads&period;html&period;
    p
      strong 6&period; Use of 3rd Party Analytics&period;
      br
      | We reserve the right to use analytics services provided by
      | third parties&period; These services use 3rd party cookies to collect
      | anonymous&comma; passive information about your use of this site &lpar;see
      | explanation of cookies in Collection of Anonymous&comma; Passive Information
      | above&rpar;&period; We use this information for the purpose of evaluating your use
      | of the Services&comma; compiling reports on activity&comma; and providing other
      | services&period; These web analytics services may also transfer this
      | information to third parties where required to do so by law&comma; or where
      | such third parties process the information on the service&apos;s behalf&period;
    p
      strong 7&period; Collection of Personal Information&semi; Categories&period;
      br
      | We will ask you for personal information when you sign up for any
      | specific benefit or purpose that requires registration&period; Personal
      | information that we collect may vary with each registration&comma; and it may
      | include one or more of the following categories&colon; name&comma; physical
      | address&comma; an email address&comma; phone number&comma; and credit card information
      | including credit card number&comma; expiration date&comma; and billing address&comma;
      | emergency contact information&comma; current medications&comma; allergies&comma; medical
      | insurance information&period;
    p
      strong
        | 8&period; Use And Sharing of Personal Information&colon; General
        | Policy And Exceptions&period;
      br
      | Our general policy is that we will use your personal information&comma;
      | including combining your personal information with passive information
      | collected from this site&comma; only for&colon; the performance of the services or
      | transaction for which it was given&comma; our private&comma; internal reporting for
      | this site&comma; and security assessments for this site&comma; and we will not
      | share&comma; sell&comma; or rent your personal information to others&period; The only
      | exceptions to this general policy&colon; &lpar;i&rpar; are described in the subsections
      | below&comma; and &lpar;ii&rpar; if you explicitly approve through our site&period;
    p
      | 8&period;1 Affiliates And Service Providers&period; We reserve the right to
      | provide such information to our affiliates or subsidiaries&comma; or trusted
      | service providers for the purpose of hosting our servers or processing
      | or archiving personal information for us&period; We require that these parties
      | agree to privacy and security safeguards for this information that are
      | consistent with this Privacy Policy&period;
    p
      | 8&period;2 Acquisition&semi; Bankruptcy&period; In the event that we are acquired by
      | or merged with a third party entity&comma; we reserve the right to transfer
      | such information as part of such merger&comma; acquisition&comma; sale&comma; or other
      | change of control&period; In the unlikely event of our bankruptcy&comma; insolvency&comma;
      | reorganization&comma; receivership&comma; or assignment for the benefit of
      | creditors&comma; or the application of laws or equitable principles affecting
      | creditors&apos; rights generally&comma; we reserve the right to transfer such
      | information to protect our rights or as required by law&period;
    p
      | 8&period;3 Enforcement&semi; Legal Process&period; We reserve the right to transfer
      | such information if we have a good faith belief that access&comma; use&comma;
      | preservation or disclosure of such information is reasonably necessary
      | &lpar;i&rpar; to satisfy any applicable law&comma; regulation&comma; legal process or
      | enforceable governmental request&comma; or &lpar;ii&rpar; to investigate or enforce
      | violations of our rights or the security of this site&period;
    p
      | 8&period;4 Miscellaneous&period; We reserve the right to share personal
      | information with the following additional parties&colon; online organizers
      | using our tools and resellers of our products and services from whose
      | site the sale originated &lpar;even though the sale originates at site of the
      | reseller&comma; registration and collection of personal information occurs at
      | this site&rpar;&period;
    p
      strong
        | 9&period; Onward Transfer of Personal Information Outside Your
        | Country of Residence&period;
      br
      | Any personal information which we may collect on this site will
      | be stored and processed in our servers located only in the United
      | States&period; By using this site&comma; if you reside outside the United States&comma; you
      | consent to the transfer of personal information outside your country of
      | residence to the United States&period;
    p
      strong 10&period; Security of Personal Information&period;
      br
      | We follow reasonable and appropriate industry standards to
      | protect your personal information and data&period; Unfortunately&comma; no data
      | transmission over the Internet or method of data storage can be
      | guaranteed 100&percnt; secure&period; Therefore&comma; while we strive to protect your
      | personal information by following generally accepted industry standards&comma;
      | we cannot ensure or warrant the absolute security of any information you
      | transmit to us or archive at this site&period;
    p
      strong 11&period; Changing And Updating Personal Information&period;
      br
      | Upon request&comma; we will permit you to request or make changes or
      | updates to your personal information for legitimate purposes&period; We request
      | identification prior to approving such requests&period; We reserve the right to
      | decline any requests that are unreasonably repetitive or systematic&comma;
      | require unreasonable time or effort of our technical or administrative
      | personnel&comma; or undermine the privacy rights of others&period; We reserve the
      | right to permit you to access your personal information in any account
      | you establish with this site for purposes of making your own changes or
      | updates&comma; and in such case&comma; instructions for making such changes or
      | updates will be provided where necessary&period;
    p
      strong 12&period; Email From This Site&semi; Opt-Out Rights&period;
      br
      | If you supply us with your e-mail address you may receive
      | periodic messages from us with information specific to the Services and
      | required for the normal functioning of the Services as well as for new
      | products or services or upcoming events&period; If you prefer not to receive
      | periodic email messages&comma; you may opt-out by following the instructions
      | on the email&period;
    p
      strong 13&period; Children&apos;s Online Policy&period;
      br
      | We are committed to preserving online privacy for all of our
      | website visitors&comma; including children&period; This site is a general audience
      | site&period; Consistent with the Children&apos;s Online Privacy Protection Act
      | &lpar;COPPA&rpar;&comma; we will not knowingly collect any information from&comma; or sell to&comma;
      | children under the age of 13&period; If you are a parent or guardian who has
      | discovered that your child under the age of 13 has submitted his or her
      | personally identifiable information without your permission or consent&comma;
      | we will remove the information from our active list&comma; at your request&period; To
      | request the removal of your child&apos;s information&comma; please email us at
      | <a href='mailto:admin@habitica.com' target='_blank'>admin@habitica.com</a> and be sure to include in
      | your message the same login information that your child submitted&period;
    p
      strong
        | 14&period; Email And Other Messages Through This Site&semi; ECPA
        | Notice&period;
      br
      | This site treats email messages and other electronic messages
      | that are sent through this site and not viewable by others as
      | confidential and private&comma; except as required by law&comma; including without
      | limitation&comma; the Electronic Communications Privacy Act of 1986&comma; 18 U&period;S&period;C&period;
      | Sections 2701-2711 &lpar;the &quot;ECPA&quot;&rpar;&period; The ECPA permits this site&apos;s limited
      | ability to intercept and&sol;or disclose electronic messages&comma; for example
      | &lpar;i&rpar; as necessary to operate our system or to protect our rights or
      | property&comma; &lpar;ii&rpar; upon legal demand &lpar;court orders&comma; warrants&comma; subpoenas&rpar;&comma; or
      | &lpar;iii&rpar; where we receive information inadvertently which appears to
      | pertain to the commission of a crime&period; This site is not considered a
      | &quot;secure communications medium&quot; under the ECPA&period;
    p
      strong 15&period; Contact Us&period;
      br
      | If you have any questions regarding this Privacy Policy&comma; please
      | contact the owner and operator of this website business&colon;
    address
      strong HabitRPG, Inc.
      br
      | 11870 Santa Monica Blvd., Suite 106-577
      br
      | Los Angeles, CA 90025
      br
      | Email&colon;&nbsp;
      a(href='mailto:admin@habitica.com') admin@habitica.com
</template>
