import {
  EVENTS,
} from '../../../constants';
import { ownsItem } from '../../gear-helper';
import backerGear from './special-backer';
import contributorGear from './special-contributor';
import takeThisGear from './special-takeThis';
import wonderconGear from './special-wondercon';
import t from '../../../translation';

let armor = {
  0: backerGear.armorSpecial0,
  1: contributorGear.armorSpecial1,
  2: backerGear.armorSpecial2,
  takeThis: takeThisGear.armorSpecialTakeThis,
  finnedOceanicArmor: {
    text: t('armorSpecialFinnedOceanicArmorText'),
    notes: t('armorSpecialFinnedOceanicArmorNotes', { str: 15 }),
    textlocaleKey: 'armorSpecialFinnedOceanicArmorText',
    notesLocalKey: 'armorSpecialFinnedOceanicArmorNotes',
    str: 15,
    value: 130,
    canOwn: ownsItem('armor_special_finnedOceanicArmor'),
  },
  pyromancersRobes: {
    text: t('armorSpecialPyromancersRobesText'),
    notes: t('armorSpecialPyromancersRobesNotes', { con: 15 }),
    textlocaleKey: 'armorSpecialPyromancersRobesText',
    notesLocalKey: 'armorSpecialPyromancersRobesNotes',
    con: 15,
    value: 130,
    canOwn: ownsItem('armor_special_pyromancersRobes'),
  },
  bardRobes: {
    text: t('armorSpecialBardRobesText'),
    notes: t('armorSpecialBardRobesNotes', { per: 3 }),
    textlocaleKey: 'armorSpecialBardRobesText',
    notesLocalKey: 'armorSpecialBardRobesNotes',
    per: 3,
    value: 0,
    canOwn: ownsItem('armor_special_bardRobes'),
  },
  lunarWarriorArmor: {
    text: t('armorSpecialLunarWarriorArmorText'),
    notes: t('armorSpecialLunarWarriorArmorNotes', { attrs: 7 }),
    textlocaleKey: 'armorSpecialLunarWarriorArmorText',
    notesLocalKey: 'armorSpecialLunarWarriorArmorNotes',
    str: 7,
    con: 7,
    value: 130,
    canOwn: ownsItem('armor_special_lunarWarriorArmor'),
  },
  mammothRiderArmor: {
    text: t('armorSpecialMammothRiderArmorText'),
    notes: t('armorSpecialMammothRiderArmorNotes', { con: 15 }),
    textlocaleKey: 'armorSpecialMammothRiderArmorText',
    notesLocalKey: 'armorSpecialMammothRiderArmorNotes',
    con: 15,
    value: 130,
    canOwn: ownsItem('armor_special_mammothRiderArmor'),
  },
  pageArmor: {
    text: t('armorSpecialPageArmorText'),
    notes: t('armorSpecialPageArmorNotes', { con: 16 }),
    textlocaleKey: 'armorSpecialPageArmorText',
    notesLocalKey: 'armorSpecialPageArmorNotes',
    con: 16,
    value: 0,
    canOwn: ownsItem('armor_special_pageArmor'),
  },
  yeti: {
    event: EVENTS.winter,
    specialClass: 'warrior',
    text: t('armorSpecialYetiText'),
    notes: t('armorSpecialYetiNotes', { con: 9 }),
    textlocaleKey: 'armorSpecialPageArmorText',
    notesLocalKey: 'armorSpecialPageArmorNotes',
    con: 9,
    value: 90,
    canBuy: () => {
      return true;
    },
  },
  ski: {
    event: EVENTS.winter,
    specialClass: 'rogue',
    text: t('armorSpecialSkiText'),
    notes: t('armorSpecialSkiNotes', { per: 15 }),
    textlocaleKey: 'armorSpecialSkiText',
    notesLocalKey: 'armorSpecialSkiNotes',
    per: 15,
    value: 90,
    canBuy: () => {
      return true;
    },
  },
  candycane: {
    event: EVENTS.winter,
    specialClass: 'wizard',
    text: t('armorSpecialCandycaneText'),
    notes: t('armorSpecialCandycaneNotes', { int: 9 }),
    textlocaleKey: 'armorSpecialCandycaneText',
    notesLocalKey: 'armorSpecialCandycaneNotes',
    int: 9,
    value: 90,
    canBuy: () => {
      return true;
    },
  },
  snowflake: {
    event: EVENTS.winter,
    specialClass: 'healer',
    text: t('armorSpecialSnowflakeText'),
    notes: t('armorSpecialSnowflakeNotes', { con: 15 }),
    textlocaleKey: 'armorSpecialSnowflakeText',
    notesLocalKey: 'armorSpecialSnowflakeNotes',
    con: 15,
    value: 90,
    canBuy: () => {
      return true;
    },
  },
  birthday: {
    event: EVENTS.birthday,
    text: t('armorSpecialBirthdayText'),
    notes: t('armorSpecialBirthdayNotes'),
    textlocaleKey: 'armorSpecialBirthdayText',
    notesLocalKey: 'armorSpecialBirthdayNotes',
    value: 0,
  },
  springRogue: {
    event: EVENTS.spring,
    specialClass: 'rogue',
    text: t('armorSpecialSpringRogueText'),
    notes: t('armorSpecialSpringRogueNotes', { per: 15 }),
    textlocaleKey: 'armorSpecialSpringRogueText',
    notesLocalKey: 'armorSpecialSpringRogueNotes',
    value: 90,
    per: 15,
  },
  springWarrior: {
    event: EVENTS.spring,
    specialClass: 'warrior',
    text: t('armorSpecialSpringWarriorText'),
    notes: t('armorSpecialSpringWarriorNotes', { con: 9 }),
    textlocaleKey: 'armorSpecialSpringWarriorText',
    notesLocalKey: 'armorSpecialSpringWarriorNotes',
    value: 90,
    con: 9,
  },
  springMage: {
    event: EVENTS.spring,
    specialClass: 'wizard',
    text: t('armorSpecialSpringMageText'),
    notes: t('armorSpecialSpringMageNotes', { int: 9 }),
    textlocaleKey: 'armorSpecialSpringMageText',
    notesLocalKey: 'armorSpecialSpringMageNotes',
    value: 90,
    int: 9,
  },
  springHealer: {
    event: EVENTS.spring,
    specialClass: 'healer',
    text: t('armorSpecialSpringHealerText'),
    notes: t('armorSpecialSpringHealerNotes', { con: 15 }),
    textlocaleKey: 'armorSpecialSpringHealerText',
    notesLocalKey: 'armorSpecialSpringHealerNotes',
    value: 90,
    con: 15,
  },
  summerRogue: {
    event: EVENTS.summer,
    specialClass: 'rogue',
    text: t('armorSpecialSummerRogueText'),
    notes: t('armorSpecialSummerRogueNotes', { per: 15 }),
    textlocaleKey: 'armorSpecialSummerRogueText',
    notesLocalKey: 'armorSpecialSummerRogueNotes',
    value: 90,
    per: 15,
  },
  summerWarrior: {
    event: EVENTS.summer,
    specialClass: 'warrior',
    text: t('armorSpecialSummerWarriorText'),
    notes: t('armorSpecialSummerWarriorNotes', { con: 9 }),
    textlocaleKey: 'armorSpecialSummerWarriorText',
    notesLocalKey: 'armorSpecialSummerWarriorNotes',
    value: 90,
    con: 9,
  },
  summerMage: {
    event: EVENTS.summer,
    specialClass: 'wizard',
    text: t('armorSpecialSummerMageText'),
    notes: t('armorSpecialSummerMageNotes', { int: 9 }),
    textlocaleKey: 'armorSpecialSummerMageText',
    notesLocalKey: 'armorSpecialSummerMageNotes',
    value: 90,
    int: 9,
  },
  summerHealer: {
    event: EVENTS.summer,
    specialClass: 'healer',
    text: t('armorSpecialSummerHealerText'),
    notes: t('armorSpecialSummerHealerNotes', { con: 15 }),
    textlocaleKey: 'armorSpecialSummerHealerText',
    notesLocalKey: 'armorSpecialSummerHealerNotes',
    value: 90,
    con: 15,
  },
  fallRogue: {
    event: EVENTS.fall,
    specialClass: 'rogue',
    text: t('armorSpecialFallRogueText'),
    notes: t('armorSpecialFallRogueNotes', { per: 15 }),
    textlocaleKey: 'armorSpecialFallRogueText',
    notesLocalKey: 'armorSpecialFallRogueNotes',
    value: 90,
    per: 15,
  },
  fallWarrior: {
    event: EVENTS.fall,
    specialClass: 'warrior',
    text: t('armorSpecialFallWarriorText'),
    notes: t('armorSpecialFallWarriorNotes', { con: 9 }),
    textlocaleKey: 'armorSpecialFallWarriorText',
    notesLocalKey: 'armorSpecialFallWarriorNotes',
    value: 90,
    con: 9,
  },
  fallMage: {
    event: EVENTS.fall,
    specialClass: 'wizard',
    text: t('armorSpecialFallMageText'),
    notes: t('armorSpecialFallMageNotes', { int: 9 }),
    textlocaleKey: 'armorSpecialFallMageText',
    notesLocalKey: 'armorSpecialFallMageNotes',
    value: 90,
    int: 9,
  },
  fallHealer: {
    event: EVENTS.fall,
    specialClass: 'healer',
    text: t('armorSpecialFallHealerText'),
    notes: t('armorSpecialFallHealerNotes', { con: 15 }),
    textlocaleKey: 'armorSpecialFallHealerText',
    notesLocalKey: 'armorSpecialFallHealerNotes',
    value: 90,
    con: 15,
  },
  winter2015Rogue: {
    event: EVENTS.winter2015,
    specialClass: 'rogue',
    text: t('armorSpecialWinter2015RogueText'),
    notes: t('armorSpecialWinter2015RogueNotes', { per: 15 }),
    textlocaleKey: 'armorSpecialWinter2015RogueText',
    notesLocalKey: 'armorSpecialWinter2015RogueNotes',
    value: 90,
    per: 15,
    canBuy: () => {
      return true;
    },
  },
  winter2015Warrior: {
    event: EVENTS.winter2015,
    specialClass: 'warrior',
    text: t('armorSpecialWinter2015WarriorText'),
    notes: t('armorSpecialWinter2015WarriorNotes', { con: 9 }),
    textlocaleKey: 'armorSpecialWinter2015WarriorText',
    notesLocalKey: 'armorSpecialWinter2015WarriorNotes',
    value: 90,
    con: 9,
    canBuy: () => {
      return true;
    },
  },
  winter2015Mage: {
    event: EVENTS.winter2015,
    specialClass: 'wizard',
    text: t('armorSpecialWinter2015MageText'),
    notes: t('armorSpecialWinter2015MageNotes', { int: 9 }),
    textlocaleKey: 'armorSpecialWinter2015MageText',
    notesLocalKey: 'armorSpecialWinter2015MageNotes',
    value: 90,
    int: 9,
    canBuy: () => {
      return true;
    },
  },
  winter2015Healer: {
    event: EVENTS.winter2015,
    specialClass: 'healer',
    text: t('armorSpecialWinter2015HealerText'),
    notes: t('armorSpecialWinter2015HealerNotes', { con: 15 }),
    textlocaleKey: 'armorSpecialWinter2015HealerText',
    notesLocalKey: 'armorSpecialWinter2015HealerNotes',
    value: 90,
    con: 15,
    canBuy: () => {
      return true;
    },
  },
  birthday2015: {
    text: t('armorSpecialBirthday2015Text'),
    notes: t('armorSpecialBirthday2015Notes'),
    textlocaleKey: 'armorSpecialBirthday2015Text',
    notesLocalKey: 'armorSpecialBirthday2015Notes',
    value: 0,
    canOwn: ownsItem('armor_special_birthday2015'),
  },
  spring2015Rogue: {
    event: EVENTS.spring2015,
    specialClass: 'rogue',
    text: t('armorSpecialSpring2015RogueText'),
    notes: t('armorSpecialSpring2015RogueNotes', { per: 15 }),
    textlocaleKey: 'armorSpecialSpring2015RogueText',
    notesLocalKey: 'armorSpecialSpring2015RogueNotes',
    value: 90,
    per: 15,
  },
  spring2015Warrior: {
    event: EVENTS.spring2015,
    specialClass: 'warrior',
    text: t('armorSpecialSpring2015WarriorText'),
    notes: t('armorSpecialSpring2015WarriorNotes', { con: 9 }),
    textlocaleKey: 'armorSpecialSpring2015WarriorText',
    notesLocalKey: 'armorSpecialSpring2015WarriorNotes',
    value: 90,
    con: 9,
  },
  spring2015Mage: {
    event: EVENTS.spring2015,
    specialClass: 'wizard',
    text: t('armorSpecialSpring2015MageText'),
    notes: t('armorSpecialSpring2015MageNotes', { int: 9 }),
    textlocaleKey: 'armorSpecialSpring2015MageText',
    notesLocalKey: 'armorSpecialSpring2015MageNotes',
    value: 90,
    int: 9,
  },
  spring2015Healer: {
    event: EVENTS.spring2015,
    specialClass: 'healer',
    text: t('armorSpecialSpring2015HealerText'),
    notes: t('armorSpecialSpring2015HealerNotes', { con: 15 }),
    textlocaleKey: 'armorSpecialSpring2015HealerText',
    notesLocalKey: 'armorSpecialSpring2015HealerNotes',
    value: 90,
    con: 15,
  },
  summer2015Rogue: {
    event: EVENTS.summer2015,
    specialClass: 'rogue',
    text: t('armorSpecialSummer2015RogueText'),
    notes: t('armorSpecialSummer2015RogueNotes', { per: 15 }),
    textlocaleKey: 'armorSpecialSummer2015RogueText',
    notesLocalKey: 'armorSpecialSummer2015RogueNotes',
    value: 90,
    per: 15,
  },
  summer2015Warrior: {
    event: EVENTS.summer2015,
    specialClass: 'warrior',
    text: t('armorSpecialSummer2015WarriorText'),
    notes: t('armorSpecialSummer2015WarriorNotes', { con: 9 }),
    textlocaleKey: 'armorSpecialSummer2015WarriorText',
    notesLocalKey: 'armorSpecialSummer2015WarriorNotes',
    value: 90,
    con: 9,
  },
  summer2015Mage: {
    event: EVENTS.summer2015,
    specialClass: 'wizard',
    text: t('armorSpecialSummer2015MageText'),
    notes: t('armorSpecialSummer2015MageNotes', { int: 9 }),
    textlocaleKey: 'armorSpecialSummer2015MageText',
    notesLocalKey: 'armorSpecialSummer2015MageNotes',
    value: 90,
    int: 9,
  },
  summer2015Healer: {
    event: EVENTS.summer2015,
    specialClass: 'healer',
    text: t('armorSpecialSummer2015HealerText'),
    notes: t('armorSpecialSummer2015HealerNotes', { con: 15 }),
    textlocaleKey: 'armorSpecialSummer2015HealerText',
    notesLocalKey: 'armorSpecialSummer2015HealerNotes',
    value: 90,
    con: 15,
  },
  fall2015Rogue: {
    event: EVENTS.fall2015,
    specialClass: 'rogue',
    text: t('armorSpecialFall2015RogueText'),
    notes: t('armorSpecialFall2015RogueNotes', { per: 15 }),
    textlocaleKey: 'armorSpecialFall2015RogueText',
    notesLocalKey: 'armorSpecialFall2015RogueNotes',
    value: 90,
    per: 15,
  },
  fall2015Warrior: {
    event: EVENTS.fall2015,
    specialClass: 'warrior',
    text: t('armorSpecialFall2015WarriorText'),
    notes: t('armorSpecialFall2015WarriorNotes', { con: 9 }),
    textlocaleKey: 'armorSpecialFall2015WarriorText',
    notesLocalKey: 'armorSpecialFall2015WarriorNotes',
    value: 90,
    con: 9,
  },
  fall2015Mage: {
    event: EVENTS.fall2015,
    specialClass: 'wizard',
    text: t('armorSpecialFall2015MageText'),
    notes: t('armorSpecialFall2015MageNotes', { int: 9 }),
    textlocaleKey: 'armorSpecialFall2015MageText',
    notesLocalKey: 'armorSpecialFall2015MageNotes',
    value: 90,
    int: 9,
  },
  fall2015Healer: {
    event: EVENTS.fall2015,
    specialClass: 'healer',
    text: t('armorSpecialFall2015HealerText'),
    notes: t('armorSpecialFall2015HealerNotes', { con: 15 }),
    textlocaleKey: 'armorSpecialFall2015HealerText',
    notesLocalKey: 'armorSpecialFall2015HealerNotes',
    value: 90,
    con: 15,
  },
  gaymerx: {
    event: EVENTS.gaymerx,
    text: t('armorSpecialGaymerxText'),
    notes: t('armorSpecialGaymerxNotes'),
    textlocaleKey: 'armorSpecialGaymerxText',
    notesLocalKey: 'armorSpecialGaymerxNotes',
    value: 0,
  },
  winter2016Rogue: {
    event: EVENTS.winter2016,
    specialClass: 'rogue',
    text: t('armorSpecialWinter2016RogueText'),
    notes: t('armorSpecialWinter2016RogueNotes', { per: 15 }),
    textlocaleKey: 'armorSpecialWinter2016RogueText',
    notesLocalKey: 'armorSpecialWinter2016RogueNotes',
    value: 90,
    per: 15,
    canBuy: () => {
      return true;
    },
  },
  winter2016Warrior: {
    event: EVENTS.winter2016,
    specialClass: 'warrior',
    text: t('armorSpecialWinter2016WarriorText'),
    notes: t('armorSpecialWinter2016WarriorNotes', { con: 9 }),
    textlocaleKey: 'armorSpecialWinter2016WarriorText',
    notesLocalKey: 'armorSpecialWinter2016WarriorNotes',
    value: 90,
    con: 9,
    canBuy: () => {
      return true;
    },
  },
  winter2016Mage: {
    event: EVENTS.winter2016,
    specialClass: 'wizard',
    text: t('armorSpecialWinter2016MageText'),
    notes: t('armorSpecialWinter2016MageNotes', { int: 9 }),
    textlocaleKey: 'armorSpecialWinter2016MageText',
    notesLocalKey: 'armorSpecialWinter2016MageNotes',
    value: 90,
    int: 9,
    canBuy: () => {
      return true;
    },
  },
  winter2016Healer: {
    event: EVENTS.winter2016,
    specialClass: 'healer',
    text: t('armorSpecialWinter2016HealerText'),
    notes: t('armorSpecialWinter2016HealerNotes', { con: 15 }),
    textlocaleKey: 'armorSpecialWinter2016HealerText',
    notesLocalKey: 'armorSpecialWinter2016HealerNotes',
    value: 90,
    con: 15,
    canBuy: () => {
      return true;
    },
  },
  birthday2016: {
    text: t('armorSpecialBirthday2016Text'),
    notes: t('armorSpecialBirthday2016Notes'),
    textlocaleKey: 'armorSpecialBirthday2016Text',
    notesLocalKey: 'armorSpecialBirthday2016Notes',
    value: 0,
    canOwn: ownsItem('armor_special_birthday2016'),
  },
  spring2016Rogue: {
    event: EVENTS.spring2016,
    specialClass: 'rogue',
    text: t('armorSpecialSpring2016RogueText'),
    notes: t('armorSpecialSpring2016RogueNotes', { per: 15 }),
    textlocaleKey: 'armorSpecialSpring2016RogueText',
    notesLocalKey: 'armorSpecialSpring2016RogueNotes',
    value: 90,
    per: 15,
  },
  spring2016Warrior: {
    event: EVENTS.spring2016,
    specialClass: 'warrior',
    text: t('armorSpecialSpring2016WarriorText'),
    notes: t('armorSpecialSpring2016WarriorNotes', { con: 9 }),
    textlocaleKey: 'armorSpecialSpring2016WarriorText',
    notesLocalKey: 'armorSpecialSpring2016WarriorNotes',
    value: 90,
    con: 9,
  },
  spring2016Mage: {
    event: EVENTS.spring2016,
    specialClass: 'wizard',
    text: t('armorSpecialSpring2016MageText'),
    notes: t('armorSpecialSpring2016MageNotes', { int: 9 }),
    textlocaleKey: 'armorSpecialSpring2016MageText',
    notesLocalKey: 'armorSpecialSpring2016MageNotes',
    value: 90,
    int: 9,
  },
  spring2016Healer: {
    event: EVENTS.spring2016,
    specialClass: 'healer',
    text: t('armorSpecialSpring2016HealerText'),
    notes: t('armorSpecialSpring2016HealerNotes', { con: 15 }),
    textlocaleKey: 'armorSpecialSpring2016HealerText',
    notesLocalKey: 'armorSpecialSpring2016HealerNotes',
    value: 90,
    con: 15,
  },
  summer2016Rogue: {
    event: EVENTS.summer2016,
    specialClass: 'rogue',
    text: t('armorSpecialSummer2016RogueText'),
    notes: t('armorSpecialSummer2016RogueNotes', { per: 15 }),
    textlocaleKey: 'armorSpecialSummer2016RogueText',
    notesLocalKey: 'armorSpecialSummer2016RogueNotes',
    value: 90,
    per: 15,
  },
  summer2016Warrior: {
    event: EVENTS.summer2016,
    specialClass: 'warrior',
    text: t('armorSpecialSummer2016WarriorText'),
    notes: t('armorSpecialSummer2016WarriorNotes', { con: 9 }),
    textlocaleKey: 'armorSpecialSummer2016WarriorText',
    notesLocalKey: 'armorSpecialSummer2016WarriorNotes',
    value: 90,
    con: 9,
  },
  summer2016Mage: {
    event: EVENTS.summer2016,
    specialClass: 'wizard',
    text: t('armorSpecialSummer2016MageText'),
    notes: t('armorSpecialSummer2016MageNotes', { int: 9 }),
    textlocaleKey: 'armorSpecialSummer2016MageText',
    notesLocalKey: 'armorSpecialSummer2016MageNotes',
    value: 90,
    int: 9,
  },
  summer2016Healer: {
    event: EVENTS.summer2016,
    specialClass: 'healer',
    text: t('armorSpecialSummer2016HealerText'),
    notes: t('armorSpecialSummer2016HealerNotes', { con: 15 }),
    textlocaleKey: 'armorSpecialSummer2016HealerText',
    notesLocalKey: 'armorSpecialSummer2016HealerNotes',
    value: 90,
    con: 15,
  },
  fall2016Rogue: {
    event: EVENTS.fall2016,
    specialClass: 'rogue',
    text: t('armorSpecialFall2016RogueText'),
    notes: t('armorSpecialFall2016RogueNotes', { per: 15 }),
    textlocaleKey: 'armorSpecialFall2016RogueText',
    notesLocalKey: 'armorSpecialFall2016RogueNotes',
    value: 90,
    per: 15,
  },
  fall2016Warrior: {
    event: EVENTS.fall2016,
    specialClass: 'warrior',
    text: t('armorSpecialFall2016WarriorText'),
    notes: t('armorSpecialFall2016WarriorNotes', { con: 9 }),
    textlocaleKey: 'armorSpecialFall2016WarriorText',
    notesLocalKey: 'armorSpecialFall2016WarriorNotes',
    value: 90,
    con: 9,
  },
  fall2016Mage: {
    event: EVENTS.fall2016,
    specialClass: 'wizard',
    text: t('armorSpecialFall2016MageText'),
    notes: t('armorSpecialFall2016MageNotes', { int: 9 }),
    textlocaleKey: 'armorSpecialFall2016MageText',
    notesLocalKey: 'armorSpecialFall2016MageNotes',
    value: 90,
    int: 9,
  },
  fall2016Healer: {
    event: EVENTS.fall2016,
    specialClass: 'healer',
    text: t('armorSpecialFall2016HealerText'),
    notes: t('armorSpecialFall2016HealerNotes', { con: 15 }),
    textlocaleKey: 'armorSpecialFall2016HealerText',
    notesLocalKey: 'armorSpecialFall2016HealerNotes',
    value: 90,
    con: 15,
  },
  winter2017Rogue: {
    event: EVENTS.winter2017,
    specialClass: 'rogue',
    text: t('armorSpecialWinter2017RogueText'),
    notes: t('armorSpecialWinter2017RogueNotes', { per: 15 }),
    textlocaleKey: 'armorSpecialWinter2017RogueText',
    notesLocalKey: 'armorSpecialWinter2017RogueNotes',
    value: 90,
    per: 15,
  },
  winter2017Warrior: {
    event: EVENTS.winter2017,
    specialClass: 'warrior',
    text: t('armorSpecialWinter2017WarriorText'),
    notes: t('armorSpecialWinter2017WarriorNotes', { con: 9 }),
    textlocaleKey: 'armorSpecialWinter2017WarriorText',
    notesLocalKey: 'armorSpecialWinter2017WarriorNotes',
    value: 90,
    con: 9,
  },
  winter2017Mage: {
    event: EVENTS.winter2017,
    specialClass: 'wizard',
    text: t('armorSpecialWinter2017MageText'),
    notes: t('armorSpecialWinter2017MageNotes', { int: 9 }),
    textlocaleKey: 'armorSpecialWinter2017MageText',
    notesLocalKey: 'armorSpecialWinter2017MageNotes',
    value: 90,
    int: 9,
  },
  winter2017Healer: {
    event: EVENTS.winter2017,
    specialClass: 'healer',
    text: t('armorSpecialWinter2017HealerText'),
    notes: t('armorSpecialWinter2017HealerNotes', { con: 15 }),
    textlocaleKey: 'armorSpecialWinter2017HealerText',
    notesLocalKey: 'armorSpecialWinter2017HealerNotes',
    value: 90,
    con: 15,
  },
  birthday2017: {
    text: t('armorSpecialBirthday2017Text'),
    notes: t('armorSpecialBirthday2017Notes'),
    textlocaleKey: 'armorSpecialBirthday2017Text',
    notesLocalKey: 'armorSpecialBirthday2017Notes',
    value: 0,
    canOwn: ownsItem('armor_special_birthday2017'),
  },
};

let back = {
  wondercon_red: wonderconGear.backSpecialWonderconRed,  // eslint-disable-line camelcase
  wondercon_black: wonderconGear.backSpecialWonderconBlack,  // eslint-disable-line camelcase
  takeThis: takeThisGear.backSpecialTakeThis,
};

let body = {
  wondercon_red: wonderconGear.bodySpecialWonderconRed,  // eslint-disable-line camelcase
  wondercon_gold: wonderconGear.bodySpecialWonderconGold,  // eslint-disable-line camelcase
  wondercon_black: wonderconGear.bodySpecialWonderconBlack,  // eslint-disable-line camelcase
  takeThis: takeThisGear.bodySpecialTakeThis,
  summerHealer: {
    event: EVENTS.summer,
    specialClass: 'healer',
    text: t('bodySpecialSummerHealerText'),
    notes: t('bodySpecialSummerHealerNotes'),
    textlocaleKey: 'bodySpecialSummerHealerText',
    notesLocalKey: 'bodySpecialSummerHealerNotes',
    value: 20,
  },
  summerMage: {
    event: EVENTS.summer,
    specialClass: 'wizard',
    text: t('bodySpecialSummerMageText'),
    notes: t('bodySpecialSummerMageNotes'),
    textlocaleKey: 'bodySpecialSummerMageText',
    notesLocalKey: 'bodySpecialSummerMageNotes',
    value: 20,
  },
  summer2015Healer: {
    event: EVENTS.summer2015,
    specialClass: 'healer',
    text: t('bodySpecialSummer2015HealerText'),
    notes: t('bodySpecialSummer2015HealerNotes'),
    textlocaleKey: 'bodySpecialSummer2015HealerText',
    notesLocalKey: 'bodySpecialSummer2015HealerNotes',
    value: 20,
  },
  summer2015Mage: {
    event: EVENTS.summer2015,
    specialClass: 'wizard',
    text: t('bodySpecialSummer2015MageText'),
    notes: t('bodySpecialSummer2015MageNotes'),
    textlocaleKey: 'bodySpecialSummer2015MageText',
    notesLocalKey: 'bodySpecialSummer2015MageNotes',
    value: 20,
  },
  summer2015Rogue: {
    event: EVENTS.summer2015,
    specialClass: 'rogue',
    text: t('bodySpecialSummer2015RogueText'),
    notes: t('bodySpecialSummer2015RogueNotes'),
    textlocaleKey: 'bodySpecialSummer2015RogueText',
    notesLocalKey: 'bodySpecialSummer2015RogueNotes',
    value: 20,
  },
  summer2015Warrior: {
    event: EVENTS.summer2015,
    specialClass: 'warrior',
    text: t('bodySpecialSummer2015WarriorText'),
    notes: t('bodySpecialSummer2015WarriorNotes'),
    textlocaleKey: 'bodySpecialSummer2015WarriorText',
    notesLocalKey: 'bodySpecialSummer2015WarriorNotes',
    value: 20,
  },
};

let eyewear = {
  wondercon_red: wonderconGear.eyewearSpecialWonderconRed,  // eslint-disable-line camelcase
  wondercon_black: wonderconGear.eyewearSpecialWonderconBlack,  // eslint-disable-line camelcase
  summerRogue: {
    event: EVENTS.summer,
    specialClass: 'rogue',
    text: t('eyewearSpecialSummerRogueText'),
    notes: t('eyewearSpecialSummerRogueNotes'),
    textlocaleKey: 'eyewearSpecialSummerRogueText',
    notesLocalKey: 'eyewearSpecialSummerRogueNotes',
    value: 20,
  },
  summerWarrior: {
    event: EVENTS.summer,
    specialClass: 'warrior',
    text: t('eyewearSpecialSummerWarriorText'),
    notes: t('eyewearSpecialSummerWarriorNotes'),
    textlocaleKey: 'eyewearSpecialSummerWarriorText',
    notesLocalKey: 'eyewearSpecialSummerWarriorNotes',
    value: 20,
  },
  blackTopFrame: {
    gearSet: 'glasses',
    text: t('eyewearSpecialBlackTopFrameText'),
    notes: t('eyewearSpecialBlackTopFrameNotes'),
    textlocaleKey: 'eyewearSpecialBlackTopFrameText',
    notesLocalKey: 'eyewearSpecialBlackTopFrameNotes',
    value: 0,
    canOwn: ownsItem('eyewear_special_blackTopFrame'),
  },
  blueTopFrame: {
    gearSet: 'glasses',
    text: t('eyewearSpecialBlueTopFrameText'),
    notes: t('eyewearSpecialBlueTopFrameNotes'),
    textlocaleKey: 'eyewearSpecialBlueTopFrameText',
    notesLocalKey: 'eyewearSpecialBlueTopFrameNotes',
    value: 0,
    canOwn: ownsItem('eyewear_special_blueTopFrame'),
  },
  greenTopFrame: {
    gearSet: 'glasses',
    text: t('eyewearSpecialGreenTopFrameText'),
    notes: t('eyewearSpecialGreenTopFrameNotes'),
    textlocaleKey: 'eyewearSpecialGreenTopFrameText',
    notesLocalKey: 'eyewearSpecialGreenTopFrameNotes',
    value: 0,
    canOwn: ownsItem('eyewear_special_greenTopFrame'),
  },
  pinkTopFrame: {
    gearSet: 'glasses',
    text: t('eyewearSpecialPinkTopFrameText'),
    notes: t('eyewearSpecialPinkTopFrameNotes'),
    textlocaleKey: 'eyewearSpecialPinkTopFrameText',
    notesLocalKey: 'eyewearSpecialPinkTopFrameNotes',
    value: 0,
    canOwn: ownsItem('eyewear_special_pinkTopFrame'),
  },
  redTopFrame: {
    gearSet: 'glasses',
    text: t('eyewearSpecialRedTopFrameText'),
    notes: t('eyewearSpecialRedTopFrameNotes'),
    textlocaleKey: 'eyewearSpecialRedTopFrameText',
    notesLocalKey: 'eyewearSpecialRedTopFrameNotes',
    value: 0,
    canOwn: ownsItem('eyewear_special_redTopFrame'),
  },
  whiteTopFrame: {
    gearSet: 'glasses',
    text: t('eyewearSpecialWhiteTopFrameText'),
    notes: t('eyewearSpecialWhiteTopFrameNotes'),
    textlocaleKey: 'eyewearSpecialWhiteTopFrameText',
    notesLocalKey: 'eyewearSpecialWhiteTopFrameNotes',
    value: 0,
    canOwn: ownsItem('eyewear_special_whiteTopFrame'),
  },
  yellowTopFrame: {
    gearSet: 'glasses',
    text: t('eyewearSpecialYellowTopFrameText'),
    notes: t('eyewearSpecialYellowTopFrameNotes'),
    textlocaleKey: 'eyewearSpecialYellowTopFrameText',
    notesLocalKey: 'eyewearSpecialYellowTopFrameNotes',
    value: 0,
    canOwn: ownsItem('eyewear_special_yellowTopFrame'),
  },
};

let head = {
  0: backerGear.headSpecial0,
  1: contributorGear.headSpecial1,
  2: backerGear.headSpecial2,
  takeThis: takeThisGear.headSpecialTakeThis,
  fireCoralCirclet: {
    text: t('headSpecialFireCoralCircletText'),
    notes: t('headSpecialFireCoralCircletNotes', { per: 15 }),
    textlocaleKey: 'headSpecialFireCoralCircletText',
    notesLocalKey: 'headSpecialFireCoralCircletNotes',
    per: 15,
    value: 130,
    canOwn: ownsItem('head_special_fireCoralCirclet'),
  },
  pyromancersTurban: {
    text: t('headSpecialPyromancersTurbanText'),
    notes: t('headSpecialPyromancersTurbanNotes', { str: 15 }),
    textlocaleKey: 'headSpecialPyromancersTurbanText',
    notesLocalKey: 'headSpecialPyromancersTurbanNotes',
    str: 15,
    value: 130,
    canOwn: ownsItem('head_special_pyromancersTurban'),
  },
  bardHat: {
    text: t('headSpecialBardHatText'),
    notes: t('headSpecialBardHatNotes', { int: 3 }),
    textlocaleKey: 'headSpecialBardHatText',
    notesLocalKey: 'headSpecialBardHatNotes',
    int: 3,
    value: 0,
    canOwn: ownsItem('head_special_bardHat'),
  },
  lunarWarriorHelm: {
    text: t('headSpecialLunarWarriorHelmText'),
    notes: t('headSpecialLunarWarriorHelmNotes', { attrs: 7 }),
    textlocaleKey: 'headSpecialLunarWarriorHelmText',
    notesLocalKey: 'headSpecialLunarWarriorHelmNotes',
    int: 7,
    str: 7,
    value: 130,
    canOwn: ownsItem('head_special_lunarWarriorHelm'),
  },
  mammothRiderHelm: {
    text: t('headSpecialMammothRiderHelmText'),
    notes: t('headSpecialMammothRiderHelmNotes', { per: 15 }),
    textlocaleKey: 'headSpecialMammothRiderHelmText',
    notesLocalKey: 'headSpecialMammothRiderHelmNotes',
    per: 15,
    value: 130,
    canOwn: ownsItem('head_special_mammothRiderHelm'),
  },
  pageHelm: {
    text: t('headSpecialPageHelmText'),
    notes: t('headSpecialPageHelmNotes', { per: 16 }),
    textlocaleKey: 'headSpecialPageHelmText',
    notesLocalKey: 'headSpecialPageHelmNotes',
    per: 16,
    value: 0,
    canOwn: ownsItem('head_special_pageHelm'),
  },
  nye: {
    event: EVENTS.nye,
    text: t('headSpecialNyeText'),
    notes: t('headSpecialNyeNotes'),
    textlocaleKey: 'headSpecialNyeText',
    notesLocalKey: 'headSpecialNyeNotes',
    value: 0,
    canOwn: ownsItem('head_special_nye'),
  },
  yeti: {
    event: EVENTS.winter,
    specialClass: 'warrior',
    text: t('headSpecialYetiText'),
    notes: t('headSpecialYetiNotes', { str: 9 }),
    textlocaleKey: 'headSpecialYetiText',
    notesLocalKey: 'headSpecialYetiNotes',
    str: 9,
    value: 60,
    canBuy: () => {
      return true;
    },
  },
  ski: {
    event: EVENTS.winter,
    specialClass: 'rogue',
    text: t('headSpecialSkiText'),
    notes: t('headSpecialSkiNotes', { per: 9 }),
    textlocaleKey: 'headSpecialSkiText',
    notesLocalKey: 'headSpecialSkiNotes',
    per: 9,
    value: 60,
    canBuy: () => {
      return true;
    },
  },
  candycane: {
    event: EVENTS.winter,
    specialClass: 'wizard',
    text: t('headSpecialCandycaneText'),
    notes: t('headSpecialCandycaneNotes', { per: 7 }),
    textlocaleKey: 'headSpecialCandycaneText',
    notesLocalKey: 'headSpecialCandycaneNotes',
    per: 7,
    value: 60,
    canBuy: () => {
      return true;
    },
  },
  snowflake: {
    event: EVENTS.winter,
    specialClass: 'healer',
    text: t('headSpecialSnowflakeText'),
    notes: t('headSpecialSnowflakeNotes', { int: 7 }),
    textlocaleKey: 'headSpecialSnowflakeText',
    notesLocalKey: 'headSpecialSnowflakeNotes',
    int: 7,
    value: 60,
    canBuy: () => {
      return true;
    },
  },
  springRogue: {
    event: EVENTS.spring,
    specialClass: 'rogue',
    text: t('headSpecialSpringRogueText'),
    notes: t('headSpecialSpringRogueNotes', { per: 9 }),
    textlocaleKey: 'headSpecialSpringRogueText',
    notesLocalKey: 'headSpecialSpringRogueNotes',
    value: 60,
    per: 9,
  },
  springWarrior: {
    event: EVENTS.spring,
    specialClass: 'warrior',
    text: t('headSpecialSpringWarriorText'),
    notes: t('headSpecialSpringWarriorNotes', { str: 9 }),
    textlocaleKey: 'headSpecialSpringWarriorText',
    notesLocalKey: 'headSpecialSpringWarriorNotes',
    value: 60,
    str: 9,
  },
  springMage: {
    event: EVENTS.spring,
    specialClass: 'wizard',
    text: t('headSpecialSpringMageText'),
    notes: t('headSpecialSpringMageNotes', { per: 7 }),
    textlocaleKey: 'headSpecialSpringMageText',
    notesLocalKey: 'headSpecialSpringMageNotes',
    value: 60,
    per: 7,
  },
  springHealer: {
    event: EVENTS.spring,
    specialClass: 'healer',
    text: t('headSpecialSpringHealerText'),
    notes: t('headSpecialSpringHealerNotes', { int: 7 }),
    textlocaleKey: 'headSpecialSpringHealerText',
    notesLocalKey: 'headSpecialSpringHealerNotes',
    value: 60,
    int: 7,
  },
  summerRogue: {
    event: EVENTS.summer,
    specialClass: 'rogue',
    text: t('headSpecialSummerRogueText'),
    notes: t('headSpecialSummerRogueNotes', { per: 9 }),
    textlocaleKey: 'headSpecialSummerRogueText',
    notesLocalKey: 'headSpecialSummerRogueNotes',
    value: 60,
    per: 9,
  },
  summerWarrior: {
    event: EVENTS.summer,
    specialClass: 'warrior',
    text: t('headSpecialSummerWarriorText'),
    notes: t('headSpecialSummerWarriorNotes', { str: 9 }),
    textlocaleKey: 'headSpecialSummerWarriorText',
    notesLocalKey: 'headSpecialSummerWarriorNotes',
    value: 60,
    str: 9,
  },
  summerMage: {
    event: EVENTS.summer,
    specialClass: 'wizard',
    text: t('headSpecialSummerMageText'),
    notes: t('headSpecialSummerMageNotes', { per: 7 }),
    textlocaleKey: 'headSpecialSummerMageText',
    notesLocalKey: 'headSpecialSummerMageNotes',
    value: 60,
    per: 7,
  },
  summerHealer: {
    event: EVENTS.summer,
    specialClass: 'healer',
    text: t('headSpecialSummerHealerText'),
    notes: t('headSpecialSummerHealerNotes', { int: 7 }),
    textlocaleKey: 'headSpecialSummerHealerText',
    notesLocalKey: 'headSpecialSummerHealerNotes',
    value: 60,
    int: 7,
  },
  fallRogue: {
    event: EVENTS.fall,
    specialClass: 'rogue',
    text: t('headSpecialFallRogueText'),
    notes: t('headSpecialFallRogueNotes', { per: 9 }),
    textlocaleKey: 'headSpecialFallRogueText',
    notesLocalKey: 'headSpecialFallRogueNotes',
    value: 60,
    per: 9,
  },
  fallWarrior: {
    event: EVENTS.fall,
    specialClass: 'warrior',
    text: t('headSpecialFallWarriorText'),
    notes: t('headSpecialFallWarriorNotes', { str: 9 }),
    textlocaleKey: 'headSpecialFallWarriorText',
    notesLocalKey: 'headSpecialFallWarriorNotes',
    value: 60,
    str: 9,
  },
  fallMage: {
    event: EVENTS.fall,
    specialClass: 'wizard',
    text: t('headSpecialFallMageText'),
    notes: t('headSpecialFallMageNotes', { per: 7 }),
    textlocaleKey: 'headSpecialFallMageText',
    notesLocalKey: 'headSpecialFallMageNotes',
    value: 60,
    per: 7,
  },
  fallHealer: {
    event: EVENTS.fall,
    specialClass: 'healer',
    text: t('headSpecialFallHealerText'),
    notes: t('headSpecialFallHealerNotes', { int: 7 }),
    textlocaleKey: 'headSpecialFallHealerText',
    notesLocalKey: 'headSpecialFallHealerNotes',
    value: 60,
    int: 7,
  },
  winter2015Rogue: {
    event: EVENTS.winter2015,
    specialClass: 'rogue',
    text: t('headSpecialWinter2015RogueText'),
    notes: t('headSpecialWinter2015RogueNotes', { per: 9 }),
    textlocaleKey: 'headSpecialWinter2015RogueText',
    notesLocalKey: 'headSpecialWinter2015RogueNotes',
    value: 60,
    per: 9,
    canBuy: () => {
      return true;
    },
  },
  winter2015Warrior: {
    event: EVENTS.winter2015,
    specialClass: 'warrior',
    text: t('headSpecialWinter2015WarriorText'),
    notes: t('headSpecialWinter2015WarriorNotes', { str: 9 }),
    textlocaleKey: 'headSpecialWinter2015WarriorText',
    notesLocalKey: 'headSpecialWinter2015WarriorNotes',
    value: 60,
    str: 9,
    canBuy: () => {
      return true;
    },
  },
  winter2015Mage: {
    event: EVENTS.winter2015,
    specialClass: 'wizard',
    text: t('headSpecialWinter2015MageText'),
    notes: t('headSpecialWinter2015MageNotes', { per: 7 }),
    textlocaleKey: 'headSpecialWinter2015MageText',
    notesLocalKey: 'headSpecialWinter2015MageNotes',
    value: 60,
    per: 7,
    canBuy: () => {
      return true;
    },
  },
  winter2015Healer: {
    event: EVENTS.winter2015,
    specialClass: 'healer',
    text: t('headSpecialWinter2015HealerText'),
    notes: t('headSpecialWinter2015HealerNotes', { int: 7 }),
    textlocaleKey: 'headSpecialWinter2015HealerText',
    notesLocalKey: 'headSpecialWinter2015HealerNotes',
    value: 60,
    int: 7,
    canBuy: () => {
      return true;
    },
  },
  nye2014: {
    text: t('headSpecialNye2014Text'),
    notes: t('headSpecialNye2014Notes'),
    textlocaleKey: 'headSpecialNye2014Text',
    notesLocalKey: 'headSpecialNye2014Notes',
    value: 0,
    canOwn: ownsItem('head_special_nye2014'),
  },
  spring2015Rogue: {
    event: EVENTS.spring2015,
    specialClass: 'rogue',
    text: t('headSpecialSpring2015RogueText'),
    notes: t('headSpecialSpring2015RogueNotes', { per: 9 }),
    textlocaleKey: 'headSpecialSpring2015RogueText',
    notesLocalKey: 'headSpecialSpring2015RogueNotes',
    value: 60,
    per: 9,
  },
  spring2015Warrior: {
    event: EVENTS.spring2015,
    specialClass: 'warrior',
    text: t('headSpecialSpring2015WarriorText'),
    notes: t('headSpecialSpring2015WarriorNotes', { str: 9 }),
    textlocaleKey: 'headSpecialSpring2015WarriorText',
    notesLocalKey: 'headSpecialSpring2015WarriorNotes',
    value: 60,
    str: 9,
  },
  spring2015Mage: {
    event: EVENTS.spring2015,
    specialClass: 'wizard',
    text: t('headSpecialSpring2015MageText'),
    notes: t('headSpecialSpring2015MageNotes', { per: 7 }),
    textlocaleKey: 'headSpecialSpring2015MageText',
    notesLocalKey: 'headSpecialSpring2015MageNotes',
    value: 60,
    per: 7,
  },
  spring2015Healer: {
    event: EVENTS.spring2015,
    specialClass: 'healer',
    text: t('headSpecialSpring2015HealerText'),
    notes: t('headSpecialSpring2015HealerNotes', { int: 7 }),
    textlocaleKey: 'headSpecialSpring2015HealerText',
    notesLocalKey: 'headSpecialSpring2015HealerNotes',
    value: 60,
    int: 7,
  },
  summer2015Rogue: {
    event: EVENTS.summer2015,
    specialClass: 'rogue',
    text: t('headSpecialSummer2015RogueText'),
    notes: t('headSpecialSummer2015RogueNotes', { per: 9 }),
    textlocaleKey: 'headSpecialSummer2015RogueText',
    notesLocalKey: 'headSpecialSummer2015RogueNotes',
    value: 60,
    per: 9,
  },
  summer2015Warrior: {
    event: EVENTS.summer2015,
    specialClass: 'warrior',
    text: t('headSpecialSummer2015WarriorText'),
    notes: t('headSpecialSummer2015WarriorNotes', { str: 9 }),
    textlocaleKey: 'headSpecialSummer2015WarriorText',
    notesLocalKey: 'headSpecialSummer2015WarriorNotes',
    value: 60,
    str: 9,
  },
  summer2015Mage: {
    event: EVENTS.summer2015,
    specialClass: 'wizard',
    text: t('headSpecialSummer2015MageText'),
    notes: t('headSpecialSummer2015MageNotes', { per: 7 }),
    textlocaleKey: 'headSpecialSummer2015MageText',
    notesLocalKey: 'headSpecialSummer2015MageNotes',
    value: 60,
    per: 7,
  },
  summer2015Healer: {
    event: EVENTS.summer2015,
    specialClass: 'healer',
    text: t('headSpecialSummer2015HealerText'),
    notes: t('headSpecialSummer2015HealerNotes', { int: 7 }),
    textlocaleKey: 'headSpecialSummer2015HealerText',
    notesLocalKey: 'headSpecialSummer2015HealerNotes',
    value: 60,
    int: 7,
  },
  fall2015Rogue: {
    event: EVENTS.fall2015,
    specialClass: 'rogue',
    text: t('headSpecialFall2015RogueText'),
    notes: t('headSpecialFall2015RogueNotes', { per: 9 }),
    textlocaleKey: 'headSpecialFall2015RogueText',
    notesLocalKey: 'headSpecialFall2015RogueNotes',
    value: 60,
    per: 9,
  },
  fall2015Warrior: {
    event: EVENTS.fall2015,
    specialClass: 'warrior',
    text: t('headSpecialFall2015WarriorText'),
    notes: t('headSpecialFall2015WarriorNotes', { str: 9 }),
    textlocaleKey: 'headSpecialFall2015WarriorText',
    notesLocalKey: 'headSpecialFall2015WarriorNotes',
    value: 60,
    str: 9,
  },
  fall2015Mage: {
    event: EVENTS.fall2015,
    specialClass: 'wizard',
    text: t('headSpecialFall2015MageText'),
    notes: t('headSpecialFall2015MageNotes', { per: 7 }),
    textlocaleKey: 'headSpecialFall2015MageText',
    notesLocalKey: 'headSpecialFall2015MageNotes',
    value: 60,
    per: 7,
  },
  fall2015Healer: {
    event: EVENTS.fall2015,
    specialClass: 'healer',
    text: t('headSpecialFall2015HealerText'),
    notes: t('headSpecialFall2015HealerNotes', { int: 7 }),
    textlocaleKey: 'headSpecialFall2015HealerText',
    notesLocalKey: 'headSpecialFall2015HealerNotes',
    value: 60,
    int: 7,
  },
  gaymerx: {
    event: EVENTS.gaymerx,
    text: t('headSpecialGaymerxText'),
    notes: t('headSpecialGaymerxNotes'),
    textlocaleKey: 'headSpecialGaymerxText',
    notesLocalKey: 'headSpecialGaymerxNotes',
    value: 0,
  },
  winter2016Rogue: {
    event: EVENTS.winter2016,
    specialClass: 'rogue',
    text: t('headSpecialWinter2016RogueText'),
    notes: t('headSpecialWinter2016RogueNotes', { per: 9 }),
    textlocaleKey: 'headSpecialWinter2016RogueText',
    notesLocalKey: 'headSpecialWinter2016RogueNotes',
    value: 60,
    per: 9,
    canBuy: () => {
      return true;
    },
  },
  winter2016Warrior: {
    event: EVENTS.winter2016,
    specialClass: 'warrior',
    text: t('headSpecialWinter2016WarriorText'),
    notes: t('headSpecialWinter2016WarriorNotes', { str: 9 }),
    textlocaleKey: 'headSpecialWinter2016WarriorText',
    notesLocalKey: 'headSpecialWinter2016WarriorNotes',
    value: 60,
    str: 9,
    canBuy: () => {
      return true;
    },
  },
  winter2016Mage: {
    event: EVENTS.winter2016,
    specialClass: 'wizard',
    text: t('headSpecialWinter2016MageText'),
    notes: t('headSpecialWinter2016MageNotes', { per: 7 }),
    textlocaleKey: 'headSpecialWinter2016MageText',
    notesLocalKey: 'headSpecialWinter2016MageNotes',
    value: 60,
    per: 7,
    canBuy: () => {
      return true;
    },
  },
  winter2016Healer: {
    event: EVENTS.winter2016,
    specialClass: 'healer',
    text: t('headSpecialWinter2016HealerText'),
    notes: t('headSpecialWinter2016HealerNotes', { int: 7 }),
    textlocaleKey: 'headSpecialWinter2016HealerText',
    notesLocalKey: 'headSpecialWinter2016HealerNotes',
    value: 60,
    int: 7,
    canBuy: () => {
      return true;
    },
  },
  nye2015: {
    text: t('headSpecialNye2015Text'),
    notes: t('headSpecialNye2015Notes'),
    textlocaleKey: 'headSpecialNye2015Text',
    notesLocalKey: 'headSpecialNye2015Notes',
    value: 0,
    canOwn: ownsItem('head_special_nye2015'),
  },
  spring2016Rogue: {
    event: EVENTS.spring2016,
    specialClass: 'rogue',
    text: t('headSpecialSpring2016RogueText'),
    notes: t('headSpecialSpring2016RogueNotes', { per: 9 }),
    textlocaleKey: 'headSpecialSpring2016RogueText',
    notesLocalKey: 'headSpecialSpring2016RogueNotes',
    value: 60,
    per: 9,
  },
  spring2016Warrior: {
    event: EVENTS.spring2016,
    specialClass: 'warrior',
    text: t('headSpecialSpring2016WarriorText'),
    notes: t('headSpecialSpring2016WarriorNotes', { str: 9 }),
    textlocaleKey: 'headSpecialSpring2016WarriorText',
    notesLocalKey: 'headSpecialSpring2016WarriorNotes',
    value: 60,
    str: 9,
  },
  spring2016Mage: {
    event: EVENTS.spring2016,
    specialClass: 'wizard',
    text: t('headSpecialSpring2016MageText'),
    notes: t('headSpecialSpring2016MageNotes', { per: 7 }),
    textlocaleKey: 'headSpecialSpring2016MageText',
    notesLocalKey: 'headSpecialSpring2016MageNotes',
    value: 60,
    per: 7,
  },
  spring2016Healer: {
    event: EVENTS.spring2016,
    specialClass: 'healer',
    text: t('headSpecialSpring2016HealerText'),
    notes: t('headSpecialSpring2016HealerNotes', { int: 7 }),
    textlocaleKey: 'headSpecialSpring2016HealerText',
    notesLocalKey: 'headSpecialSpring2016HealerNotes',
    value: 60,
    int: 7,
  },
  summer2016Rogue: {
    event: EVENTS.summer2016,
    specialClass: 'rogue',
    text: t('headSpecialSummer2016RogueText'),
    notes: t('headSpecialSummer2016RogueNotes', { per: 9 }),
    textlocaleKey: 'headSpecialSummer2016RogueText',
    notesLocalKey: 'headSpecialSummer2016RogueNotes',
    value: 60,
    per: 9,
  },
  summer2016Warrior: {
    event: EVENTS.summer2016,
    specialClass: 'warrior',
    text: t('headSpecialSummer2016WarriorText'),
    notes: t('headSpecialSummer2016WarriorNotes', { str: 9 }),
    textlocaleKey: 'headSpecialSummer2016WarriorText',
    notesLocalKey: 'headSpecialSummer2016WarriorNotes',
    value: 60,
    str: 9,
  },
  summer2016Mage: {
    event: EVENTS.summer2016,
    specialClass: 'wizard',
    text: t('headSpecialSummer2016MageText'),
    notes: t('headSpecialSummer2016MageNotes', { per: 7 }),
    textlocaleKey: 'headSpecialSummer2016MageText',
    notesLocalKey: 'headSpecialSummer2016MageNotes',
    value: 60,
    per: 7,
  },
  summer2016Healer: {
    event: EVENTS.summer2016,
    specialClass: 'healer',
    text: t('headSpecialSummer2016HealerText'),
    notes: t('headSpecialSummer2016HealerNotes', { int: 7 }),
    textlocaleKey: 'headSpecialSummer2016HealerText',
    notesLocalKey: 'headSpecialSummer2016HealerNotes',
    value: 60,
    int: 7,
  },
  fall2016Rogue: {
    event: EVENTS.fall2016,
    specialClass: 'rogue',
    text: t('headSpecialFall2016RogueText'),
    notes: t('headSpecialFall2016RogueNotes', { per: 9 }),
    textlocaleKey: 'headSpecialFall2016RogueText',
    notesLocalKey: 'headSpecialFall2016RogueNotes',
    value: 60,
    per: 9,
  },
  fall2016Warrior: {
    event: EVENTS.fall2016,
    specialClass: 'warrior',
    text: t('headSpecialFall2016WarriorText'),
    notes: t('headSpecialFall2016WarriorNotes', { str: 9 }),
    textlocaleKey: 'headSpecialFall2016WarriorText',
    notesLocalKey: 'headSpecialFall2016WarriorNotes',
    value: 60,
    str: 9,
  },
  fall2016Mage: {
    event: EVENTS.fall2016,
    specialClass: 'wizard',
    text: t('headSpecialFall2016MageText'),
    notes: t('headSpecialFall2016MageNotes', { per: 7 }),
    textlocaleKey: 'headSpecialFall2016MageText',
    notesLocalKey: 'headSpecialFall2016MageNotes',
    value: 60,
    per: 7,
  },
  fall2016Healer: {
    event: EVENTS.fall2016,
    specialClass: 'healer',
    text: t('headSpecialFall2016HealerText'),
    notes: t('headSpecialFall2016HealerNotes', { int: 7 }),
    textlocaleKey: 'headSpecialFall2016HealerText',
    notesLocalKey: 'headSpecialFall2016HealerNotes',
    value: 60,
    int: 7,
  },
  winter2017Rogue: {
    event: EVENTS.winter2017,
    specialClass: 'rogue',
    text: t('headSpecialWinter2017RogueText'),
    notes: t('headSpecialWinter2017RogueNotes', { per: 9 }),
    textlocaleKey: 'headSpecialWinter2017RogueText',
    notesLocalKey: 'headSpecialWinter2017RogueNotes',
    value: 60,
    per: 9,
  },
  winter2017Warrior: {
    event: EVENTS.winter2017,
    specialClass: 'warrior',
    text: t('headSpecialWinter2017WarriorText'),
    notes: t('headSpecialWinter2017WarriorNotes', { str: 9 }),
    textlocaleKey: 'headSpecialWinter2017WarriorText',
    notesLocalKey: 'headSpecialWinter2017WarriorNotes',
    value: 60,
    str: 9,
  },
  winter2017Mage: {
    event: EVENTS.winter2017,
    specialClass: 'wizard',
    text: t('headSpecialWinter2017MageText'),
    notes: t('headSpecialWinter2017MageNotes', { per: 7 }),
    textlocaleKey: 'headSpecialWinter2017MageText',
    notesLocalKey: 'headSpecialWinter2017MageNotes',
    value: 60,
    per: 7,
  },
  winter2017Healer: {
    event: EVENTS.winter2017,
    specialClass: 'healer',
    text: t('headSpecialWinter2017HealerText'),
    notes: t('headSpecialWinter2017HealerNotes', { int: 7 }),
    textlocaleKey: 'headSpecialWinter2017HealerText',
    notesLocalKey: 'headSpecialWinter2017HealerNotes',
    value: 60,
    int: 7,
  },
  nye2016: {
    text: t('headSpecialNye2016Text'),
    notes: t('headSpecialNye2016Notes'),
    textlocaleKey: 'headSpecialNye2016Text',
    notesLocalKey: 'headSpecialNye2016Notes',
    value: 0,
    canOwn: ownsItem('head_special_nye2016'),
  },
};

let headAccessory = {
  springRogue: {
    event: EVENTS.spring,
    specialClass: 'rogue',
    text: t('headAccessorySpecialSpringRogueText'),
    notes: t('headAccessorySpecialSpringRogueNotes'),
    textlocaleKey: 'headAccessorySpecialSpringRogueText',
    notesLocalKey: 'headAccessorySpecialSpringRogueNotes',
    value: 20,
  },
  springWarrior: {
    event: EVENTS.spring,
    specialClass: 'warrior',
    text: t('headAccessorySpecialSpringWarriorText'),
    notes: t('headAccessorySpecialSpringWarriorNotes'),
    textlocaleKey: 'headAccessorySpecialSpringWarriorText',
    notesLocalKey: 'headAccessorySpecialSpringWarriorNotes',
    value: 20,
  },
  springMage: {
    event: EVENTS.spring,
    specialClass: 'wizard',
    text: t('headAccessorySpecialSpringMageText'),
    notes: t('headAccessorySpecialSpringMageNotes'),
    textlocaleKey: 'headAccessorySpecialSpringMageText',
    notesLocalKey: 'headAccessorySpecialSpringMageNotes',
    value: 20,
  },
  springHealer: {
    event: EVENTS.spring,
    specialClass: 'healer',
    text: t('headAccessorySpecialSpringHealerText'),
    notes: t('headAccessorySpecialSpringHealerNotes'),
    textlocaleKey: 'headAccessorySpecialSpringHealerText',
    notesLocalKey: 'headAccessorySpecialSpringHealerNotes',
    value: 20,
  },
  spring2015Rogue: {
    event: EVENTS.spring2015,
    specialClass: 'rogue',
    text: t('headAccessorySpecialSpring2015RogueText'),
    notes: t('headAccessorySpecialSpring2015RogueNotes'),
    textlocaleKey: 'headAccessorySpecialSpring2015RogueText',
    notesLocalKey: 'headAccessorySpecialSpring2015RogueNotes',
    value: 20,
  },
  spring2015Warrior: {
    event: EVENTS.spring2015,
    specialClass: 'warrior',
    text: t('headAccessorySpecialSpring2015WarriorText'),
    notes: t('headAccessorySpecialSpring2015WarriorNotes'),
    textlocaleKey: 'headAccessorySpecialSpring2015WarriorText',
    notesLocalKey: 'headAccessorySpecialSpring2015WarriorNotes',
    value: 20,
  },
  spring2015Mage: {
    event: EVENTS.spring2015,
    specialClass: 'wizard',
    text: t('headAccessorySpecialSpring2015MageText'),
    notes: t('headAccessorySpecialSpring2015MageNotes'),
    textlocaleKey: 'headAccessorySpecialSpring2015MageText',
    notesLocalKey: 'headAccessorySpecialSpring2015MageNotes',
    value: 20,
  },
  spring2015Healer: {
    event: EVENTS.spring2015,
    specialClass: 'healer',
    text: t('headAccessorySpecialSpring2015HealerText'),
    notes: t('headAccessorySpecialSpring2015HealerNotes'),
    textlocaleKey: 'headAccessorySpecialSpring2015HealerText',
    notesLocalKey: 'headAccessorySpecialSpring2015HealerNotes',
    value: 20,
  },
  bearEars: {
    gearSet: 'animal',
    text: t('headAccessoryBearEarsText'),
    notes: t('headAccessoryBearEarsNotes'),
    textlocaleKey: 'headAccessoryBearEarsText',
    notesLocalKey: 'headAccessoryBearEarsNotes',
    value: 20,
    canOwn: ownsItem('headAccessory_special_bearEars'),
    canBuy: () => {
      return true;
    },
  },
  cactusEars: {
    gearSet: 'animal',
    text: t('headAccessoryCactusEarsText'),
    notes: t('headAccessoryCactusEarsNotes'),
    textlocaleKey: 'headAccessoryCactusEarsText',
    notesLocalKey: 'headAccessoryCactusEarsNotes',
    value: 20,
    canOwn: ownsItem('headAccessory_special_cactusEars'),
    canBuy: () => {
      return true;
    },
  },
  foxEars: {
    gearSet: 'animal',
    text: t('headAccessoryFoxEarsText'),
    notes: t('headAccessoryFoxEarsNotes'),
    textlocaleKey: 'headAccessoryFoxEarsText',
    notesLocalKey: 'headAccessoryFoxEarsNotes',
    value: 20,
    canOwn: ownsItem('headAccessory_special_foxEars'),
    canBuy: () => {
      return true;
    },
  },
  lionEars: {
    gearSet: 'animal',
    text: t('headAccessoryLionEarsText'),
    notes: t('headAccessoryLionEarsNotes'),
    textlocaleKey: 'headAccessoryLionEarsText',
    notesLocalKey: 'headAccessoryLionEarsNotes',
    value: 20,
    canOwn: ownsItem('headAccessory_special_lionEars'),
    canBuy: () => {
      return true;
    },
  },
  pandaEars: {
    gearSet: 'animal',
    text: t('headAccessoryPandaEarsText'),
    notes: t('headAccessoryPandaEarsNotes'),
    textlocaleKey: 'headAccessoryPandaEarsText',
    notesLocalKey: 'headAccessoryPandaEarsNotes',
    value: 20,
    canOwn: ownsItem('headAccessory_special_pandaEars'),
    canBuy: () => {
      return true;
    },
  },
  pigEars: {
    gearSet: 'animal',
    text: t('headAccessoryPigEarsText'),
    notes: t('headAccessoryPigEarsNotes'),
    textlocaleKey: 'headAccessoryPigEarsText',
    notesLocalKey: 'headAccessoryPigEarsNotes',
    value: 20,
    canOwn: ownsItem('headAccessory_special_pigEars'),
    canBuy: () => {
      return true;
    },
  },
  tigerEars: {
    gearSet: 'animal',
    text: t('headAccessoryTigerEarsText'),
    notes: t('headAccessoryTigerEarsNotes'),
    textlocaleKey: 'headAccessoryTigerEarsText',
    notesLocalKey: 'headAccessoryTigerEarsNotes',
    value: 20,
    canOwn: ownsItem('headAccessory_special_tigerEars'),
    canBuy: () => {
      return true;
    },
  },
  wolfEars: {
    gearSet: 'animal',
    text: t('headAccessoryWolfEarsText'),
    notes: t('headAccessoryWolfEarsNotes'),
    textlocaleKey: 'headAccessoryWolfEarsText',
    notesLocalKey: 'headAccessoryWolfEarsNotes',
    value: 20,
    canOwn: ownsItem('headAccessory_special_wolfEars'),
    canBuy: () => {
      return true;
    },
  },
  spring2016Rogue: {
    event: EVENTS.spring2016,
    specialClass: 'rogue',
    text: t('headAccessorySpecialSpring2016RogueText'),
    notes: t('headAccessorySpecialSpring2016RogueNotes'),
    textlocaleKey: 'headAccessorySpecialSpring2016RogueText',
    notesLocalKey: 'headAccessorySpecialSpring2016RogueNotes',
    value: 20,
  },
  spring2016Warrior: {
    event: EVENTS.spring2016,
    specialClass: 'warrior',
    text: t('headAccessorySpecialSpring2016WarriorText'),
    notes: t('headAccessorySpecialSpring2016WarriorNotes'),
    textlocaleKey: 'headAccessorySpecialSpring2016WarriorText',
    notesLocalKey: 'headAccessorySpecialSpring2016WarriorNotes',
    value: 20,
  },
  spring2016Mage: {
    event: EVENTS.spring2016,
    specialClass: 'wizard',
    text: t('headAccessorySpecialSpring2016MageText'),
    notes: t('headAccessorySpecialSpring2016MageNotes'),
    textlocaleKey: 'headAccessorySpecialSpring2016MageText',
    notesLocalKey: 'headAccessorySpecialSpring2016MageNotes',
    value: 20,
  },
  spring2016Healer: {
    event: EVENTS.spring2016,
    specialClass: 'healer',
    text: t('headAccessorySpecialSpring2016HealerText'),
    notes: t('headAccessorySpecialSpring2016HealerNotes'),
    textlocaleKey: 'headAccessorySpecialSpring2016HealerText',
    notesLocalKey: 'headAccessorySpecialSpring2016HealerNotes',
    value: 20,
  },
};

let shield = {
  0: backerGear.shieldSpecial0,
  1: contributorGear.shieldSpecial1,
  takeThis: takeThisGear.shieldSpecialTakeThis,
  goldenknight: {
    text: t('shieldSpecialGoldenknightText'),
    notes: t('shieldSpecialGoldenknightNotes', { attrs: 25 }),
    textlocaleKey: 'shieldSpecialGoldenknightText',
    notesLocalKey: 'shieldSpecialGoldenknightNotes',
    con: 25,
    per: 25,
    value: 200,
    canOwn: ownsItem('shield_special_goldenknight'),
  },
  moonpearlShield: {
    text: t('shieldSpecialMoonpearlShieldText'),
    notes: t('shieldSpecialMoonpearlShieldNotes', { con: 15 }),
    textlocaleKey: 'shieldSpecialMoonpearlShieldText',
    notesLocalKey: 'shieldSpecialMoonpearlShieldNotes',
    con: 15,
    value: 130,
    canOwn: ownsItem('shield_special_moonpearlShield'),
  },
  mammothRiderHorn: {
    text: t('shieldSpecialMammothRiderHornText'),
    notes: t('shieldSpecialMammothRiderHornNotes', { str: 15 }),
    textlocaleKey: 'shieldSpecialMammothRiderHornText',
    notesLocalKey: 'shieldSpecialMammothRiderHornNotes',
    str: 15,
    value: 130,
    canOwn: ownsItem('shield_special_mammothRiderHorn'),
  },
  diamondStave: {
    text: t('shieldSpecialDiamondStaveText'),
    notes: t('shieldSpecialDiamondStaveNotes', { int: 16 }),
    textlocaleKey: 'shieldSpecialDiamondStaveText',
    notesLocalKey: 'shieldSpecialDiamondStaveNotes',
    int: 16,
    value: 0,
    canOwn: ownsItem('shield_special_diamondStave'),
  },
  yeti: {
    event: EVENTS.winter,
    specialClass: 'warrior',
    text: t('shieldSpecialYetiText'),
    notes: t('shieldSpecialYetiNotes', { con: 7 }),
    textlocaleKey: 'shieldSpecialYetiText',
    notesLocalKey: 'shieldSpecialYetiNotes',
    con: 7,
    value: 70,
    canBuy: () => {
      return true;
    },
  },
  ski: {
    event: EVENTS.winter,
    specialClass: 'rogue',
    text: t('weaponSpecialSkiText'),
    notes: t('weaponSpecialSkiNotes', { str: 8 }),
    textlocaleKey: 'weaponSpecialSkiText',
    notesLocalKey: 'weaponSpecialSkiNotes',
    str: 8,
    value: 90,
    canBuy: () => {
      return true;
    },
  },
  snowflake: {
    event: EVENTS.winter,
    specialClass: 'healer',
    text: t('shieldSpecialSnowflakeText'),
    notes: t('shieldSpecialSnowflakeNotes', { con: 9 }),
    textlocaleKey: 'shieldSpecialSnowflakeText',
    notesLocalKey: 'shieldSpecialSnowflakeNotes',
    con: 9,
    value: 70,
    canBuy: () => {
      return true;
    },
  },
  springRogue: {
    event: EVENTS.spring,
    specialClass: 'rogue',
    text: t('shieldSpecialSpringRogueText'),
    notes: t('shieldSpecialSpringRogueNotes', { str: 8 }),
    textlocaleKey: 'shieldSpecialSpringRogueText',
    notesLocalKey: 'shieldSpecialSpringRogueNotes',
    value: 80,
    str: 8,
  },
  springWarrior: {
    event: EVENTS.spring,
    specialClass: 'warrior',
    text: t('shieldSpecialSpringWarriorText'),
    notes: t('shieldSpecialSpringWarriorNotes', { con: 7 }),
    textlocaleKey: 'shieldSpecialSpringWarriorText',
    notesLocalKey: 'shieldSpecialSpringWarriorNotes',
    value: 70,
    con: 7,
  },
  springHealer: {
    event: EVENTS.spring,
    specialClass: 'healer',
    text: t('shieldSpecialSpringHealerText'),
    notes: t('shieldSpecialSpringHealerNotes', { con: 9 }),
    textlocaleKey: 'shieldSpecialSpringHealerText',
    notesLocalKey: 'shieldSpecialSpringHealerNotes',
    value: 70,
    con: 9,
  },
  summerRogue: {
    event: EVENTS.summer,
    specialClass: 'rogue',
    text: t('shieldSpecialSummerRogueText'),
    notes: t('shieldSpecialSummerRogueNotes', { str: 8 }),
    textlocaleKey: 'shieldSpecialSummerRogueText',
    notesLocalKey: 'shieldSpecialSummerRogueNotes',
    value: 80,
    str: 8,
  },
  summerWarrior: {
    event: EVENTS.summer,
    specialClass: 'warrior',
    text: t('shieldSpecialSummerWarriorText'),
    notes: t('shieldSpecialSummerWarriorNotes', { con: 7 }),
    textlocaleKey: 'shieldSpecialSummerWarriorText',
    notesLocalKey: 'shieldSpecialSummerWarriorNotes',
    value: 70,
    con: 7,
  },
  summerHealer: {
    event: EVENTS.summer,
    specialClass: 'healer',
    text: t('shieldSpecialSummerHealerText'),
    notes: t('shieldSpecialSummerHealerNotes', { con: 9 }),
    textlocaleKey: 'shieldSpecialSummerHealerText',
    notesLocalKey: 'shieldSpecialSummerHealerNotes',
    value: 70,
    con: 9,
  },
  fallRogue: {
    event: EVENTS.fall,
    specialClass: 'rogue',
    text: t('shieldSpecialFallRogueText'),
    notes: t('shieldSpecialFallRogueNotes', { str: 8 }),
    textlocaleKey: 'shieldSpecialFallRogueText',
    notesLocalKey: 'shieldSpecialFallRogueNotes',
    value: 80,
    str: 8,
  },
  fallWarrior: {
    event: EVENTS.fall,
    specialClass: 'warrior',
    text: t('shieldSpecialFallWarriorText'),
    notes: t('shieldSpecialFallWarriorNotes', { con: 7 }),
    textlocaleKey: 'shieldSpecialFallWarriorText',
    notesLocalKey: 'shieldSpecialFallWarriorNotes',
    value: 70,
    con: 7,
  },
  fallHealer: {
    event: EVENTS.fall,
    specialClass: 'healer',
    text: t('shieldSpecialFallHealerText'),
    notes: t('shieldSpecialFallHealerNotes', { con: 9 }),
    textlocaleKey: 'shieldSpecialFallHealerText',
    notesLocalKey: 'shieldSpecialFallHealerNotes',
    value: 70,
    con: 9,
  },
  winter2015Rogue: {
    event: EVENTS.winter2015,
    specialClass: 'rogue',
    text: t('shieldSpecialWinter2015RogueText'),
    notes: t('shieldSpecialWinter2015RogueNotes', { str: 8 }),
    textlocaleKey: 'shieldSpecialWinter2015RogueText',
    notesLocalKey: 'shieldSpecialWinter2015RogueNotes',
    value: 80,
    str: 8,
    canBuy: () => {
      return true;
    },
  },
  winter2015Warrior: {
    event: EVENTS.winter2015,
    specialClass: 'warrior',
    text: t('shieldSpecialWinter2015WarriorText'),
    notes: t('shieldSpecialWinter2015WarriorNotes', { con: 7 }),
    textlocaleKey: 'shieldSpecialWinter2015WarriorText',
    notesLocalKey: 'shieldSpecialWinter2015WarriorNotes',
    value: 70,
    con: 7,
    canBuy: () => {
      return true;
    },
  },
  winter2015Healer: {
    event: EVENTS.winter2015,
    specialClass: 'healer',
    text: t('shieldSpecialWinter2015HealerText'),
    notes: t('shieldSpecialWinter2015HealerNotes', { con: 9 }),
    textlocaleKey: 'shieldSpecialWinter2015HealerText',
    notesLocalKey: 'shieldSpecialWinter2015HealerNotes',
    value: 70,
    con: 9,
    canBuy: () => {
      return true;
    },
  },
  spring2015Rogue: {
    event: EVENTS.spring2015,
    specialClass: 'rogue',
    text: t('shieldSpecialSpring2015RogueText'),
    notes: t('shieldSpecialSpring2015RogueNotes', { str: 8 }),
    textlocaleKey: 'shieldSpecialSpring2015RogueText',
    notesLocalKey: 'shieldSpecialSpring2015RogueNotes',
    value: 80,
    str: 8,
  },
  spring2015Warrior: {
    event: EVENTS.spring2015,
    specialClass: 'warrior',
    text: t('shieldSpecialSpring2015WarriorText'),
    notes: t('shieldSpecialSpring2015WarriorNotes', { con: 7 }),
    textlocaleKey: 'shieldSpecialSpring2015WarriorText',
    notesLocalKey: 'shieldSpecialSpring2015WarriorNotes',
    value: 70,
    con: 7,
  },
  spring2015Healer: {
    event: EVENTS.spring2015,
    specialClass: 'healer',
    text: t('shieldSpecialSpring2015HealerText'),
    notes: t('shieldSpecialSpring2015HealerNotes', { con: 9 }),
    textlocaleKey: 'shieldSpecialSpring2015HealerText',
    notesLocalKey: 'shieldSpecialSpring2015HealerNotes',
    value: 70,
    con: 9,
  },
  summer2015Rogue: {
    event: EVENTS.summer2015,
    specialClass: 'rogue',
    text: t('shieldSpecialSummer2015RogueText'),
    notes: t('shieldSpecialSummer2015RogueNotes', { str: 8 }),
    textlocaleKey: 'shieldSpecialSummer2015RogueText',
    notesLocalKey: 'shieldSpecialSummer2015RogueNotes',
    value: 80,
    str: 8,
  },
  summer2015Warrior: {
    event: EVENTS.summer2015,
    specialClass: 'warrior',
    text: t('shieldSpecialSummer2015WarriorText'),
    notes: t('shieldSpecialSummer2015WarriorNotes', { con: 7 }),
    textlocaleKey: 'shieldSpecialSummer2015WarriorText',
    notesLocalKey: 'shieldSpecialSummer2015WarriorNotes',
    value: 70,
    con: 7,
  },
  summer2015Healer: {
    event: EVENTS.summer2015,
    specialClass: 'healer',
    text: t('shieldSpecialSummer2015HealerText'),
    notes: t('shieldSpecialSummer2015HealerNotes', { con: 9 }),
    textlocaleKey: 'shieldSpecialSummer2015HealerText',
    notesLocalKey: 'shieldSpecialSummer2015HealerNotes',
    value: 70,
    con: 9,
  },
  fall2015Rogue: {
    event: EVENTS.fall2015,
    specialClass: 'rogue',
    text: t('shieldSpecialFall2015RogueText'),
    notes: t('shieldSpecialFall2015RogueNotes', { str: 8 }),
    textlocaleKey: 'shieldSpecialFall2015RogueText',
    notesLocalKey: 'shieldSpecialFall2015RogueNotes',
    value: 80,
    str: 8,
  },
  fall2015Warrior: {
    event: EVENTS.fall2015,
    specialClass: 'warrior',
    text: t('shieldSpecialFall2015WarriorText'),
    notes: t('shieldSpecialFall2015WarriorNotes', { con: 7 }),
    textlocaleKey: 'shieldSpecialFall2015WarriorText',
    notesLocalKey: 'shieldSpecialFall2015WarriorNotes',
    value: 70,
    con: 7,
  },
  fall2015Healer: {
    event: EVENTS.fall2015,
    specialClass: 'healer',
    text: t('shieldSpecialFall2015HealerText'),
    notes: t('shieldSpecialFall2015HealerNotes', { con: 9 }),
    textlocaleKey: 'shieldSpecialFall2015HealerText',
    notesLocalKey: 'shieldSpecialFall2015HealerNotes',
    value: 70,
    con: 9,
  },
  winter2016Rogue: {
    event: EVENTS.winter2016,
    specialClass: 'rogue',
    text: t('shieldSpecialWinter2016RogueText'),
    notes: t('shieldSpecialWinter2016RogueNotes', { str: 8 }),
    textlocaleKey: 'shieldSpecialWinter2016RogueText',
    notesLocalKey: 'shieldSpecialWinter2016RogueNotes',
    value: 80,
    str: 8,
    canBuy: () => {
      return true;
    },
  },
  winter2016Warrior: {
    event: EVENTS.winter2016,
    specialClass: 'warrior',
    text: t('shieldSpecialWinter2016WarriorText'),
    notes: t('shieldSpecialWinter2016WarriorNotes', { con: 7 }),
    textlocaleKey: 'shieldSpecialWinter2016WarriorText',
    notesLocalKey: 'shieldSpecialWinter2016WarriorNotes',
    value: 70,
    con: 7,
    canBuy: () => {
      return true;
    },
  },
  winter2016Healer: {
    event: EVENTS.winter2016,
    specialClass: 'healer',
    text: t('shieldSpecialWinter2016HealerText'),
    notes: t('shieldSpecialWinter2016HealerNotes', { con: 9 }),
    textlocaleKey: 'shieldSpecialWinter2016HealerText',
    notesLocalKey: 'shieldSpecialWinter2016HealerNotes',
    value: 70,
    con: 9,
    canBuy: () => {
      return true;
    },
  },
  spring2016Rogue: {
    event: EVENTS.spring2016,
    specialClass: 'rogue',
    text: t('shieldSpecialSpring2016RogueText'),
    notes: t('shieldSpecialSpring2016RogueNotes', { str: 8 }),
    textlocaleKey: 'shieldSpecialSpring2016RogueText',
    notesLocalKey: 'shieldSpecialSpring2016RogueNotes',
    value: 80,
    str: 8,
  },
  spring2016Warrior: {
    event: EVENTS.spring2016,
    specialClass: 'warrior',
    text: t('shieldSpecialSpring2016WarriorText'),
    notes: t('shieldSpecialSpring2016WarriorNotes', { con: 7 }),
    textlocaleKey: 'shieldSpecialSpring2016WarriorText',
    notesLocalKey: 'shieldSpecialSpring2016WarriorNotes',
    value: 70,
    con: 7,
  },
  spring2016Healer: {
    event: EVENTS.spring2016,
    specialClass: 'healer',
    text: t('shieldSpecialSpring2016HealerText'),
    notes: t('shieldSpecialSpring2016HealerNotes', { con: 9 }),
    textlocaleKey: 'shieldSpecialSpring2016HealerText',
    notesLocalKey: 'shieldSpecialSpring2016HealerNotes',
    value: 70,
    con: 9,
  },
  summer2016Rogue: {
    event: EVENTS.summer2016,
    specialClass: 'rogue',
    text: t('shieldSpecialSummer2016RogueText'),
    notes: t('shieldSpecialSummer2016RogueNotes', { str: 8 }),
    textlocaleKey: 'shieldSpecialSummer2016WarriorText',
    notesLocalKey: 'shieldSpecialSummer2016WarriorNotes',
    value: 80,
    str: 8,
  },
  summer2016Warrior: {
    event: EVENTS.summer2016,
    specialClass: 'warrior',
    text: t('shieldSpecialSummer2016WarriorText'),
    notes: t('shieldSpecialSummer2016WarriorNotes', { con: 7 }),
    textlocaleKey: 'shieldSpecialSummer2016WarriorText',
    notesLocalKey: 'shieldSpecialSummer2016WarriorNotes',
    value: 70,
    con: 7,
  },
  summer2016Healer: {
    event: EVENTS.summer2016,
    specialClass: 'healer',
    text: t('shieldSpecialSummer2016HealerText'),
    notes: t('shieldSpecialSummer2016HealerNotes', { con: 9 }),
    textlocaleKey: 'shieldSpecialSummer2016HealerText',
    notesLocalKey: 'shieldSpecialSummer2016HealerNotes',
    value: 70,
    con: 9,
  },
  fall2016Rogue: {
    event: EVENTS.fall2016,
    specialClass: 'rogue',
    text: t('shieldSpecialFall2016RogueText'),
    notes: t('shieldSpecialFall2016RogueNotes', { str: 8 }),
    textlocaleKey: 'shieldSpecialFall2016RogueText',
    notesLocalKey: 'shieldSpecialFall2016RogueNotes',
    value: 80,
    str: 8,
  },
  fall2016Warrior: {
    event: EVENTS.fall2016,
    specialClass: 'warrior',
    text: t('shieldSpecialFall2016WarriorText'),
    notes: t('shieldSpecialFall2016WarriorNotes', { con: 7 }),
    textlocaleKey: 'shieldSpecialFall2016WarriorText',
    notesLocalKey: 'shieldSpecialFall2016WarriorNotes',
    value: 70,
    con: 7,
  },
  fall2016Healer: {
    event: EVENTS.fall2016,
    specialClass: 'healer',
    text: t('shieldSpecialFall2016HealerText'),
    notes: t('shieldSpecialFall2016HealerNotes', { con: 9 }),
    textlocaleKey: 'shieldSpecialFall2016HealerText',
    notesLocalKey: 'shieldSpecialFall2016HealerNotes',
    value: 70,
    con: 9,
  },
  winter2017Rogue: {
    event: EVENTS.winter2017,
    specialClass: 'rogue',
    text: t('shieldSpecialWinter2017RogueText'),
    notes: t('shieldSpecialWinter2017RogueNotes', { str: 8 }),
    textlocaleKey: 'shieldSpecialWinter2017RogueText',
    notesLocalKey: 'shieldSpecialWinter2017RogueNotes',
    value: 80,
    str: 8,
  },
  winter2017Warrior: {
    event: EVENTS.winter2017,
    specialClass: 'warrior',
    text: t('shieldSpecialWinter2017WarriorText'),
    notes: t('shieldSpecialWinter2017WarriorNotes', { con: 7 }),
    textlocaleKey: 'shieldSpecialWinter2017WarriorText',
    notesLocalKey: 'shieldSpecialWinter2017WarriorNotes',
    value: 70,
    con: 7,
  },
  winter2017Healer: {
    event: EVENTS.winter2017,
    specialClass: 'healer',
    text: t('shieldSpecialWinter2017HealerText'),
    notes: t('shieldSpecialWinter2017HealerNotes', { con: 9 }),
    textlocaleKey: 'shieldSpecialWinter2017HealerText',
    notesLocalKey: 'shieldSpecialWinter2017HealerNotes',
    value: 70,
    con: 9,
  },
};

let weapon = {
  0: backerGear.weaponSpecial0,
  1: contributorGear.weaponSpecial1,
  2: backerGear.weaponSpecial2,
  3: backerGear.weaponSpecial3,
  critical: contributorGear.weaponSpecialCritical,
  takeThis: takeThisGear.weaponSpecialTakeThis,
  tridentOfCrashingTides: {
    text: t('weaponSpecialTridentOfCrashingTidesText'),
    notes: t('weaponSpecialTridentOfCrashingTidesNotes', { int: 15 }),
    textlocaleKey: 'weaponSpecialTridentOfCrashingTidesText',
    notesLocalKey: 'weaponSpecialTridentOfCrashingTidesNotes',
    int: 15,
    value: 130,
    canOwn: ownsItem('weapon_special_tridentOfCrashingTides'),
  },
  taskwoodsLantern: {
    text: t('weaponSpecialTaskwoodsLanternText'),
    notes: t('weaponSpecialTaskwoodsLanternNotes', { attrs: 15 }),
    textlocaleKey: 'weaponSpecialTaskwoodsLanternText',
    notesLocalKey: 'weaponSpecialTaskwoodsLanternNotes',
    twoHanded: true,
    per: 15,
    int: 15,
    value: 130,
    canOwn: ownsItem('weapon_special_taskwoodsLantern'),
  },
  bardInstrument: {
    text: t('weaponSpecialBardInstrumentText'),
    notes: t('weaponSpecialBardInstrumentNotes', { attrs: 4 }),
    textlocaleKey: 'weaponSpecialBardInstrumentText',
    notesLocalKey: 'weaponSpecialBardInstrumentNotes',
    twoHanded: true,
    per: 4,
    int: 4,
    value: 0,
    canOwn: ownsItem('weapon_special_bardInstrument'),
  },
  lunarScythe: {
    text: t('weaponSpecialLunarScytheText'),
    notes: t('weaponSpecialLunarScytheNotes', { attrs: 7 }),
    textlocaleKey: 'weaponSpecialLunarScytheText',
    notesLocalKey: 'weaponSpecialLunarScytheNotes',
    twoHanded: true,
    str: 7,
    per: 7,
    value: 130,
    canOwn: ownsItem('weapon_special_lunarScythe'),
  },
  mammothRiderSpear: {
    text: t('weaponSpecialMammothRiderSpearText'),
    notes: t('weaponSpecialMammothRiderSpearNotes', { int: 15 }),
    textlocaleKey: 'weaponSpecialMammothRiderSpearText',
    notesLocalKey: 'weaponSpecialMammothRiderSpearNotes',
    int: 15,
    value: 130,
    canOwn: ownsItem('weapon_special_mammothRiderSpear'),
  },
  pageBanner: {
    text: t('weaponSpecialPageBannerText'),
    notes: t('weaponSpecialPageBannerNotes', { str: 16 }),
    textlocaleKey: 'weaponSpecialPageBannerText',
    notesLocalKey: 'weaponSpecialPageBannerNotes',
    str: 16,
    value: 0,
    canOwn: ownsItem('weapon_special_pageBanner'),
  },
  yeti: {
    event: EVENTS.winter,
    specialClass: 'warrior',
    text: t('weaponSpecialYetiText'),
    notes: t('weaponSpecialYetiNotes', { str: 15 }),
    textlocaleKey: 'weaponSpecialYetiText',
    notesLocalKey: 'weaponSpecialYetiNotes',
    str: 15,
    value: 90,
    canBuy: () => {
      return true;
    },
  },
  ski: {
    event: EVENTS.winter,
    specialClass: 'rogue',
    text: t('weaponSpecialSkiText'),
    notes: t('weaponSpecialSkiNotes', { str: 8 }),
    textlocaleKey: 'weaponSpecialSkiText',
    notesLocalKey: 'weaponSpecialSkiNotes',
    str: 8,
    value: 90,
    canBuy: () => {
      return true;
    },
  },
  candycane: {
    event: EVENTS.winter,
    specialClass: 'wizard',
    twoHanded: true,
    text: t('weaponSpecialCandycaneText'),
    notes: t('weaponSpecialCandycaneNotes', { int: 15, per: 7 }),
    textlocaleKey: 'weaponSpecialCandycaneText',
    notesLocalKey: 'weaponSpecialCandycaneNotes',
    int: 15,
    per: 7,
    value: 160,
    canBuy: () => {
      return true;
    },
  },
  snowflake: {
    event: EVENTS.winter,
    specialClass: 'healer',
    text: t('weaponSpecialSnowflakeText'),
    notes: t('weaponSpecialSnowflakeNotes', { int: 9 }),
    textlocaleKey: 'weaponSpecialSnowflakeText',
    notesLocalKey: 'weaponSpecialSnowflakeNotes',
    int: 9,
    value: 90,
    canBuy: () => {
      return true;
    },
  },
  springRogue: {
    event: EVENTS.spring,
    specialClass: 'rogue',
    text: t('weaponSpecialSpringRogueText'),
    notes: t('weaponSpecialSpringRogueNotes', { str: 8 }),
    textlocaleKey: 'weaponSpecialSpringRogueText',
    notesLocalKey: 'weaponSpecialSpringRogueNotes',
    value: 80,
    str: 8,
  },
  springWarrior: {
    event: EVENTS.spring,
    specialClass: 'warrior',
    text: t('weaponSpecialSpringWarriorText'),
    notes: t('weaponSpecialSpringWarriorNotes', { str: 15 }),
    textlocaleKey: 'weaponSpecialSpringWarriorText',
    notesLocalKey: 'weaponSpecialSpringWarriorNotes',
    value: 90,
    str: 15,
  },
  springMage: {
    event: EVENTS.spring,
    specialClass: 'wizard',
    twoHanded: true,
    text: t('weaponSpecialSpringMageText'),
    notes: t('weaponSpecialSpringMageNotes', { int: 15, per: 7 }),
    textlocaleKey: 'weaponSpecialSpringMageText',
    notesLocalKey: 'weaponSpecialSpringMageNotes',
    value: 160,
    int: 15,
    per: 7,
  },
  springHealer: {
    event: EVENTS.spring,
    specialClass: 'healer',
    text: t('weaponSpecialSpringHealerText'),
    notes: t('weaponSpecialSpringHealerNotes', { int: 9 }),
    textlocaleKey: 'weaponSpecialSpringHealerText',
    notesLocalKey: 'weaponSpecialSpringHealerNotes',
    value: 90,
    int: 9,
  },
  summerRogue: {
    event: EVENTS.summer,
    specialClass: 'rogue',
    text: t('weaponSpecialSummerRogueText'),
    notes: t('weaponSpecialSummerRogueNotes', { str: 8 }),
    textlocaleKey: 'weaponSpecialSummerRogueText',
    notesLocalKey: 'weaponSpecialSummerRogueNotes',
    value: 80,
    str: 8,
  },
  summerWarrior: {
    event: EVENTS.summer,
    specialClass: 'warrior',
    text: t('weaponSpecialSummerWarriorText'),
    notes: t('weaponSpecialSummerWarriorNotes', { str: 15 }),
    textlocaleKey: 'weaponSpecialSummerWarriorText',
    notesLocalKey: 'weaponSpecialSummerWarriorNotes',
    value: 90,
    str: 15,
  },
  summerMage: {
    event: EVENTS.summer,
    specialClass: 'wizard',
    twoHanded: true,
    text: t('weaponSpecialSummerMageText'),
    notes: t('weaponSpecialSummerMageNotes', { int: 15, per: 7 }),
    textlocaleKey: 'weaponSpecialSummerMageText',
    notesLocalKey: 'weaponSpecialSummerMageNotes',
    value: 160,
    int: 15,
    per: 7,
  },
  summerHealer: {
    event: EVENTS.summer,
    specialClass: 'healer',
    text: t('weaponSpecialSummerHealerText'),
    notes: t('weaponSpecialSummerHealerNotes', { int: 9 }),
    textlocaleKey: 'weaponSpecialSummerHealerText',
    notesLocalKey: 'weaponSpecialSummerHealerNotes',
    value: 90,
    int: 9,
  },
  fallRogue: {
    event: EVENTS.fall,
    specialClass: 'rogue',
    text: t('weaponSpecialFallRogueText'),
    notes: t('weaponSpecialFallRogueNotes', { str: 8 }),
    textlocaleKey: 'weaponSpecialFallRogueText',
    notesLocalKey: 'weaponSpecialFallRogueNotes',
    value: 80,
    str: 8,
  },
  fallWarrior: {
    event: EVENTS.fall,
    specialClass: 'warrior',
    text: t('weaponSpecialFallWarriorText'),
    notes: t('weaponSpecialFallWarriorNotes', { str: 15 }),
    textlocaleKey: 'weaponSpecialFallWarriorText',
    notesLocalKey: 'weaponSpecialFallWarriorNotes',
    value: 90,
    str: 15,
  },
  fallMage: {
    event: EVENTS.fall,
    specialClass: 'wizard',
    twoHanded: true,
    text: t('weaponSpecialFallMageText'),
    notes: t('weaponSpecialFallMageNotes', { int: 15, per: 7 }),
    textlocaleKey: 'weaponSpecialFallMageText',
    notesLocalKey: 'weaponSpecialFallMageNotes',
    value: 160,
    int: 15,
    per: 7,
  },
  fallHealer: {
    event: EVENTS.fall,
    specialClass: 'healer',
    text: t('weaponSpecialFallHealerText'),
    notes: t('weaponSpecialFallHealerNotes', { int: 9 }),
    textlocaleKey: 'weaponSpecialFallHealerText',
    notesLocalKey: 'weaponSpecialFallHealerNotes',
    value: 90,
    int: 9,
  },
  winter2015Rogue: {
    event: EVENTS.winter2015,
    specialClass: 'rogue',
    text: t('weaponSpecialWinter2015RogueText'),
    notes: t('weaponSpecialWinter2015RogueNotes', { str: 8 }),
    textlocaleKey: 'weaponSpecialWinter2015RogueText',
    notesLocalKey: 'weaponSpecialWinter2015RogueNotes',
    value: 80,
    str: 8,
    canBuy: () => {
      return true;
    },
  },
  winter2015Warrior: {
    event: EVENTS.winter2015,
    specialClass: 'warrior',
    text: t('weaponSpecialWinter2015WarriorText'),
    notes: t('weaponSpecialWinter2015WarriorNotes', { str: 15 }),
    textlocaleKey: 'weaponSpecialWinter2015WarriorText',
    notesLocalKey: 'weaponSpecialWinter2015WarriorNotes',
    value: 90,
    str: 15,
    canBuy: () => {
      return true;
    },
  },
  winter2015Mage: {
    event: EVENTS.winter2015,
    specialClass: 'wizard',
    twoHanded: true,
    text: t('weaponSpecialWinter2015MageText'),
    notes: t('weaponSpecialWinter2015MageNotes', { int: 15, per: 7 }),
    textlocaleKey: 'weaponSpecialWinter2015MageText',
    notesLocalKey: 'weaponSpecialWinter2015MageNotes',
    value: 160,
    int: 15,
    per: 7,
    canBuy: () => {
      return true;
    },
  },
  winter2015Healer: {
    event: EVENTS.winter2015,
    specialClass: 'healer',
    text: t('weaponSpecialWinter2015HealerText'),
    notes: t('weaponSpecialWinter2015HealerNotes', { int: 9 }),
    textlocaleKey: 'weaponSpecialWinter2015HealerText',
    notesLocalKey: 'weaponSpecialWinter2015HealerNotes',
    value: 90,
    int: 9,
    canBuy: () => {
      return true;
    },
  },
  spring2015Rogue: {
    event: EVENTS.spring2015,
    specialClass: 'rogue',
    text: t('weaponSpecialSpring2015RogueText'),
    notes: t('weaponSpecialSpring2015RogueNotes', { str: 8 }),
    textlocaleKey: 'weaponSpecialSpring2015RogueText',
    notesLocalKey: 'weaponSpecialSpring2015RogueNotes',
    value: 80,
    str: 8,
  },
  spring2015Warrior: {
    event: EVENTS.spring2015,
    specialClass: 'warrior',
    text: t('weaponSpecialSpring2015WarriorText'),
    notes: t('weaponSpecialSpring2015WarriorNotes', { str: 15 }),
    textlocaleKey: 'weaponSpecialSpring2015WarriorText',
    notesLocalKey: 'weaponSpecialSpring2015WarriorNotes',
    value: 90,
    str: 15,
  },
  spring2015Mage: {
    event: EVENTS.spring2015,
    specialClass: 'wizard',
    twoHanded: true,
    text: t('weaponSpecialSpring2015MageText'),
    notes: t('weaponSpecialSpring2015MageNotes', { int: 15, per: 7 }),
    textlocaleKey: 'weaponSpecialSpring2015MageText',
    notesLocalKey: 'weaponSpecialSpring2015MageNotes',
    value: 160,
    int: 15,
    per: 7,
  },
  spring2015Healer: {
    event: EVENTS.spring2015,
    specialClass: 'healer',
    text: t('weaponSpecialSpring2015HealerText'),
    notes: t('weaponSpecialSpring2015HealerNotes', { int: 9 }),
    textlocaleKey: 'weaponSpecialSpring2015HealerText',
    notesLocalKey: 'weaponSpecialSpring2015HealerNotes',
    value: 90,
    int: 9,
  },
  summer2015Rogue: {
    event: EVENTS.summer2015,
    specialClass: 'rogue',
    text: t('weaponSpecialSummer2015RogueText'),
    notes: t('weaponSpecialSummer2015RogueNotes', { str: 8 }),
    textlocaleKey: 'weaponSpecialSummer2015RogueText',
    notesLocalKey: 'weaponSpecialSummer2015RogueNotes',
    value: 80,
    str: 8,
  },
  summer2015Warrior: {
    event: EVENTS.summer2015,
    specialClass: 'warrior',
    text: t('weaponSpecialSummer2015WarriorText'),
    notes: t('weaponSpecialSummer2015WarriorNotes', { str: 15 }),
    textlocaleKey: 'weaponSpecialSummer2015WarriorText',
    notesLocalKey: 'weaponSpecialSummer2015WarriorNotes',
    value: 90,
    str: 15,
  },
  summer2015Mage: {
    event: EVENTS.summer2015,
    specialClass: 'wizard',
    twoHanded: true,
    text: t('weaponSpecialSummer2015MageText'),
    notes: t('weaponSpecialSummer2015MageNotes', { int: 15, per: 7 }),
    textlocaleKey: 'weaponSpecialSummer2015MageText',
    notesLocalKey: 'weaponSpecialSummer2015MageNotes',
    value: 160,
    int: 15,
    per: 7,
  },
  summer2015Healer: {
    event: EVENTS.summer2015,
    specialClass: 'healer',
    text: t('weaponSpecialSummer2015HealerText'),
    notes: t('weaponSpecialSummer2015HealerNotes', { int: 9 }),
    textlocaleKey: 'weaponSpecialSummer2015HealerText',
    notesLocalKey: 'weaponSpecialSummer2015HealerNotes',
    value: 90,
    int: 9,
  },
  fall2015Rogue: {
    event: EVENTS.fall2015,
    specialClass: 'rogue',
    text: t('weaponSpecialFall2015RogueText'),
    notes: t('weaponSpecialFall2015RogueNotes', { str: 8 }),
    textlocaleKey: 'weaponSpecialFall2015RogueText',
    notesLocalKey: 'weaponSpecialFall2015RogueNotes',
    value: 80,
    str: 8,
  },
  fall2015Warrior: {
    event: EVENTS.fall2015,
    specialClass: 'warrior',
    text: t('weaponSpecialFall2015WarriorText'),
    notes: t('weaponSpecialFall2015WarriorNotes', { str: 15 }),
    textlocaleKey: 'weaponSpecialFall2015WarriorText',
    notesLocalKey: 'weaponSpecialFall2015WarriorNotes',
    value: 90,
    str: 15,
  },
  fall2015Mage: {
    event: EVENTS.fall2015,
    specialClass: 'wizard',
    twoHanded: true,
    text: t('weaponSpecialFall2015MageText'),
    notes: t('weaponSpecialFall2015MageNotes', { int: 15, per: 7 }),
    textlocaleKey: 'weaponSpecialFall2015MageText',
    notesLocalKey: 'weaponSpecialFall2015MageNotes',
    value: 160,
    int: 15,
    per: 7,
  },
  fall2015Healer: {
    event: EVENTS.fall2015,
    specialClass: 'healer',
    text: t('weaponSpecialFall2015HealerText'),
    notes: t('weaponSpecialFall2015HealerNotes', { int: 9 }),
    textlocaleKey: 'weaponSpecialFall2015HealerText',
    notesLocalKey: 'weaponSpecialFall2015HealerNotes',
    value: 90,
    int: 9,
  },
  winter2016Rogue: {
    event: EVENTS.winter2016,
    specialClass: 'rogue',
    text: t('weaponSpecialWinter2016RogueText'),
    notes: t('weaponSpecialWinter2016RogueNotes', { str: 8 }),
    textlocaleKey: 'weaponSpecialWinter2016RogueText',
    notesLocalKey: 'weaponSpecialWinter2016RogueNotes',
    value: 80,
    str: 8,
    canBuy: () => {
      return true;
    },
  },
  winter2016Warrior: {
    event: EVENTS.winter2016,
    specialClass: 'warrior',
    text: t('weaponSpecialWinter2016WarriorText'),
    notes: t('weaponSpecialWinter2016WarriorNotes', { str: 15 }),
    textlocaleKey: 'weaponSpecialWinter2016WarriorText',
    notesLocalKey: 'weaponSpecialWinter2016WarriorNotes',
    value: 90,
    str: 15,
    canBuy: () => {
      return true;
    },
  },
  winter2016Mage: {
    event: EVENTS.winter2016,
    specialClass: 'wizard',
    twoHanded: true,
    text: t('weaponSpecialWinter2016MageText'),
    notes: t('weaponSpecialWinter2016MageNotes', { int: 15, per: 7 }),
    textlocaleKey: 'weaponSpecialWinter2016MageText',
    notesLocalKey: 'weaponSpecialWinter2016MageNotes',
    value: 160,
    int: 15,
    per: 7,
    canBuy: () => {
      return true;
    },
  },
  winter2016Healer: {
    event: EVENTS.winter2016,
    specialClass: 'healer',
    text: t('weaponSpecialWinter2016HealerText'),
    notes: t('weaponSpecialWinter2016HealerNotes', { int: 9 }),
    textlocaleKey: 'weaponSpecialWinter2016HealerText',
    notesLocalKey: 'weaponSpecialWinter2016HealerNotes',
    value: 90,
    int: 9,
    canBuy: () => {
      return true;
    },
  },
  spring2016Rogue: {
    event: EVENTS.spring2016,
    specialClass: 'rogue',
    text: t('weaponSpecialSpring2016RogueText'),
    notes: t('weaponSpecialSpring2016RogueNotes', { str: 8 }),
    textlocaleKey: 'weaponSpecialSpring2016RogueText',
    notesLocalKey: 'weaponSpecialSpring2016RogueNotes',
    value: 80,
    str: 8,
  },
  spring2016Warrior: {
    event: EVENTS.spring2016,
    specialClass: 'warrior',
    text: t('weaponSpecialSpring2016WarriorText'),
    notes: t('weaponSpecialSpring2016WarriorNotes', { str: 15 }),
    textlocaleKey: 'weaponSpecialSpring2016WarriorText',
    notesLocalKey: 'weaponSpecialSpring2016WarriorNotes',
    value: 90,
    str: 15,
  },
  spring2016Mage: {
    event: EVENTS.spring2016,
    specialClass: 'wizard',
    twoHanded: true,
    text: t('weaponSpecialSpring2016MageText'),
    notes: t('weaponSpecialSpring2016MageNotes', { int: 15, per: 7 }),
    textlocaleKey: 'weaponSpecialSpring2016MageText',
    notesLocalKey: 'weaponSpecialSpring2016MageNotes',
    value: 160,
    int: 15,
    per: 7,
  },
  spring2016Healer: {
    event: EVENTS.spring2016,
    specialClass: 'healer',
    text: t('weaponSpecialSpring2016HealerText'),
    notes: t('weaponSpecialSpring2016HealerNotes', { int: 9 }),
    textlocaleKey: 'weaponSpecialSpring2016HealerText',
    notesLocalKey: 'weaponSpecialSpring2016HealerNotes',
    value: 90,
    int: 9,
  },
  summer2016Rogue: {
    event: EVENTS.summer2016,
    specialClass: 'rogue',
    text: t('weaponSpecialSummer2016RogueText'),
    notes: t('weaponSpecialSummer2016RogueNotes', { str: 8 }),
    textlocaleKey: 'weaponSpecialSummer2016RogueText',
    notesLocalKey: 'weaponSpecialSummer2016RogueNotes',
    value: 80,
    str: 8,
  },
  summer2016Warrior: {
    event: EVENTS.summer2016,
    specialClass: 'warrior',
    text: t('weaponSpecialSummer2016WarriorText'),
    notes: t('weaponSpecialSummer2016WarriorNotes', { str: 15 }),
    textlocaleKey: 'weaponSpecialSummer2016WarriorText',
    notesLocalKey: 'weaponSpecialSummer2016WarriorNotes',
    value: 90,
    str: 15,
  },
  summer2016Mage: {
    event: EVENTS.summer2016,
    specialClass: 'wizard',
    twoHanded: true,
    text: t('weaponSpecialSummer2016MageText'),
    notes: t('weaponSpecialSummer2016MageNotes', { int: 15, per: 7 }),
    textlocaleKey: 'weaponSpecialSummer2016MageText',
    notesLocalKey: 'weaponSpecialSummer2016MageNotes',
    value: 160,
    int: 15,
    per: 7,
  },
  summer2016Healer: {
    event: EVENTS.summer2016,
    specialClass: 'healer',
    text: t('weaponSpecialSummer2016HealerText'),
    notes: t('weaponSpecialSummer2016HealerNotes', { int: 9 }),
    textlocaleKey: 'weaponSpecialSummer2016HealerText',
    notesLocalKey: 'weaponSpecialSummer2016HealerNotes',
    value: 90,
    int: 9,
  },
  fall2016Rogue: {
    event: EVENTS.fall2016,
    specialClass: 'rogue',
    text: t('weaponSpecialFall2016RogueText'),
    notes: t('weaponSpecialFall2016RogueNotes', { str: 8 }),
    textlocaleKey: 'weaponSpecialFall2016RogueText',
    notesLocalKey: 'weaponSpecialFall2016RogueNotes',
    value: 80,
    str: 8,
  },
  fall2016Warrior: {
    event: EVENTS.fall2016,
    specialClass: 'warrior',
    text: t('weaponSpecialFall2016WarriorText'),
    notes: t('weaponSpecialFall2016WarriorNotes', { str: 15 }),
    textlocaleKey: 'weaponSpecialFall2016WarriorText',
    notesLocalKey: 'weaponSpecialFall2016WarriorNotes',
    value: 90,
    str: 15,
  },
  fall2016Mage: {
    event: EVENTS.fall2016,
    specialClass: 'wizard',
    twoHanded: true,
    text: t('weaponSpecialFall2016MageText'),
    notes: t('weaponSpecialFall2016MageNotes', { int: 15, per: 7 }),
    textlocaleKey: 'weaponSpecialFall2016MageText',
    notesLocalKey: 'weaponSpecialFall2016MageNotes',
    value: 160,
    int: 15,
    per: 7,
  },
  fall2016Healer: {
    event: EVENTS.fall2016,
    specialClass: 'healer',
    text: t('weaponSpecialFall2016HealerText'),
    notes: t('weaponSpecialFall2016HealerNotes', { int: 9 }),
    textlocaleKey: 'weaponSpecialFall2016HealerText',
    notesLocalKey: 'weaponSpecialFall2016HealerNotes',
    value: 90,
    int: 9,
  },
  winter2017Rogue: {
    event: EVENTS.winter2017,
    specialClass: 'rogue',
    text: t('weaponSpecialWinter2017RogueText'),
    notes: t('weaponSpecialWinter2017RogueNotes', { str: 8 }),
    textlocaleKey: 'weaponSpecialWinter2017RogueText',
    notesLocalKey: 'weaponSpecialWinter2017RogueNotes',
    value: 80,
    str: 8,
  },
  winter2017Warrior: {
    event: EVENTS.winter2017,
    specialClass: 'warrior',
    text: t('weaponSpecialWinter2017WarriorText'),
    notes: t('weaponSpecialWinter2017WarriorNotes', { str: 15 }),
    textlocaleKey: 'weaponSpecialWinter2017WarriorText',
    notesLocalKey: 'weaponSpecialWinter2017WarriorNotes',
    value: 90,
    str: 15,
  },
  winter2017Mage: {
    event: EVENTS.winter2017,
    specialClass: 'wizard',
    twoHanded: true,
    text: t('weaponSpecialWinter2017MageText'),
    notes: t('weaponSpecialWinter2017MageNotes', { int: 15, per: 7 }),
    textlocaleKey: 'weaponSpecialWinter2017MageText',
    notesLocalKey: 'weaponSpecialWinter2017MageNotes',
    value: 170,
    int: 15,
    per: 7,
  },
  winter2017Healer: {
    event: EVENTS.winter2017,
    specialClass: 'healer',
    text: t('weaponSpecialWinter2017HealerText'),
    notes: t('weaponSpecialWinter2017HealerNotes', { int: 9 }),
    textlocaleKey: 'weaponSpecialWinter2017HealerText',
    notesLocalKey: 'weaponSpecialWinter2017HealerNotes',
    value: 90,
    int: 9,
  },
};

let specialSet = {
  armor,
  back,
  body,
  eyewear,
  head,
  headAccessory,
  shield,
  weapon,
};

module.exports = specialSet;
