// Generated by CoffeeScript 1.3.3
var userSchema;

module.exports.userSchema = userSchema = {
  stats: {
    money: 0,
    exp: 0,
    lvl: 1,
    hp: 50
  },
  items: {
    itemsEnabled: false,
    armor: 0,
    weapon: 0
  },
  tasks: {},
  habitIds: [],
  dailyIds: [],
  todoIds: [],
  completedIds: [],
  rewardIds: []
};

module.exports.updateSchema = function(model) {};
