const ANIMAL_SET_ACHIEVEMENTS = {
  legendaryBestiary: {
    type: 'pet',
    species: [
      'Dragon',
      'FlyingPig',
      'Gryphon',
      'SeaSerpent',
      'Unicorn',
    ],
    achievementKey: 'legendaryBestiary',
    notificationType: 'ACHIEVEMENT_ANIMAL_SET',
  },
  birdsOfAFeather: {
    type: 'pet',
    species: [
      'FlyingPig',
      'Owl',
      'Parrot',
      'Pterodactyl',
      'Gryphon',
      'Falcon',
      'Rooster',
      'Peacock',
    ],
    achievementKey: 'birdsOfAFeather',
    notificationType: 'ACHIEVEMENT_ANIMAL_SET',
  },
  domesticated: {
    type: 'pet',
    species: [
      'Ferret',
      'GuineaPig',
      'Rooster',
      'FlyingPig',
      'Rat',
      'Bunny',
      'Horse',
      'Cow',
    ],
    achievementKey: 'domesticated',
    notificationType: 'ACHIEVEMENT_ANIMAL_SET',
  },
  reptacularRumble: {
    type: 'pet',
    species: [
      'Alligator',
      'Pterodactyl',
      'Snake',
      'Triceratops',
      'TRex',
      'Turtle',
      'Velociraptor',
    ],
    achievementKey: 'reptacularRumble',
    notificationType: 'ACHIEVEMENT_ANIMAL_SET',
  },
  woodlandWizard: {
    type: 'pet',
    species: [
      'Badger',
      'BearCub',
      'Deer',
      'Fox',
      'Frog',
      'Hedgehog',
      'Owl',
      'Snail',
      'Squirrel',
      'Treeling',
    ],
    achievementKey: 'woodlandWizard',
    notificationType: 'ACHIEVEMENT_ANIMAL_SET',
  },
  zodiacZookeeper: {
    type: 'pet',
    species: [
      'Rat',
      'Cow',
      'Bunny',
      'Snake',
      'Horse',
      'Sheep',
      'Monkey',
      'Rooster',
      'Wolf',
      'TigerCub',
      'FlyingPig',
      'Dragon',
    ],
    achievementKey: 'zodiacZookeeper',
    notificationType: 'ACHIEVEMENT_ANIMAL_SET',
  },
};

export default ANIMAL_SET_ACHIEVEMENTS;
