const ANIMAL_SET_ACHIEVEMENTS = {
  legendaryBestiary: {
    type: 'pet',
    species: [
      'Dragon',
      'FlyingPig',
      'Gryphon',
      'SeaSerpent',
      'Unicorn',
    ],
    achievementKey: 'legendaryBestiary',
    notificationType: 'ACHIEVEMENT',
  },
  birdsOfAFeather: {
    type: 'pet',
    species: [
      'FlyingPig',
      'Owl',
      'Parrot',
      'Pterodactyl',
      'Gryphon',
      'Falcon',
      'Rooster',
      'Peacock',
    ],
    achievementKey: 'birdsOfAFeather',
    notificationType: 'ACHIEVEMENT',
  },
  bonelessBoss: {
    type: 'pet',
    species: [
      'Beetle',
      'Butterfly',
      'Cuttlefish',
      'Nudibranch',
      'Octopus',
      'Snail',
      'Spider',
    ],
    achievementKey: 'bonelessBoss',
    notificationType: 'ACHIEVEMENT',
  },
  cats: {
    type: 'pet',
    species: [
      'Cheetah',
      'LionCub',
      'Sabretooth',
      'TigerCub',
    ],
    achievementKey: 'cats',
    notificationType: 'ACHIEVEMENT',
  },
  dinosaurDynasty: {
    type: 'pet',
    species: [
      'Falcon',
      'Owl',
      'Parrot',
      'Peacock',
      'Penguin',
      'Rooster',
      'Pterodactyl',
      'TRex',
      'Triceratops',
      'Velociraptor',
    ],
    achievementKey: 'dinosaurDynasty',
    notificationType: 'ACHIEVEMENT',
  },
  domesticated: {
    type: 'pet',
    species: [
      'Ferret',
      'GuineaPig',
      'Rooster',
      'FlyingPig',
      'Rat',
      'Bunny',
      'Horse',
      'Cow',
    ],
    achievementKey: 'domesticated',
    notificationType: 'ACHIEVEMENT',
  },
  duneBuddy: {
    type: 'pet',
    species: [
      'Armadillo',
      'Cactus',
      'Fox',
      'Frog',
      'Snake',
      'Spider',
    ],
    achievementKey: 'duneBuddy',
    notificationType: 'ACHIEVEMENT',
  },
  plantParent: {
    type: 'pet',
    species: [
      'Cactus',
      'Treeling',
    ],
    achievementKey: 'plantParent',
    notificationType: 'ACHIEVEMENT',
  },
  polarPro: {
    type: 'pet',
    species: [
      'BearCub',
      'Fox',
      'Penguin',
      'Whale',
      'Wolf',
    ],
    achievementKey: 'polarPro',
    notificationType: 'ACHIEVEMENT',
  },
  reptacularRumble: {
    type: 'pet',
    species: [
      'Alligator',
      'Pterodactyl',
      'Snake',
      'Triceratops',
      'TRex',
      'Turtle',
      'Velociraptor',
    ],
    achievementKey: 'reptacularRumble',
    notificationType: 'ACHIEVEMENT',
  },
  rodentRuler: {
    type: 'pet',
    species: [
      'Rat',
      'GuineaPig',
      'Squirrel',
    ],
    achievementKey: 'rodentRuler',
    notificationType: 'ACHIEVEMENT',
  },
  roughRider: {
    type: 'petMount',
    species: [
      'Cactus',
      'Hedgehog',
      'Rock',
    ],
    achievementKey: 'roughRider',
    notificationType: 'ACHIEVEMENT',
  },
  woodlandWizard: {
    type: 'pet',
    species: [
      'Badger',
      'BearCub',
      'Deer',
      'Fox',
      'Frog',
      'Hedgehog',
      'Owl',
      'Snail',
      'Squirrel',
      'Treeling',
    ],
    achievementKey: 'woodlandWizard',
    notificationType: 'ACHIEVEMENT',
  },
  zodiacZookeeper: {
    type: 'pet',
    species: [
      'Rat',
      'Cow',
      'Bunny',
      'Snake',
      'Horse',
      'Sheep',
      'Monkey',
      'Rooster',
      'Wolf',
      'TigerCub',
      'FlyingPig',
      'Dragon',
    ],
    achievementKey: 'zodiacZookeeper',
    notificationType: 'ACHIEVEMENT',
  },
};

export default ANIMAL_SET_ACHIEVEMENTS;
