echo Installing Xvfb...
apt-get install -qq xvfb
echo Installing Java7...
apt-get install -qq openjdk-7-jre 
echo Downloading Firefox...
wget http://sourceforge.net/projects/ubuntuzilla/files/mozilla/apt/pool/main/f/firefox-mozilla-build/firefox-mozilla-build_40.0.3-0ubuntu1_amd64.deb/download -O firefox.deb >/dev/null 2>&1
echo Installing Firefox...
dpkg -i firefox.deb
rm firefox.deb
