echo Installing GraphicsMagick - provides gm and convert...
apt-get install -qq graphicsmagick

echo Installing phantomjs and dependency...
apt-get install -qq libicu48

echo Installing requirements for gulp.spritesmith...
apt-get install -qq pkg-config libcairo2-dev libjpeg-dev
