import {transform, defaults} from 'lodash';

//--------------------------------------------------
// Pets and Mounts are generated by eggs * potions
//
// { <egg_key>-<potion_key>: true }
//
// <egg_key> - the key of the egg the animal hatched from
// <potion_key> - the potion that hatched the animal
//
//--------------------------------------------------
// Special Pets and Mounts
// { <animal_type>-<fake_potion>: <transifex_key> }
//
// <animal_type> - could be existing animal or a totally new animal
// <fake_potion> - if a unique animal, potion is Base, if it's a special version of an existing animal, the fake potion is a different from a normal hatching potion
//--------------------------------------------------

import hatchingPotions from '../hatching-potions';
import dropEggs from '../eggs/drops';
import questEggs from '../eggs/quest';

import specialPets from './special-pets';
import specialMounts from './special-mounts';

let dropPets = generateAnimalSet(dropEggs);
let questPets = generateAnimalSet(questEggs);
let dropMounts = generateAnimalSet(dropEggs);
let questMounts = generateAnimalSet(questEggs);

function generateAnimalSet(set) {
  return transform(set, (m, egg) => {
    defaults(m, transform(hatchingPotions, (m2, pot) => {
      return m2[egg.key + "-" + pot.key] = true;
    }));
  });
}

export default {
  dropPets: dropPets,
  dropMounts: dropMounts,
  questPets: questPets,
  questMounts: questMounts,
  specialPets: specialPets,
  specialMounts: specialMounts,
}
